(()=>{const topics=window.TCF_TOPICS||[],$=id=>document.getElementById(id),el={sectionFilter:$("sectionFilter"),searchInput:$("searchInput"),topicList:$("topicList"),randomBtn:$("randomBtn"),reviewOnlyBtn:$("reviewOnlyBtn"),topicCounter:$("topicCounter"),topicZh:$("topicZh"),topicFr:$("topicFr"),paragraphTabs:$("paragraphTabs"),promptText:$("promptText"),answerBox:$("answerBox"),wordCount:$("wordCount"),checkBtn:$("checkBtn"),revealBtn:$("revealBtn"),clearBtn:$("clearBtn"),resultPanel:$("resultPanel"),scoreValue:$("scoreValue"),scoreMessage:$("scoreMessage"),userDiff:$("userDiff"),answerDiff:$("answerDiff"),prevBtn:$("prevBtn"),nextBtn:$("nextBtn"),nextSegmentBtn:$("nextSegmentBtn"),statDone:$("statDone"),statReview:$("statReview"),statAttempts:$("statAttempts")};
const KEY="tcf-writing-trainer-v1",saved=(()=>{try{return JSON.parse(localStorage.getItem(KEY)||"{}")}catch{return{}}})(),state={topicId:Number(saved.lastTopicId)||1,segment:Number.isInteger(saved.lastSegment)?saved.lastSegment:0,mode:saved.mode||"paragraph",hint:saved.hint||"zh",statuses:saved.statuses||{},attempts:Number(saved.attempts)||0,reviewOnly:false};
function persist(){localStorage.setItem(KEY,JSON.stringify({lastTopicId:state.topicId,lastSegment:state.segment,mode:state.mode,hint:state.hint,statuses:state.statuses,attempts:state.attempts}))}const current=()=>topics.find(t=>t.id===state.topicId)||topics[0];
function normalize(s){return s.normalize("NFC").replace(/[’‘`]/g,"'").replace(/\s+/g," ").trim()}function tokens(s){return normalize(s).match(/[\p{L}\p{M}]+(?:['’-][\p{L}\p{M}]+)*|\d+|[^\s]/gu)||[]}const comparable=t=>t.toLocaleLowerCase("fr");
function lcsDiff(a,b){const A=tokens(a),B=tokens(b),n=A.length,m=B.length,dp=Array.from({length:n+1},()=>new Uint16Array(m+1));for(let i=n-1;i>=0;i--)for(let j=m-1;j>=0;j--)dp[i][j]=comparable(A[i])===comparable(B[j])?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);let i=0,j=0,matches=0;const user=[],answer=[];while(i<n&&j<m){if(comparable(A[i])===comparable(B[j])){user.push({t:A[i],c:"ok"});answer.push({t:B[j],c:"ok"});matches++;i++;j++}else if(dp[i+1][j]>=dp[i][j+1])user.push({t:A[i++],c:"extra"});else answer.push({t:B[j++],c:"miss"})}while(i<n)user.push({t:A[i++],c:"extra"});while(j<m)answer.push({t:B[j++],c:"miss"});return{user,answer,score:Math.round(2*matches/Math.max(1,n+m)*100)}}
function esc(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function renderTokens(arr){let out="";const punct=/^[.,;:!?…\)\]}]$/,open=/^[\(\[{«]$/;arr.forEach((x,i)=>{const tok="<span"+(x.c==="ok"?"":' class="'+x.c+'"')+">"+esc(x.t)+"</span>";out+=i===0?tok:punct.test(x.t)?tok:" "+tok});return out}
function targetText(){const t=current();return state.mode==="full"?t.paragraphs.map(p=>p.answer).join("\n\n"):t.paragraphs[state.segment].answer}
function promptText(){const t=current();if(state.hint==="none")return"无提示。请直接默写。";if(state.hint==="first"){const arr=state.mode==="full"?t.paragraphs:[t.paragraphs[state.segment]];return arr.map((p,i)=>(state.mode==="full"?i+1+". ":"")+tokens(p.answer).slice(0,8).join(" ")+"…").join("\n\n")}return state.mode==="full"?t.paragraphs.map((p,i)=>i+1+". "+p.hintZh).join("\n"):t.paragraphs[state.segment].hintZh}
function populateSections(){const secs=[...new Set(topics.map(t=>t.section).filter(Boolean))];el.sectionFilter.innerHTML='<option value="">全部主题（'+topics.length+'）</option>'+secs.map(s=>'<option value="'+esc(s)+'">'+esc(s)+"</option>").join("")}
function filteredTopics(){const q=el.searchInput.value.trim().toLowerCase(),sec=el.sectionFilter.value;return topics.filter(t=>(!sec||t.section===sec)&&(!state.reviewOnly||state.statuses[t.id]==="review")&&(!q||(`${t.zhTitle} ${t.frTitle} ${t.section} ${t.subsection}`.toLowerCase().includes(q))))}
function renderTopicList(){const list=filteredTopics();el.topicList.innerHTML=list.length?list.map(t=>{const st=state.statuses[t.id]||"new";return'<button type="button" class="topic-item '+(t.id===state.topicId?"active":"")+'" data-id="'+t.id+'"><span class="dot '+st+'"></span><span class="num">'+String(t.id).padStart(2,"0")+"</span>"+esc(t.zhTitle||t.frTitle)+'<span class="fr">'+esc(t.frTitle)+"</span></button>"}).join(""):'<div style="padding:20px;color:var(--muted)">没有匹配的题目。</div>';el.topicList.querySelectorAll("[data-id]").forEach(b=>b.addEventListener("click",()=>{state.topicId=Number(b.dataset.id);state.segment=0;persist();resetAnswer();render()}))}
function renderStats(){const v=Object.values(state.statuses);el.statDone.textContent=v.filter(x=>x==="mastered").length;el.statReview.textContent=v.filter(x=>x==="review").length;el.statAttempts.textContent=state.attempts}
function renderTabs(){const labels=["1 · Introduction","2 · D’une part","3 · D’autre part","4 · Conclusion"];el.paragraphTabs.innerHTML=labels.map((x,i)=>'<button type="button" role="tab" data-seg="'+i+'" class="'+(state.segment===i?"active":"")+'" '+(state.mode==="full"?"disabled":"")+">"+x+"</button>").join("");el.paragraphTabs.style.opacity=state.mode==="full"?.45:1;el.paragraphTabs.querySelectorAll("[data-seg]").forEach(b=>b.addEventListener("click",()=>{state.segment=Number(b.dataset.seg);persist();resetAnswer();renderPractice()}))}
function renderPractice(){const t=current();el.topicCounter.textContent="第 "+t.id+" / "+topics.length+" 题 · "+t.section+(t.subsection?" · "+t.subsection:"");el.topicZh.textContent=t.zhTitle||"";el.topicFr.textContent=t.frTitle;renderTabs();el.promptText.textContent=promptText();document.querySelectorAll(".mode-btn").forEach(b=>b.classList.toggle("active",b.dataset.mode===state.mode));document.querySelectorAll(".hint-btn").forEach(b=>b.classList.toggle("active",b.dataset.hint===state.hint));document.querySelectorAll(".status-btn").forEach(b=>b.classList.toggle("active",b.dataset.status===(state.statuses[t.id]||"new")));el.nextSegmentBtn.style.visibility=state.mode==="paragraph"?"visible":"hidden";el.nextSegmentBtn.textContent=state.segment<3?"下一段 →":"本题完成 ✓"}
function resetAnswer(){el.answerBox.value="";el.resultPanel.classList.add("hidden");updateWordCount()}function updateWordCount(){el.wordCount.textContent=((el.answerBox.value.match(/[\p{L}\p{M}]+(?:['’][\p{L}\p{M}]+)*/gu)||[]).length)+" mots"}function render(){renderTopicList();renderStats();renderPractice()}
function check(){const user=el.answerBox.value.trim();if(!user){el.answerBox.focus();return}const d=lcsDiff(user,targetText());el.scoreValue.textContent=d.score+"%";el.scoreMessage.textContent=d.score>=97?"非常接近原稿。":d.score>=90?"基本掌握，重点看标出的差异。":d.score>=75?"主体记住了，再复习一下措辞。":"建议先看原稿，再重新默写一遍。";el.userDiff.innerHTML=renderTokens(d.user);el.answerDiff.innerHTML=renderTokens(d.answer);el.resultPanel.classList.remove("hidden");state.attempts++;persist();renderStats()}
function reveal(){el.scoreValue.textContent="原稿";el.scoreMessage.textContent="先对照，再清空重写会更有效。";el.userDiff.textContent=el.answerBox.value.trim()||"（尚未作答）";el.answerDiff.textContent=targetText();el.resultPanel.classList.remove("hidden")}
function moveTopic(delta){const idx=topics.findIndex(t=>t.id===state.topicId),n=(idx+delta+topics.length)%topics.length;state.topicId=topics[n].id;state.segment=0;persist();resetAnswer();render()}
populateSections();el.searchInput.addEventListener("input",renderTopicList);el.sectionFilter.addEventListener("change",renderTopicList);el.randomBtn.addEventListener("click",()=>{const list=filteredTopics();if(!list.length)return;const t=list[Math.floor(Math.random()*list.length)];state.topicId=t.id;state.segment=0;persist();resetAnswer();render()});el.reviewOnlyBtn.addEventListener("click",()=>{state.reviewOnly=!state.reviewOnly;el.reviewOnlyBtn.setAttribute("aria-pressed",String(state.reviewOnly));el.reviewOnlyBtn.classList.toggle("secondary",state.reviewOnly);renderTopicList()});document.querySelectorAll(".mode-btn").forEach(b=>b.addEventListener("click",()=>{state.mode=b.dataset.mode;persist();resetAnswer();renderPractice()}));document.querySelectorAll(".hint-btn").forEach(b=>b.addEventListener("click",()=>{state.hint=b.dataset.hint;persist();renderPractice()}));document.querySelectorAll(".status-btn").forEach(b=>b.addEventListener("click",()=>{state.statuses[state.topicId]=b.dataset.status;persist();render()}));el.answerBox.addEventListener("input",updateWordCount);el.checkBtn.addEventListener("click",check);el.revealBtn.addEventListener("click",reveal);el.clearBtn.addEventListener("click",resetAnswer);el.prevBtn.addEventListener("click",()=>moveTopic(-1));el.nextBtn.addEventListener("click",()=>moveTopic(1));el.nextSegmentBtn.addEventListener("click",()=>{if(state.segment<3){state.segment++;persist();resetAnswer();renderPractice()}else{state.statuses[state.topicId]=state.statuses[state.topicId]||"review";persist();moveTopic(1)}});render()})();