(()=>{const baseTopics=window.TCF_TOPICS||[],exams=window.TCF_EE3_EXAMS||{migrations:[],metadata:{}},topics=[...baseTopics,...exams.migrations],$=id=>document.getElementById(id),el={sectionFilter:$("sectionFilter"),searchInput:$("searchInput"),topicList:$("topicList"),randomBtn:$("randomBtn"),reviewOnlyBtn:$("reviewOnlyBtn"),topicCounter:$("topicCounter"),topicZh:$("topicZh"),topicFr:$("topicFr"),paragraphTabs:$("paragraphTabs"),cardBar:$("cardBar"),cardCounter:$("cardCounter"),shuffleCardsBtn:$("shuffleCardsBtn"),promptText:$("promptText"),answerBox:$("answerBox"),wordCount:$("wordCount"),checkBtn:$("checkBtn"),revealBtn:$("revealBtn"),clearBtn:$("clearBtn"),resultPanel:$("resultPanel"),scoreValue:$("scoreValue"),scoreMessage:$("scoreMessage"),userDiff:$("userDiff"),answerDiff:$("answerDiff"),prevBtn:$("prevBtn"),nextBtn:$("nextBtn"),nextSegmentBtn:$("nextSegmentBtn"),statDone:$("statDone"),statReview:$("statReview"),statAttempts:$("statAttempts")};
const KEY="tcf-writing-trainer-v1",saved=(()=>{try{return JSON.parse(localStorage.getItem(KEY)||"{}")}catch{return{}}})(),state={topicId:Number(saved.lastTopicId)||1,segment:Number.isInteger(saved.lastSegment)?saved.lastSegment:0,cardIndex:Number.isInteger(saved.cardIndex)?saved.cardIndex:0,cardOrder:saved.cardOrder||{},mode:saved.mode||"paragraph",hint:saved.hint||"zh",statuses:saved.statuses||{},attempts:Number(saved.attempts)||0,reviewOnly:false};
for(const t of exams.migrations)window.TCF_TRANSLATIONS[t.id]=t.translations;
let scope=localStorage.getItem(KEY+"-exam-scope")==="exams"||currentExamId(state.topicId)?"exams":"base";
function currentExamId(id){return exams.migrations.some(t=>t.id===id)}
function persist(){localStorage.setItem(KEY,JSON.stringify({lastTopicId:state.topicId,lastSegment:state.segment,cardIndex:state.cardIndex,cardOrder:state.cardOrder,mode:state.mode,hint:state.hint,statuses:state.statuses,attempts:state.attempts}))}const current=()=>topics.find(t=>t.id===state.topicId)||topics[0];
function normalize(s){return s.normalize("NFC").replace(/[’‘`]/g,"'").replace(/\s+/g," ").trim()}function tokens(s){return normalize(s).match(/[\p{L}\p{M}]+(?:['’-][\p{L}\p{M}]+)*|\d+|[^\s]/gu)||[]}const comparable=t=>t.toLocaleLowerCase("fr");
function lcsDiff(a,b){const A=tokens(a),B=tokens(b),n=A.length,m=B.length,dp=Array.from({length:n+1},()=>new Uint16Array(m+1));for(let i=n-1;i>=0;i--)for(let j=m-1;j>=0;j--)dp[i][j]=comparable(A[i])===comparable(B[j])?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);let i=0,j=0,matches=0;const user=[],answer=[];while(i<n&&j<m){if(comparable(A[i])===comparable(B[j])){user.push({t:A[i],c:"ok"});answer.push({t:B[j],c:"ok"});matches++;i++;j++}else if(dp[i+1][j]>=dp[i][j+1])user.push({t:A[i++],c:"extra"});else answer.push({t:B[j++],c:"miss"})}while(i<n)user.push({t:A[i++],c:"extra"});while(j<m)answer.push({t:B[j++],c:"miss"});return{user,answer,score:Math.round(2*matches/Math.max(1,n+m)*100)}}
function esc(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function renderTokens(arr){let out="";const punct=/^[.,;:!?…\)\]}]$/,open=/^[\(\[{«]$/;arr.forEach((x,i)=>{const tok="<span"+(x.c==="ok"?"":' class="'+x.c+'"')+">"+esc(x.t)+"</span>";out+=i===0?tok:punct.test(x.t)?tok:" "+tok});return out}
function splitSentences(s){return (s||"").split(/(?<=[.!?。！？])\s*/).map(x=>x.trim()).filter(Boolean)}
function cleanFrChunk(s){return s.replace(/^(D’une part|D'autre part|D’autre part),\s*/i,"").replace(/^Pour conclure,\s*il me semble que\s*/i,"").replace(/^Parallèlement,\s*il faudrait que\s*/i,"").replace(/^(En effet|De plus|Enfin|Par exemple),\s*/i,"").trim()}
function cleanZhChunk(s){return s.replace(/^(一方面|另一方面|例如|此外|最后|事实上)[，,]\s*/,"").replace(/^总而言之[，,]?我认为/,"").replace(/^与此同时[，,]?/,"").trim()}
function buildCards(t){const tr=window.TCF_TRANSLATIONS&&window.TCF_TRANSLATIONS[t.id];if(!tr)return[];const cards=[];t.paragraphs.forEach((p,pi)=>{const fs=splitSentences(p.answer),zs=splitSentences(tr[pi]||"");fs.forEach((f,si)=>{let z=zs[Math.min(si,zs.length-1)]||tr[pi]||"";if(pi===0&&/tandis que/i.test(f)){const parts=f.split(/,?\s*tandis que\s*/i);const zparts=z.split(/；而|；|，而/);parts.forEach((part,k)=>{let ff=part.replace(/^Certains considèrent qu[’']?/i,"").replace(/^d’autres estiment qu[’']?/i,"").trim();let zz=(zparts[k]||z).replace(/^有些人认为[，,]?/,"").replace(/^而?另一些人则认为[，,]?/,"").trim();if(ff.split(/\s+/).length>=4)cards.push({fr:cleanFrChunk(ff).replace(/^[,;]\s*/,""),zh:cleanZhChunk(zz),role:p.role})});}else if(!(pi===0&&/^De nos jours/i.test(f))){const ff=cleanFrChunk(f),zz=cleanZhChunk(z);if(ff&&ff.split(/\s+/).length>=4)cards.push({fr:ff,zh:zz,role:p.role})}})});return cards.filter(c=>!/^(il me semble|il faudrait|de nos jours|certains considèrent|d’autres estiment)/i.test(c.fr))}
function currentCards(){const t=current();const cards=buildCards(t);const ord=state.cardOrder[t.id];if(Array.isArray(ord)&&ord.length===cards.length)return ord.map(i=>cards[i]).filter(Boolean);return cards}
function currentCard(){const cards=currentCards();if(!cards.length)return{fr:"",zh:""};state.cardIndex=Math.min(state.cardIndex,cards.length-1);return cards[state.cardIndex]}
function targetText(){const t=current();if(state.mode==="cards")return currentCard().fr;return state.mode==="full"?t.paragraphs.map(p=>p.answer).join("\n\n"):t.paragraphs[state.segment].answer}
function promptText(){const t=current();if(state.mode==="cards"){const c=currentCard();if(state.hint==="none")return"无提示。请直接默写这个主题句块。";if(state.hint==="first")return tokens(c.fr).slice(0,3).join(" ")+"…";return c.zh}if(state.hint==="none")return"无提示。请直接默写。";if(state.hint==="first"){const arr=state.mode==="full"?t.paragraphs:[t.paragraphs[state.segment]];return arr.map((p,i)=>(state.mode==="full"?i+1+". ":"")+tokens(p.answer).slice(0,8).join(" ")+"…").join("\n\n")}const tr=window.TCF_TRANSLATIONS&&window.TCF_TRANSLATIONS[t.id];if(tr){return state.mode==="full"?tr.map((x,i)=>(i+1)+". "+x).join("\n\n"):tr[state.segment]}return state.mode==="full"?t.paragraphs.map((p,i)=>i+1+". "+p.hintZh).join("\n"):t.paragraphs[state.segment].hintZh}
function populateSections(){const secs=[...new Set(baseTopics.map(t=>t.section).filter(Boolean))];el.sectionFilter.innerHTML='<option value="">全部主题（'+baseTopics.length+'）</option>'+secs.map(s=>'<option value="'+esc(s)+'">'+esc(s)+"</option>").join("")}
function filteredTopics(){const q=el.searchInput.value.trim().toLowerCase(),sec=el.sectionFilter.value;return topics.filter(t=>(scope==="exams"?!!exams.metadata[t.id]:!t.examOnly)&&(!$("examMonth").value||scope!=="exams"||exams.metadata[t.id].months.includes($("examMonth").value))&&(!sec||t.section===sec)&&(!state.reviewOnly||state.statuses[t.id]==="review")&&(!q||(`${t.zhTitle} ${t.frTitle} ${t.section} ${t.subsection}`.toLowerCase().includes(q))))}
function renderTopicList(){const list=filteredTopics();el.topicList.innerHTML=list.length?list.map(t=>{const st=state.statuses[t.id]||"new";return'<button type="button" class="topic-item '+(t.id===state.topicId?"active":"")+'" data-id="'+t.id+'"><span class="dot '+st+'"></span><span class="num">'+String(t.id).padStart(2,"0")+"</span>"+esc(t.zhTitle||t.frTitle)+(scope==="exams"?'<small class="exam-list-badge">'+exams.metadata[t.id].months.map(m=>m.replace("-",".")).join(" / ")+" 真题 · "+(t.examOnly?"真题迁移改写版":"原库直接匹配")+"</small>":"")+'<span class="fr">'+esc(t.frTitle)+"</span></button>"}).join(""):'<div style="padding:20px;color:var(--muted)">没有匹配的题目。</div>';el.topicList.querySelectorAll("[data-id]").forEach(b=>b.addEventListener("click",()=>{state.topicId=Number(b.dataset.id);state.segment=0;state.cardIndex=0;persist();resetAnswer();render()}))}
function renderStats(){const v=Object.values(state.statuses);el.statDone.textContent=v.filter(x=>x==="mastered").length;el.statReview.textContent=v.filter(x=>x==="review").length;el.statAttempts.textContent=state.attempts}
function renderTabs(){const labels=current().paragraphs.map((p,i)=>(i+1)+" · "+p.role);el.paragraphTabs.innerHTML=labels.map((x,i)=>'<button type="button" role="tab" data-seg="'+i+'" class="'+(state.segment===i?"active":"")+'" '+(state.mode==="full"?"disabled":"")+">"+x+"</button>").join("");el.paragraphTabs.style.opacity=state.mode==="full"?.45:1;el.paragraphTabs.querySelectorAll("[data-seg]").forEach(b=>b.addEventListener("click",()=>{state.segment=Number(b.dataset.seg);persist();resetAnswer();renderPractice()}))}
function renderPractice(){const t=current();el.topicCounter.textContent="第 "+(filteredTopics().findIndex(x=>x.id===t.id)+1)+" / "+filteredTopics().length+" 题 · "+t.section+(t.subsection?" · "+t.subsection:"");el.topicZh.textContent=t.zhTitle||"";el.topicFr.textContent=t.frTitle;renderTabs();const cards=currentCards();const isCards=state.mode==="cards";el.paragraphTabs.classList.toggle("hidden",isCards);el.cardBar.classList.toggle("hidden",!isCards);if(isCards){el.cardCounter.textContent="主题卡 "+(cards.length?state.cardIndex+1:0)+" / "+cards.length+" · "+(currentCard().role||"")}el.promptText.textContent=promptText();document.querySelectorAll(".mode-btn").forEach(b=>b.classList.toggle("active",b.dataset.mode===state.mode));document.querySelectorAll(".hint-btn").forEach(b=>b.classList.toggle("active",b.dataset.hint===state.hint));document.querySelectorAll(".status-btn").forEach(b=>b.classList.toggle("active",b.dataset.status===(state.statuses[t.id]||"new")));el.nextSegmentBtn.style.visibility=state.mode==="full"?"hidden":"visible";el.nextSegmentBtn.textContent=isCards?(state.cardIndex<cards.length-1?"下一张卡 →":"本题卡牌完成 ✓"):(state.segment<3?"下一段 →":"本题完成 ✓");window.TCF_EE3_UI.render(t,state.mode,state.segment,scope);el.answerBox.placeholder=isCards?"根据中文翻译默写对应的法语主题词组 / 句块……":"在这里默写。建议先完整写完，再检查答案……"}
function resetAnswer(){window.TCF_EE3_UI.hideReference();el.answerBox.value="";el.resultPanel.classList.add("hidden");updateWordCount()}function updateWordCount(){el.wordCount.textContent=((el.answerBox.value.match(/[\p{L}\p{M}]+(?:['’][\p{L}\p{M}]+)*/gu)||[]).length)+" mots"}function render(){renderTopicList();renderStats();renderPractice()}
function check(){const user=el.answerBox.value.trim();if(!user){el.answerBox.focus();return}const d=lcsDiff(user,targetText());el.scoreValue.textContent=d.score+"%";el.scoreMessage.textContent=d.score>=97?"非常接近原稿。":d.score>=90?"基本掌握，重点看标出的差异。":d.score>=75?"主体记住了，再复习一下措辞。":"建议先看原稿，再重新默写一遍。";el.userDiff.innerHTML=renderTokens(d.user);el.answerDiff.innerHTML=renderTokens(d.answer);el.resultPanel.classList.remove("hidden");state.attempts++;persist();renderStats()}
window.TCF_GRAMMAR_TARGET=()=>({fr:targetText()});
function reveal(){window.TCF_EE3_UI.toggleReference()}
function moveTopic(delta){const list=filteredTopics();if(!list.length)return;const idx=list.findIndex(t=>t.id===state.topicId),n=(idx+delta+list.length)%list.length;state.topicId=list[n].id;state.segment=0;state.cardIndex=0;persist();resetAnswer();render()}
populateSections();el.searchInput.addEventListener("input",refreshScope);el.sectionFilter.addEventListener("change",refreshScope);el.randomBtn.addEventListener("click",()=>{const list=filteredTopics();if(!list.length)return;const t=list[Math.floor(Math.random()*list.length)];state.topicId=t.id;state.segment=0;state.cardIndex=0;persist();resetAnswer();render()});el.reviewOnlyBtn.addEventListener("click",()=>{state.reviewOnly=!state.reviewOnly;el.reviewOnlyBtn.setAttribute("aria-pressed",String(state.reviewOnly));el.reviewOnlyBtn.classList.toggle("secondary",state.reviewOnly);refreshScope()});document.querySelectorAll(".mode-btn").forEach(b=>b.addEventListener("click",()=>{state.mode=b.dataset.mode;state.cardIndex=0;persist();resetAnswer();renderPractice()}));document.querySelectorAll(".hint-btn").forEach(b=>b.addEventListener("click",()=>{state.hint=b.dataset.hint;persist();renderPractice()}));document.querySelectorAll(".status-btn").forEach(b=>b.addEventListener("click",()=>{state.statuses[state.topicId]=b.dataset.status;persist();refreshScope()}));el.answerBox.addEventListener("input",updateWordCount);el.checkBtn.addEventListener("click",check);el.revealBtn.addEventListener("click",reveal);el.clearBtn.addEventListener("click",resetAnswer);el.prevBtn.addEventListener("click",()=>moveTopic(-1));el.nextBtn.addEventListener("click",()=>moveTopic(1));el.nextSegmentBtn.addEventListener("click",()=>{if(state.mode==="cards"){const cards=currentCards();if(state.cardIndex<cards.length-1){state.cardIndex++;persist();resetAnswer();renderPractice()}else{state.statuses[state.topicId]=state.statuses[state.topicId]||"review";persist();moveTopic(1)}}else if(state.segment<3){state.segment++;persist();resetAnswer();renderPractice()}else{state.statuses[state.topicId]=state.statuses[state.topicId]||"review";persist();moveTopic(1)}});el.shuffleCardsBtn.addEventListener("click",()=>{const cards=buildCards(current());const order=cards.map((_,i)=>i);for(let i=order.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[order[i],order[j]]=[order[j],order[i]]}state.cardOrder[state.topicId]=order;state.cardIndex=0;persist();resetAnswer();renderPractice()});
function refreshScope(){$("sectionFilter").options[0].textContent=scope==="exams"?"全部真题主题":"全部主题（62）";const list=filteredTopics();$("practicePanel").classList.toggle("hidden",!list.length);if(list.length&&!list.some(t=>t.id===state.topicId)){state.topicId=list[0].id;state.segment=0;state.cardIndex=0;persist();resetAnswer();}$("examMonth").disabled=scope!=="exams";$("baseScopeBtn").setAttribute("aria-pressed",String(scope==="base"));$("examScopeBtn").setAttribute("aria-pressed",String(scope==="exams"));$("scopeCount").textContent=(scope==="exams"?"45 条月度记录 · 36 道独立任务 · ":"原语料 · ")+list.length+" 篇当前结果";renderTopicList();renderStats();if(list.length)renderPractice();}
function changeScope(value){scope=value;localStorage.setItem(KEY+"-exam-scope",value);$("sectionFilter").value="";$("searchInput").value="";$("examMonth").value="";resetAnswer();refreshScope();}
$("baseScopeBtn").addEventListener("click",()=>changeScope("base"));$("examScopeBtn").addEventListener("click",()=>changeScope("exams"));$("examMonth").addEventListener("change",refreshScope);refreshScope()})();
