/* Local grammar notes tied to the current reference, never to the learner's draft. */
(() => {
'use strict';
const rules=[];
const add=(pattern,title,explanation,example,pitfall='')=>rules.push({pattern,title,explanation,example,pitfall});
add(/\b(?:rendre|rend|rends|rendent|rendons|rendez|rendra\w*|rendait|rendaient|rendu\w*)\b[^.!?;\n]{0,90}?\b(?:plus |moins |aussi )?(?:interactif\w*|accessible\w*|efficace\w*|facile\w*|difficile\w*|heureu\w*|autonome\w*|responsable\w*|agréable\w*|simple\w*|attractif\w*|compliqué\w*|motivé\w*|pratique\w*|visible\w*|utile\w*)/giu,'rendre + 宾语 + 形容词：使……变得……','宾语是被改变的人或事物；后面的形容词说明它变成怎样，语法功能是宾语表语（attribut du complément direct）。形容词与宾语配合，而不是与主语配合。','rendre l’apprentissage plus interactif：使学习更有互动性。l’apprentissage 是阳性单数，故用 interactif；rendre les activités plus interactives 中用阴性复数 interactives。','不要把形容词前补成 de / à；但 rendre service à 是另一个固定搭配。');
add(/\b(?:plus|moins|aussi)\s+[\p{L}-]+/giu,'比较结构：plus / moins / aussi + 形容词或副词','如果后接形容词：plus 表示“更……”，moins 表示“不那么……”，aussi 表示“同样……”。如果后接副词则比较动作的方式。比较对象通常用 que 引出；省略比较对象时仍可表达程度比较。','plus interactif：更有互动性；plus facilement：更容易地；aussi utile que…：和……一样有用。','此处只在后一个词确为形容词／副词时适用；plus de + 名词比较数量，ne…plus 表示“不再”，le plus… 常是最高级。');
add(/\b(?:plus|moins|autant)\s+d[e’'][^.!?;,\n]{0,45}/giu,'数量比较：plus / moins / autant de + 名词','plus de 表示“更多的”，moins de 表示“更少的”，autant de 表示“同样多的”。de 在元音或哑音 h 前省音为 d’。','plus d’informations：更多信息；moins de temps：更少时间；autant de possibilités que…','数量结构是 de，不写成 plus des informations；plus des… 也可能是加法或其他结构，要按语境区分。');
add(/\b(?:le|la|les)\s+(?:plus|moins)\s+[\p{L}-]+/giu,'最高级：le / la / les plus（或 moins）','定冠词 + plus / moins 通常表达“最……／最不……”。比较范围可用 de 引出。冠词与所指名词的性数一致。','la solution la plus efficace：最有效的方案；les outils les moins chers：最便宜的工具。');
add(/\b(?:meilleur\w*|mieux|pire\w*)\b/giu,'不规则比较词','meilleur 是 bon 的比较级，修饰名词并配合性数；mieux 是 bien 的比较级，通常修饰动词；pire 可表示“更糟”。','une meilleure solution：更好的方案；mieux comprendre：理解得更好。','不要说 plus bon 或 plus bien 来表达普通比较。');
add(/\b(?:mon|ton|son|ma|ta|sa|mes|tes|ses|notre|votre|leur|nos|vos|leurs)\s+[\p{L}-]+/giu,'物主限定词：看被修饰的名词，而非拥有者的性别','mon / ton / son 用于阳性单数；ma / ta / sa 用于阴性单数；mes / tes / ses 用于复数。阴性单数词前，如果紧接元音或哑音 h，用 mon / ton / son 来避免元音相撞。名词本身仍是阴性。notre / votre / leur 不区分阴阳性；复数用 nos / vos / leurs。','son ami：ami 是阳性，正常用 son；son amie：amie 是阴性，但元音前用 son；sa meilleure amie：紧接的是辅音开头的 meilleure，故用 sa。','不能因为名字以 a / e 开头就一律换 son。h 嘘音也不触发这条规则，例如 sa honte。son 不表示拥有者一定是男性。');
add(/\b(?:au|aux|du|des)\b/giu,'冠词缩合与 du / des 的区别','à + le → au，à + les → aux；de + le → du，de + les → des。à la / à l’ / de la / de l’ 不缩合。du 也可能是部分冠词，des 也可能是复数不定冠词，要看是否有一个要求 de 的前词。','participer au festival = participer à + le festival；profiter du séjour = profiter de + le séjour；acheter du pain 中 du 表示不确定数量。','遇到 des 不能一律拆成 de + les。');
add(/\b(?:l’|l'|d’|d'|qu’|qu'|j’|j'|n’|n'|s’|s'|c’|c')[\p{L}]+/giu,'省音：元音或哑音 h 前的撇号','le / la → l’，de → d’，que → qu’，je → j’，ne → n’，se → s’，ce → c’。省音后的形式不额外加元音。l’ 不直接说明名词阴阳性。','l’apprentissage、d’informations、qu’il、j’aime、s’adapter。','嘘音 h 通常阻止省音；si 一般只在 il / ils 前省音为 s’il / s’ils。');
add(/\b(?:beaucoup|peu|assez|trop|tant|tellement)\s+d[e’'][^.!?;,\n]{0,40}/giu,'数量词 + de + 名词','beaucoup de：很多；peu de：很少；assez de：足够；trop de：太多。一般不再加不定冠词或部分冠词；元音前 de → d’。','beaucoup d’informations、assez de temps、trop de difficultés。','beaucoup des étudiants 可以表示“那些学生中的很多人”，与一般泛指 beaucoup d’étudiants 不同。');
add(/\b(?:ne|n’|n')[^.!?;\n]{0,65}?\b(?:pas|plus|jamais|rien|personne|aucun\w*)\b/giu,'否定：ne…pas / plus / jamais / rien / personne','变位句中，ne 通常在变位动词前，pas / plus / jamais 在它后面；复合时态通常夹住助动词。plus = 不再，jamais = 从不，rien = 什么也不，personne = 没有人。','je ne peux pas venir；je n’ai jamais essayé；je ne vois personne。','rien / personne 的位置随功能变化；personne 作主语时：Personne ne vient。不是所有 ne 都表示否定（如某些虚拟式从句的赘词 ne）。');
add(/\bne\s+pas\s+[\p{L}’'-]+/giu,'不定式的否定：ne pas + 动词原形','当被否定的是动词原形，ne pas 通常一起放在这个原形前。复合不定式中放在 avoir / être 前。','Je préfère ne pas sortir；ne pas avoir compris。','变位句则是 je ne sors pas，不能套用 ne pas sors。');
add(/\b(?:pour que|afin que|bien que|quoique|à condition que|avant que|sans que|à moins que|jusqu’à ce que|jusqu'a ce que)\b/giu,'连接词后常用虚拟式','pour que / afin que 引出目的；bien que / quoique 引出让步；à condition que 引出条件；avant que 引出先行动作。这些结构后使用虚拟式。两边主语相同时，目的常用 pour / afin de + 不定式。','pour qu’ils puissent participer；bien qu’il soit difficile；afin de progresser。','不要把 bien que 与 même si 混用：même si 通常接直陈式。avant que 等后可有赘词 ne，并不表示“不”。');
add(/\b(?:il faut que|il faudrait que|il est nécessaire que|il serait souhaitable que|je souhaite que|je voudrais que)\b/giu,'要求／愿望：que + 虚拟式','il faut que 表示要求；il faudrait que / il serait souhaitable que 更委婉。主句中的条件式不改变这些结构后从句需要虚拟式的原则。','Il faudrait que nous puissions participer；Je souhaite que tout se passe bien。','同一主体可使用 souhaiter / vouloir + 不定式：Je souhaite participer。');
add(/\b(?:même si|parce que|puisque|alors que|tandis que|étant donné que|pendant que)\b/giu,'从句连接：原因、让步与对比','parce que / puisque 引出原因；même si 引出让步条件；alors que / tandis que 可表示对比或同时发生。它们通常使用直陈式，而非仅因出现 que 就改成虚拟式。','Même si cela coûte cher, c’est utile；parce que cela facilite la vie。');
add(/\bsi\b[^.!?;\n]{1,90}/giu,'si 条件句：按假设程度配合时态','现实可能：si + 现在时，主句可用现在时／将来时／命令式；与现在事实相反或较不确定：si + 未完成过去时，主句用条件式现在时；过去未实现：si + 愈过去时，主句用条件式过去时。','Si j’ai le temps, je viendrai；Si j’avais le temps, je viendrais。','条件连词 si 后不用将来时或条件式。询问“是否”的 si（je voudrais savoir si…）是另一种用法，不能机械套用条件句规则。');
add(/\b(?:est-ce que|est-ce qu’|est-ce qu')/giu,'est-ce que：构成一般疑问句','后面保留主语 + 动词的陈述语序；元音前 que → qu’。也可放在疑问词后。','Est-ce que vous proposez des cours ? Quand est-ce que cela commence ?','不要再叠加倒装成 Est-ce que proposez-vous…');
add(/\b(?:pourriez-vous|pouvez-vous|avez-vous|êtes-vous|souhaitez-vous|serait-il|est-il|faut-il|y a-t-il)\b/giu,'疑问倒装与礼貌问法','变位动词与主语代词之间用连字符。第三人称单数在需要时加 -t-。pourriez-vous 是 pouvoir 的条件式现在时，用于委婉请求。','Pourriez-vous m’indiquer les horaires ? Y a-t-il des places ?','-t- 是读音连接形式，不是单词；不能写成 y a t il。');
add(/\b(?:quel|quelle|quels|quelles)\s+[\p{L}-]+/giu,'quel：疑问限定词的性数配合','quel / quelle / quels / quelles 与所问名词的性数配合：阳单／阴单／阳复／阴复。','Quel tarif ? Quelle durée ? Quels documents ? Quelles activités ?');
add(/\b(?:ce qui|ce que|ce qu’|ce qu'|ce dont)\b/giu,'ce qui / ce que / ce dont：指“……的事／东西”','ce qui 在从句中作主语；ce que 作直接宾语；ce dont 对应需要 de 的补语。先看从句动词需要什么，再选代词。','ce qui me plaît：令我喜欢的事；ce que je préfère：我偏爱的东西；ce dont j’ai besoin：我需要的东西。');
add(/\bdont\b/giu,'dont：承接 de + 名词的关系代词','dont 常替代 parler de、avoir besoin de、profiter de 等结构中的 de 补语，也可表达所属关系。它不同时再保留原来的 de 或重复代词。','une activité dont tout le monde peut profiter：人人都能受益的活动，源自 profiter de cette activité。','不是所有“关于／其中”都用 dont；原结构若要求 à、avec 等介词，应考虑 auquel、avec lequel 等。');
add(/\b(?:qui|que|qu’|qu')\b/giu,'qui / que：先区分关系代词与连接词','有名词先行词时，qui 常在关系从句中作主语，que 作直接宾语。que 也可只是连接词（je pense que…），并不代替宾语。','un outil qui facilite l’apprentissage；un outil que j’utilise。','不能仅凭 qui / que 后面紧接哪个词就确定全部句子结构；复合时态中，前置直接宾语可能影响过去分词配合。');
add(/\b(?:en|tout en)\s+[\p{L}-]*ant\b/giu,'副动词：en + 现在分词','可表达方式、同时发生、原因等；逻辑主语通常与主句主语相同。tout en 可强调同时进行或让步。副动词不作阴阳性或复数配合。','On apprend en pratiquant；tout en restant prudent：同时保持谨慎。','en utilisant 后直接接 utiliser 的宾语；不是 en + 普通动词原形。');
add(/\btout en\b/giu,'tout en + 现在分词：同时……／尽管……','tout en 后接现在分词，例如 restant、utilisant、respectant。列表里的 participe présent 是语法占位提示，不是应写出的法语词。','progresser tout en respectant son rythme：在尊重自身节奏的同时进步。');
add(/\b(?:pour|afin de|sans|avant de|au lieu de|plutôt que de)\s+[\p{L}’'-]+/giu,'介词与动词原形','pour / afin de + 不定式表达目的；sans + 不定式表示“不做……”；avant de + 不定式表示“在做……前”；au lieu de / plutôt que de 表示替代。','pour apprendre；sans dépenser；avant de partir；plutôt que de rester。','只有后接动词时才是这里的不定式结构；pour + 名词也是正确结构。');
add(/\b(?:permettre|permet|permettent|permettrait|permettra|permettez)\b/giu,'permettre à quelqu’un de + 动词原形','表示“允许／使某人能够做某事”。à 引出受益者，de 引出动作；受益者可用间接宾语代词 lui / leur / nous 等替代。','Cela permet aux élèves de participer；Cela leur permet de participer。','不能把动作前的 de 改成 à。permettre quelque chose 也存在，但结构不同。');
add(/\b(?:donner|donne|donnent|donnerait)\s+envie\b/giu,'donner envie à quelqu’un de + 动词原形','表示“让某人想做某事”：envie 是愿望，à quelqu’un 表示产生愿望的人，de 引出想做的动作。某人可在上下文明确时省略。','Cela donne envie aux élèves d’apprendre；Cela me donne envie de participer。','如果要明确说“让某人”，应保留 à + 人或间接宾语代词；不要写成 donner envie de quelqu’un。');
add(/\b(?:participer|participe|participent|participerai|participerez)\s+à(?=\s|$|[.,;!?])/giu,'participer à + 活动／事项','参加活动用 à 引出活动，à 与 le / les 缩合为 au / aux。','participer à une activité；participer au festival；participer aux ateliers。','不要写 participer de 来表达“参加”。');
add(/\b(?:profiter|profite|profitent|profitez)\s+d[e’']/giu,'profiter de + 名词','表示“享受／利用／受益于”。de 与冠词缩合，或在元音前省音。','profiter du séjour；profiter des activités；profiter d’une occasion。','profiter à quelqu’un 是“对某人有利”，主语与意义不同。');
add(/\bfaire face à(?=\s|$|[.,;!?])/giu,'faire face à：面对／应对','à 引出面对的困难或情况，属于固定介词搭配。','faire face aux difficultés = à + les difficultés。');
add(/\b(?:avoir|a|ont|avons|avez|ai)\s+(?:besoin|envie|peur)\s+d[e’']/giu,'avoir besoin / envie / peur de','besoin de：需要；envie de：想要；peur de：害怕。后面可以接名词，也可接动词原形。','avoir besoin de soutien；avoir envie de voyager；avoir peur de se tromper。');
add(/\b(?:aider|aide|aident|aidez)\b/giu,'aider quelqu’un à + 动词原形','aider 后的人是直接宾语，动作由 à 引出；人称代词用 le / la / les 等。','aider les enfants à apprendre；les aider à progresser。','不要把 aider les enfants 改成 aider aux enfants。');
add(/\b(?:empêcher|empêche|empêchent)\b/giu,'empêcher quelqu’un de + 动词原形','阻止某人做某事：人是直接宾语，动作前用 de。','empêcher les élèves de participer；les empêcher de sortir。');
add(/\b(?:encourager|encourage|encouragent|inciter|incite|incitent)\b/giu,'encourager / inciter quelqu’un à + 动词原形','鼓励／促使某人做某事：动词直接接人，动作前用 à。','encourager les élèves à participer。');
add(/\b(?:essayer|essaie|essaient|décider|décide|décident|éviter|évite|évitent)\s+d[e’']/giu,'essayer / décider / éviter de + 动词原形','essayer de：尝试；décider de：决定；éviter de：避免。原形动作前保留 de，元音前为 d’。','essayer de comprendre；décider de partir；éviter d’attendre。');
add(/\b(?:réussir|réussit|réussissent|arriver|arrive|arrivent|chercher|cherche|cherchent)\s+à(?=\s|$|[.,;!?])/giu,'réussir / arriver / chercher à + 动词原形','réussir à、arriver à 表示“成功做到”；chercher à 表示“设法／试图”。动作前用 à。','réussir à s’intégrer；chercher à progresser。','arriver à + 地点是到达地点，要与“设法做到”区别。');
add(/\b(?:pouvoir|peux|peut|pouvons|pouvez|peuvent|pourrait|pourraient|devoir|dois|doit|devons|devez|doivent|devrait|devraient|vouloir|veux|veut|voulons|voulez|veulent|voudrais|voudrait|voudriez)\s+(?:(?:souvent|toujours|aussi|également|encore|bien|parfois)\s+)?[\p{L}’'-]+/giu,'pouvoir / devoir / vouloir + 动词原形','pouvoir 表示能力／可能，devoir 表示义务或推测，vouloir 表示愿望。后接动作时直接接原形，不额外加 de 或 à。','peut faciliter；doit respecter；voudrait participer。');
add(/\b(?:il y a|il y avait|il y aura|il y aurait|y a-t-il)\b/giu,'il y a：表示“有／存在”','il 是非人称主语，y 属于固定结构；后面引出存在的人或事物。avoir 的时态随时间变化。','Il y a plusieurs possibilités；Y a-t-il des cours ?','“有”不是 il est；过去时间间隔的 il y a trois ans 是“三年前”。');
add(/\b(?:il faut|il faudrait|il vaut mieux|il est important de|il est nécessaire de|il est possible de)\b/giu,'非人称建议／评价 + 动词原形','il 不指具体男性；il faut 表示“必须”，il faudrait 更委婉，il vaut mieux 表示“最好”。important / nécessaire / possible de 用 de 引出动作。','Il vaut mieux comparer；Il est important de respecter les règles。');
add(/\b(?:grâce à|à cause de|en raison de|faute de|malgré|contrairement à|par rapport à|en dehors de)\b/giu,'介词短语：后接名词或代词','grâce à：多为正面原因；à cause de：多为负面原因；en raison de：较中性；faute de：由于缺少；malgré：尽管；par rapport à：相对于。保留各结构自己的介词。','grâce au soutien；à cause du manque de temps；malgré les difficultés。','malgré 不能直接像 bien que 一样引出普通变位从句。');
add(/\b(?:de plus|en outre|par ailleurs|cependant|pourtant|néanmoins|en revanche|à l’inverse|en effet|ainsi|par conséquent|pour conclure|tout d’abord|ensuite|enfin)\b/giu,'论证连接词：把观点之间的关系说清楚','de plus / en outre：递进；cependant / pourtant / néanmoins：转折让步；en revanche / à l’inverse：对比；en effet：解释或依据；par conséquent：结果；tout d’abord / ensuite / enfin：顺序。','En effet, cela facilite la communication；Par conséquent, les échanges sont plus simples。','en effet 用来支持前一句，不能一律当作“因此”。');
add(/\b(?:non seulement|pas seulement|mais aussi|à la fois|soit\b[^.!?\n]{1,35}\bsoit)\b/giu,'并列与递进句型','non seulement…mais aussi…：不仅……而且……；à la fois…et…：既……又……；soit…soit…：要么……要么……。两端尽量使用平行语法结构。','non seulement utile, mais aussi agréable；à la fois simple et efficace。');
add(/\b(?:de plus en plus|de moins en moins)\b/giu,'渐进变化：越来越……','de plus en plus + 形容词／副词：越来越……；de plus en plus de + 名词：越来越多的……。de moins en moins 表示越来越少／越来越不。','de plus en plus important；de plus en plus de personnes。');
add(/\b(?:depuis|pendant|durant|pour|dans|il y a)\s+(?:un|une|deux|trois|quatre|quelques|plusieurs|\d+)\s+(?:jour\w*|semaine\w*|mois|an\w*|heure\w*|minute\w*)/giu,'时间介词：起点、时长与未来','depuis：从过去延续到参考时刻；pendant / durant：持续时长；il y a + 时长：多久以前；dans + 时长：多久之后；pour + 时长：计划／预计持续多久。','depuis deux ans；pendant trois jours；dans une semaine。','延续到现在常用 depuis + 现在时，不直接按中文“已经……”机械换成过去时。');
add(/\b(?:s’adapter à|se familiariser avec|s’intégrer|s’intéresser à|se concentrer sur|s’occuper de|se rendre compte de|se sentir)\b/giu,'代词式动词：保留反身代词与固定介词','se 随主语变化：me / te / se / nous / vous / se。介词由动词搭配决定：s’adapter à、se familiariser avec、s’occuper de。复合时态通常以 être 为助动词，过去分词是否配合还需看 se 的功能。','je m’adapte à la vie locale；nous nous familiarisons avec le système。','不是所有代词式动词的过去分词都简单跟主语配合：elles se sont parlé 中不加 es。');
add(/\b(?:je serais ravi|je serais ravie|je serais heureux|je serais heureuse|je vous serais reconnaissant|je vous serais reconnaissante)\b/giu,'条件式礼貌句与形容词配合','serais 是 être 的条件式现在时第一人称单数。ravi / heureux / reconnaissant 描述说话者，女性用 ravie / heureuse / reconnaissante。ravi(e) de + 原形表示“很高兴做……”。','Je serais ravie de participer；Je vous serais reconnaissante de m’aider。','礼貌程度来自 serais；写成 serai 是将来时，含义与语气不同。原题答案若指定形式，核对仍按原题规则。');
add(/\b(?:ce|cet|cette|ces)\s+[\p{L}-]+/giu,'指示限定词：ce / cet / cette / ces','ce：阳性单数辅音前；cet：阳性单数元音或哑音 h 前；cette：阴性单数；ces：复数。cet 不表示阴性。','cet outil；cette activité；ces informations。');
add(/\b(?:quelque chose|qqch|qch|quelqu’un|quelqu'un|qqn|qn|infinitif|participe présent|subjonctif)\b/giu,'不定代词与句型列表的占位提示','quelque chose 表示“某事／某物”，quelqu’un 表示“某人”，在完整句子里可以是实际的不定代词。在句型列表里，它们也常充当占位词，可用具体的人或事替换；qqch / qch、qqn / qn 是列表缩写。infinitif 等标签说明后接什么语法形式。','participer à quelque chose → participer à un atelier；tout en + participe présent → tout en travaillant。','省略占位词不等于可改核心介词或变位。');
add(/\b(?:avoir|ai|a|ont|avez|avons)\s+du mal à(?=\s|$)/giu,'avoir du mal à + 动词原形：做……有困难','du mal 是固定结构的一部分；à 后面接难以完成的动作。mal 这里是名词，不是形容词“坏的”。','avoir du mal à comprendre；j’ai du mal à m’adapter。');
add(/\b(?:venir|viens|vient|venons|venez|viennent)\s+d[e’'][\p{L}’'-]+/giu,'venir de + 动词原形：最近过去时','表示“刚刚做完……”。venir 根据主语变位，de 后接动词原形；venir de + 地点则表示“来自”，不是最近过去时。','Elle vient d’arriver：她刚到。','动作前 de 不省略；复合过去时 elle est arrivée 与此结构不同。');
add(/\bprendre la parole\b/giu,'prendre la parole：发言','prendre + la parole 是固定搭配；parole 是阴性名词。这里表示开始发言，而非逐字理解为“拿话语”。','Je voudrais prendre la parole：我想发言。');
add(/\b(?:être|est|sont|étaient|sera|seront)\s+(?:souvent\s+)?(?:réglé\w*|accepté\w*|utilisé\w*|organisé\w*|proposé\w*|encouragé\w*|considéré\w*|offert\w*|interdit\w*|autorisé\w*)/giu,'être + 过去分词：被动或结果状态','此结构可表达主语受到某个动作，也可表达动作后的状态。过去分词与主语性数配合；动作执行者可用 par 引出。具体是被动过程还是状态，要结合上下文。','les difficultés doivent être réglées：困难必须得到解决；réglées 与阴性复数 difficultés 配合。');
add(/\b(?:le|la|les|un|une|des)\s+[\p{L}-]+/giu,'名词前的冠词：特指、泛指与性数','le / la / les 是定冠词；un / une / des 可作不定冠词。冠词与名词的性数有关，选择定冠词还是不定冠词也取决于是否特指。下方名词标注可辅助确认性别。','un compte：一个账户；le compte：那个／已知的账户；les documents：那些文件。','le / la / les 在动词前也可能是宾语代词；des 还可能是 de + les 缩合，不能只看单词就断言功能。');
const lexical={apprentissage:['学习','阳性名词；apprendre 的名词形式。'],interactif:['互动的','形容词；阴性 interactive，复数 interactifs / interactives。'],interactifs:['互动的','interactif 的阳性复数。'],interactive:['互动的','interactif 的阴性单数。'],interactives:['互动的','interactif 的阴性复数。'],rendre:['使……变得；归还','原形动词。根据后续结构区分 rendre + 宾语 + 形容词、rendre quelque chose、rendre service à。'],accessible:['可接近的；可获得的','形容词；性别形式相同，复数 accessibles。'],efficace:['有效的','形容词；阴阳性同形，复数 efficaces。'],soutien:['支持','阳性名词；常见 apporter / offrir un soutien。'],démarche:['手续；做法','阴性名词；行政手续常用复数 démarches。'],démarches:['手续；举措','阴性复数。'],quotidien:['日常；日常生活','形容词可用 quotidienne；le quotidien 是阳性名词“日常生活”。'],compte:['账户；计算','阳性名词；ouvrir un compte bancaire。'],bancaire:['银行的','形容词；compte bancaire = 银行账户。'],documents:['文件','document 的阳性复数。'],transport:['运输；交通工具','阳性名词；les transports en commun = 公共交通。'],langue:['语言','阴性名词。'],stress:['压力','阳性名词，复数形式不另加 s。'],difficultés:['困难','difficulté 的阴性复数。'],occasion:['机会；场合','阴性名词，une occasion de + 原形。'],avantages:['优点；益处','avantage 的阳性复数。'],inconvénients:['缺点；不利之处','inconvénient 的阳性复数。'],emploi:['工作；就业','阳性名词；trouver un emploi。'],formation:['培训；教育','阴性名词。'],budget:['预算','阳性名词。'],horaire:['时间安排','阳性名词；复数 horaires 常指营业／课程时间。'],horaires:['时间表；营业时间','horaire 的阳性复数。'],tarif:['价目；收费','阳性名词。'],tarifs:['价格；收费标准','tarif 的阳性复数。'],activité:['活动','阴性名词。'],activités:['活动','activité 的阴性复数。'],atelier:['工作坊','阳性名词。'],ateliers:['工作坊','atelier 的阳性复数。'],autonomie:['自主性','阴性名词。'],responsabilité:['责任','阴性名词。'],épanouissement:['成长；个人发展','阳性名词。'],repères:['参照点；熟悉感','repère 的阳性复数；trouver ses repères = 找到自己的节奏／适应环境。'],insertion:['融入；进入','阴性名词；insertion professionnelle = 职业融入。'],accueil:['接待；欢迎','阳性名词；société d’accueil = 接纳移民的社会。'],séjour:['停留；旅居','阳性名词。'],logement:['住房','阳性名词。'],hébergement:['住宿','阳性名词。'],environnement:['环境','阳性名词。'],expérience:['经验；经历','阴性名词。'],conséquences:['后果；影响','conséquence 的阴性复数。'],renforcer:['加强','及物动词，直接接宾语。'],faciliter:['便利；促进','及物动词，直接接宾语。'],freiner:['抑制；减缓','及物动词，直接接宾语。'],favoriser:['促进；有利于','及物动词，直接接宾语。'],améliorer:['改善；提高','及物动词，直接接宾语。'],développer:['发展；培养','及物动词，直接接宾语。'],bénéficier:['受益','常见 bénéficier de + 事物；事物 bénéficient à + 人 = 对人有利。'],proposer:['提出；提供','proposer quelque chose à quelqu’un / proposer de + 原形。'],participer:['参加','参加活动时用 participer à。'],profiter:['享受；利用','profiter de + 事物；profiter à + 人 = 对人有利。'],ami:['男性朋友','阳性单数，son ami 是常规性数配合。'],amie:['女性朋友','阴性单数，直接在元音开头 amie 前使用 son：son amie。']};
const norm=s=>String(s||'').toLowerCase().replace(/[’‘]/g,"'").replace(/\s+/g,' ').trim();
const unicodeBoundary='(?:(?<![\\p{L}\\p{M}])(?=[\\p{L}\\p{M}])|(?<=[\\p{L}\\p{M}])(?![\\p{L}\\p{M}]))';
for(const rule of rules)rule.pattern=new RegExp(rule.pattern.source.replace(/\\b/g,unicodeBoundary),rule.pattern.flags);
function analyze(text){let output=[];for(const rule of rules){let matches=Array.from(text.matchAll(rule.pattern));if(rule.title.startsWith('比较结构'))matches=matches.filter(m=>! /^(?:plus|moins|aussi)\s+(?:de|des|du|en|que|qu|d)$/i.test(m[0])&&!/\b(?:ne|n['’])[^.!?;]{0,40}$/i.test(text.slice(Math.max(0,m.index-45),m.index)));if(rule.title.startsWith('物主限定词'))matches=matches.filter(m=>!/^leur\s+(?:permet|permettent|donne|donnent|offre|offrent|propose|proposent|parle|parlent|faut|semble|semblent|plaît|plaisent)$/i.test(m[0]));if(rule.title.startsWith('介词与动词原形'))matches=matches.filter(m=>{const word=m[0].split(/\s+/).pop().replace(/^(?:s|m|t|l|d)['’]/,'');return /(?:er|ir|re|oir)$/.test(word)&&!['soutenir','plaisir'].includes(word);});if(rule.title.startsWith('aider quelqu'))matches=matches.filter(m=>!/(?:l['’]|\b(?:une|cette|leur|son|une grande)\s+)$/.test(text.slice(Math.max(0,m.index-16),m.index)));if(rule.title.startsWith('指示限定词'))matches=matches.filter(m=>!/^ce\s+(?:qui|que|dont|quand)\b/i.test(m[0]));if(matches.length)output.push({...rule,quotes:[...new Set(matches.map(m=>m[0]))]});}return output;}
function node(tag,text,className){const el=document.createElement(tag);if(text)el.textContent=text;if(className)el.className=className;return el;}
function render(container,item){const fr=String(item.fr||'').trim();container.replaceChildren();container.append(node('h3','当前正确原文'),node('p',fr,'ga-original'));if(item.zh)container.append(node('p','中文提示：'+item.zh));
const notes=analyze(fr);container.append(node('h3','句型与语法拆解'));
if(!notes.length)container.append(node('p','这条原文暂未命中已收录的句型规则。下方展示词汇与已有用法提示；不据拼写猜测未确定的语法。','ga-note'));
for(const r of notes){const box=node('article',null,'ga-card');box.append(node('h4',r.title),node('p','原文定位：'+r.quotes.join(' ／ '),'ga-quote'),node('p',r.explanation),node('p','示例（用于说明规则）：'+r.example));if(r.pitfall)box.append(node('p','注意：'+r.pitfall,'ga-note'));container.append(box);}
container.append(node('h3','词汇与固定表达'));
const table=node('table',null,'ga-table');const header=node('tr');['法语','中文','用法／词性'].forEach(t=>header.append(node('th',t)));table.append(header);let seen=new Set(),count=0;
function row(a,b,c){if(seen.has(norm(a)))return;seen.add(norm(a));const tr=node('tr');[a,b,c||''].forEach(t=>tr.append(node('td',t)));table.append(tr);count++;}
if(item.fr&&item.zh&&item.fr.length<220)row(item.fr,item.zh,item.usage||'当前词条的原有中文提示');
const normalized=' '+norm(fr)+' ';
for(const entry of window.TCF_GRAMMAR_GLOSSARY||[]){const expression=norm(entry.fr).replace(/[.!?]+$/,'');if(expression.length>3&&normalized.includes(' '+expression+' '))row(entry.fr,entry.zh,entry.usage||'来自五个表达练习页中已整理的对应词条');}
for(const word of fr.match(/[\p{L}]+/gu)||[]){const key=norm(word),entry=lexical[key];if(entry)row(word,...entry);}
if(count){const scroll=node('div',null,'ga-table-wrap');scroll.append(table);container.append(scroll);}else container.append(node('p','当前没有已收录的中文词义匹配；下方仍可查看名词性别提示。','ga-note'));
if(item.usage)container.append(node('h3','本题原有用法提示'),node('p',item.usage));
const conjugations=window.TCF_CORPUS_CONJUGATIONS||window.TCF_CONJUGATIONS;if(conjugations)conjugations.render(container,fr);
window.TCF_NOUNS?.render(container,fr);
container.append(node('p','分析仅针对上方正确原文，不修改题目或判分规则。自动笔记覆盖已收录词汇与规则；多义词、复杂从句与未收录结构仍须结合上下文确认。','ga-note'));
const sources=node('details'),summary=node('summary','语法参考来源');sources.append(summary);for(const [title,url] of [['加拿大语言门户：rendre 与形容词','https://nos-langues.canada.ca/fr/cles-de-la-redaction/rendre-suivi-dun-adjectif'],['OQLF：宾语表语与形容词配合','https://vitrinelinguistique.oqlf.gouv.qc.ca/24285/la-grammaire/la-grammaire-actuelle/les-fonctions-et-roles-syntaxiques/lattribut'],['OQLF：阴性词前 mon / ton / son','https://vitrinelinguistique.oqlf.gouv.qc.ca/24157/la-grammaire/les-determinants/determinants-possessifs/mon-ton-et-son-devant-des-mots-feminins']]){const link=node('a',title);link.href=url;link.target='_blank';link.rel='noopener';const paragraph=node('p');paragraph.append(link);sources.append(paragraph);}container.append(sources);
}
function init(){const answer=document.getElementById('answer')||document.getElementById('answerBox'),clear=document.getElementById('clear')||document.getElementById('clearBtn');if(!answer||!clear)return;
const style=node('style');style.textContent='.ga-panel{margin:16px 0;padding:18px;border:1px solid #cfd4ea;border-radius:14px;background:#fafbff;color:#24304b;line-height:1.8;overflow-wrap:anywhere}.ga-panel[hidden]{display:none!important}.ga-panel h3{margin:18px 0 8px;font-size:19px}.ga-panel h4{margin:0 0 6px;font-size:16px}.ga-panel p{margin:7px 0}.ga-original{white-space:pre-wrap;background:#eef0fb;padding:14px;border-radius:9px;font-size:18px}.ga-card{padding:14px;margin:12px 0;border:1px solid #e0e4f0;border-radius:10px;background:#fff}.ga-quote{color:#5459af;font-weight:600}.ga-note{font-size:13px;color:#647087}.ga-table-wrap{max-width:100%;overflow:auto}.ga-table{width:100%;border-collapse:collapse;font-size:14px}.ga-table th,.ga-table td{text-align:left;border:1px solid #dce1ed;padding:10px;vertical-align:top;min-width:100px}.ga-table th{background:#edf0fb}.ga-close{float:right}.ga-panel a{color:#4b56b7}@media(max-width:600px){.ga-panel{padding:12px}.ga-table td{padding:7px}.ga-original{font-size:16px}}';document.head.append(style);
const button=node('button','语法分析');button.type='button';button.id='grammarAnalysis';button.className=clear.className;button.setAttribute('aria-expanded','false');button.setAttribute('aria-controls','grammarPanel');clear.after(button);
const panel=node('section',null,'ga-panel');panel.id='grammarPanel';panel.hidden=true;panel.setAttribute('aria-label','当前原文的语法分析');const close=node('button','收起分析','ga-close');close.type='button';const body=node('div');panel.append(close,body);clear.parentElement.after(panel);let identity='';
function hide(){panel.hidden=true;button.setAttribute('aria-expanded','false');}
close.onclick=hide;button.onclick=()=>{if(answer.disabled)return;const item=window.TCF_GRAMMAR_TARGET?.();if(!item?.fr){hide();return;}const key=JSON.stringify(item);if(!panel.hidden&&identity===key){hide();return;}identity=key;render(body,item);panel.hidden=false;button.setAttribute('aria-expanded','true');};
// Topic/paragraph changes invalidate old notes; typing does not hide them.
const observer=new MutationObserver(()=>{if(panel.hidden)return;const item=window.TCF_GRAMMAR_TARGET?.();if(JSON.stringify(item)!==identity)hide();});const prompt=document.getElementById('prompt')||document.getElementById('promptText')||document.getElementById('promptZh');if(prompt)observer.observe(prompt,{childList:true,subtree:true,characterData:true});
document.addEventListener('click',event=>{const el=event.target.closest('button');if(el&&/^(prev|next|random|shuffle)/.test(el.id))hide();});document.addEventListener('change',event=>{if(event.target.tagName==='SELECT')hide();});
}
window.TCF_GRAMMAR={analyze,render};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
