/* Noun gender hints for every TCF trainer. Offline; no paid API. */
(()=>{'use strict';
const DATA=window.TCF_NOUN_DATA||{},ADJ=new Set(window.TCF_NOUN_ADJECTIVES||[]);
const DET=new Set('le la les un une des du au aux ce cet cette ces mon ton son ma ta sa mes tes ses notre votre leur nos vos leurs quelques plusieurs chaque tout toute tous toutes aucun aucune certains certaines deux trois'.split(' '));
const MG=new Set('le un du au ce cet aucun'.split(' ')),FG=new Set('la une cette ma ta sa toute aucune'.split(' '));
const SUBJECT=new Set('je tu il elle on nous vous ils elles ne me te se lui leur y en'.split(' '));
const NOTES={livre:'书籍：阳性；重量／货币单位：阴性。',mémoire:'记忆：阴性；论文／报告：阳性。',poste:'职位／岗位：阳性；邮政：阴性。',mode:'方式：阳性；时尚：阴性。',tour:'轮次／游览：阳性；塔：阴性。',aide:'帮助／援助：阴性；助手：依所指的人可用阴性或阳性。',gens:'通常按阳性复数配合；紧贴前面的某些形容词有阴性配合规则。',personne:'名词 personne 是阴性，即使指男性；否定代词 personne 不作名词标注。',professeur:'professeur 是阳性名词；对应阴性形式常用 professeure。',espace:'一般“空间”为阳性；排印中的空格可为阴性。',cours:'课程／过程：阳性；cour 的复数 cours（庭院）：阴性。'};
function tokens(fr){return [...fr.normalize('NFC').matchAll(/[\p{L}\p{M}]+(?:-[\p{L}\p{M}]+)*/gu)].map(m=>({word:m[0],key:m[0].toLocaleLowerCase('fr'),start:m.index,end:m.index+m[0].length}));}
function determiner(ts,i,fr){let j=i-1,skipped=0;while(j>=0&&skipped<3&&ADJ.has(ts[j].key)&&!DET.has(ts[j].key)&&!/[,;.!?\n]/.test(fr.slice(ts[j].end,ts[j+1].start))){j--;skipped++;}const t=ts[j];if(!t)return null;const gap=fr.slice(t.end,ts[j+1]?.start||ts[i].start);if(/[,;.!?\n]/.test(gap))return null;if(DET.has(t.key))return{key:t.key,index:j};if(t.key==='l'&&/^[’']\s*$/.test(fr.slice(t.end,ts[j+1].start)))return{key:'l',index:j};return null;}
function analyze(fr){fr=fr.normalize('NFC');const ts=tokens(fr),out=[];for(let i=0;i<ts.length;i++){const t=ts[i],entry=DATA[t.key];if(!entry||t.word.length<2)continue;const [senses,mask]=entry,d=determiner(ts,i,fr),before=ts[i-1]?.key||'',prior=d?ts[d.index-1]?.key:'';
// Noun/verb, noun/adjective and noun/function-word homographs require a noun phrase.
if(mask&&!d)continue;
const next=ts[i+1];if((mask&1)&&next&&DATA[next.key]&&!DET.has(next.key)&&!/[,.!?;:\n]/.test(fr.slice(t.end,next.start)))continue;
if(t.key==='abord'&&before==='d')continue;
if(mask&2&&d&&['le','la','les','l'].includes(d.key)&&(SUBJECT.has(prior)||['j','s','m','t','n'].includes(prior)))continue;
if(mask&2&&['ai','as','a','avons','avez','ont','avait','avaient','est','sont'].includes(before))continue;
if((mask&1)&&d?.key==='l'&&['est','sont','être'].includes(prior))continue;
if(t.key==='personne'&&!d)continue;
let genders=[...new Set(senses.map(x=>x[1]).filter(g=>g!=='?'))],gender=genders.length===1?genders[0]:genders.length>1?'mf':'?';let method='词库';
const explicit=d&&(MG.has(d.key)?'m':FG.has(d.key)?'f':null);
// Never use mon/ton/son to infer gender: mon amie remains feminine.
if(explicit&&(gender==='mf'||gender==='?')){gender=explicit;method='原文限定词 '+d.key;}
if(t.key==='aide'||t.key==='aides'){const pre=fr.slice(Math.max(0,t.start-45),t.start).toLowerCase();if(/(?:à\s+l['’]|sans\s+l['’]|de\s+l['’]|d['’]|besoin\s+d['’]|en\s+|une\s+)$/u.test(pre)){gender='f';method='帮助／援助这一词义';}}
out.push({...t,lemma:senses[0][0],gender,method,note:NOTES[senses[0][0]]||'',raw:fr.slice(t.start,t.end)});}
return out;}
function label(g){return {m:'阳性 · m.',f:'阴性 · f.',mf:'阳／阴 · 按词义或所指的人', '?':'性别待确认'}[g];}
function render(container,fr){if(!container||typeof fr!=='string')return;container.querySelectorAll(':scope > .noun-panel').forEach(n=>n.remove());fr=fr.normalize('NFC');const rows=analyze(fr),box=document.createElement('section');box.className='noun-panel';const title=document.createElement('strong');title.textContent='正确原文 · 名词阴阳性';const legend=document.createElement('p');legend.className='noun-note';legend.textContent='蓝色 m.＝阳性　玫红 f.＝阴性　灰色＝双性／待确认。看原词，也看单数原形。';box.append(title,legend);const line=document.createElement('p');line.className='noun-expression';let at=0;for(const r of rows){line.append(document.createTextNode(fr.slice(at,r.start)));const m=document.createElement('mark');m.className='noun-'+r.gender;m.textContent=r.raw;m.title=r.lemma+' · '+label(r.gender);m.append();line.append(m);at=r.end;}line.append(document.createTextNode(fr.slice(at)));box.append(line);const list=document.createElement('div');list.className='noun-list';const seen=new Set();for(const r of rows){const key=r.lemma+'|'+r.gender;if(seen.has(key))continue;seen.add(key);const item=document.createElement('div');item.className='noun-entry';const tag=document.createElement('span');tag.className='noun-tag noun-'+r.gender;tag.textContent=r.lemma;item.append(tag,document.createTextNode(' — '+label(r.gender)+(r.note?'；'+r.note:'')));list.append(item);}if(!rows.length){const p=document.createElement('p');p.textContent='此处未识别出可标注的名词。';list.append(p);}box.append(list);const note=document.createElement('p');note.className='noun-note';note.textContent='这是词库与上下文规则提示，不是完整语法分析。未着色不代表不是名词；同形词无法确定时保留歧义，不凭词尾猜性别。';const source=document.createElement('a');source.href=new URL('noun-sources.md',document.currentScript?.src||scriptURL).href;source.textContent='词库来源';source.target='_blank';source.rel='noopener';note.append(' ',source);box.append(note);container.append(box);}
const scriptURL=document.currentScript.src;const css=document.createElement('style');css.textContent=`.noun-panel{margin:16px 0 0;padding:16px;border:1px solid #dce4ec;background:#fff;border-radius:12px;color:#24304b;white-space:normal;max-width:100%;min-width:0}.noun-expression{font-size:18px;line-height:1.9;white-space:pre-wrap;overflow-wrap:anywhere;max-height:360px;overflow:auto}.noun-expression mark,.noun-tag{padding:1px 4px;border-radius:4px;box-decoration-break:clone}.noun-m{background:#dcecff;color:#17497a}.noun-f{background:#ffe1ef;color:#92265a}.noun-mf,.noun-\\?{background:#edf0f3;color:#455468}.noun-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));gap:8px;max-height:300px;overflow:auto}.noun-entry{font-size:14px;line-height:1.8;overflow-wrap:anywhere}.noun-note{font-size:13px;line-height:1.7;color:#627083;white-space:normal}.noun-tag{font-weight:600}@media(max-width:600px){.noun-panel{padding:12px}.noun-expression{font-size:16px}}`;document.head.append(css);window.TCF_NOUNS={analyze,render,version:1};
})();
