'use strict';
const KEY='TCF-COMBINED-EXPRESSIONS-v1',names=['动词搭配','固定句型','动词固定用法'];
const $=id=>document.getElementById(id);
let state={version:1,app:'tcf-combined',records:{},module:0,current:null,source:'',patternSource:'0'};
let mode=0,current=null,order=null;
try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.app==='tcf-combined'&&x.version===1&&x.records)state={...state,...x};}catch(e){}
function persist(){state.module=mode;state.current=current?.id||null;try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){$('toast').textContent='浏览器未能保存进度，请导出备份。';}}
function rec(id=current?.id){return state.records[id]||(state.records[id]={draft:'',attempts:0,correct:0,wrong:0,last:null,error:null});}
function saveDraft(){if(current){rec().draft=$('answer').value;persist();}}
function selectedSource(){return $('sourceFilter').value;}
function belongs(x,s){return s===''||x.origins.includes(Number(s));}
function scoped(){return DATA.filter(x=>x.module===mode&&belongs(x,selectedSource()));}
function categoriesFor(x){const s=selectedSource();return [...new Set(x.members.filter(m=>s===''||m.sourceIndex===Number(s)).map(m=>m.category))];}
function filtered(){let rs=scoped().filter(x=>(!$('category').value||categoriesFor(x).includes($('category').value))&&x.zh.includes($('search').value.trim()));const f=$('status').value;if(f)rs=rs.filter(x=>{const r=state.records[x.id];return f==='new'?!r?.attempts:f==='wrong'?r?.error&&!r.error.resolved:r?.last===true;});if(order)rs.sort((a,b)=>order.indexOf(a.id)-order.indexOf(b.id));return rs;}
function errorItems(){return DATA.filter(x=>state.records[x.id]?.error&&($('showResolved').checked||!state.records[x.id].error.resolved)&&(!$('errModule').value||x.module===Number($('errModule').value))&&belongs(x,$('errSource').value));}
function stats(){const rs=mode==='errors'?errorItems():filtered();$('total').textContent=rs.length;$('done').textContent=rs.filter(x=>state.records[x.id]?.attempts).length;$('pending').textContent=rs.filter(x=>state.records[x.id]?.error&&!state.records[x.id].error.resolved).length;$('errCount').textContent=Object.values(state.records).filter(r=>r.error&&!r.error.resolved).length;}
function list(){const rs=filtered();$('list').replaceChildren();$('listCount').textContent=rs.length+' 条表达';const frag=document.createDocumentFragment();for(const x of rs){const b=document.createElement('button');b.className='item'+(current?.id===x.id?' active':'');b.textContent=x.zh;const s=document.createElement('small'),r=state.records[x.id];s.textContent=x.origins.map(p=>SOURCE_NAMES[p]).join(' / ')+' · '+categoriesFor(x).join(' / ')+(r?.error&&!r.error.resolved?' · 待复习':r?.last?' · 已答对':'');b.append(s);b.onclick=()=>show(x);frag.append(b);}$('list').append(frag);stats();}
function show(x){saveDraft();current=x;$('practice').classList.toggle('hidden',!x);if(!x){$('toast').textContent='这个筛选下暂无表达。';list();persist();return;}$('toast').textContent='';$('prompt').textContent=x.zh;$('position').textContent=x.origins.map(p=>SOURCE_NAMES[p]).join(' / ')+' · '+categoriesFor(x).join(' / ')+' · '+(filtered().findIndex(t=>t.id===x.id)+1)+' / '+filtered().length;$('answer').value=rec().draft;$('feedback').classList.add('hidden');$('reference').classList.add('hidden');$('reveal').textContent='显示答案';$('moduleTitle').textContent=names[x.module]+(x.module===1?' · '+SOURCE_NAMES[Number(selectedSource())]:'');$('rule').textContent=x.module===0?'核对完整搭配；忽略大小写、标点和多余空格，保留重音。':'只核对核心表达。占位词可省略；qqch / qch、qqn / qn、qqch ou qqn / qch ou qn 均可。核心词、时态、介词和重音须正确。';list();persist();}
function rebuildCategories(){const previous=$('category').value;$('category').replaceChildren(new Option('全部分类',''));for(const c of [...new Set(scoped().flatMap(categoriesFor))])$('category').add(new Option(c,c));if([...$('category').options].some(o=>o.value===previous))$('category').value=previous;}
function buildSource(){const desired=mode===1?state.patternSource:state.source;$('sourceFilter').replaceChildren();if(mode!==1)$('sourceFilter').add(new Option('全部来源',''));SOURCE_NAMES.forEach((n,p)=>{const count=DATA.filter(x=>x.module===mode&&x.origins.includes(p)).length;$('sourceFilter').add(new Option(n+' · '+count+' 条',String(p)));});$('sourceFilter').value=[...$('sourceFilter').options].some(o=>o.value===desired)?desired:mode===1?'0':'';$('sourceNote').textContent=mode===1?'固定句型按来源分别练习，下拉菜单一次选择一个子模块。':'同一表达只练一次；显示并保留所有来源。也可按来源筛选。';}
function setModule(m){saveDraft();mode=m;order=null;current=null;document.querySelectorAll('[data-module]').forEach(b=>{const active=b.dataset.module===String(m);b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});const practice=Number.isInteger(m);$('practiceFilters').classList.toggle('hidden',!practice);$('practiceStats').classList.toggle('hidden',m==='vocab');$('practice').classList.toggle('hidden',!practice);$('errorsView').classList.toggle('hidden',m!=='errors');$('vocabularyView').classList.toggle('hidden',m!=='vocab');$('toast').textContent='';if(m==='vocab'){window.COMBINED_VOCAB?.render();persist();return;}if(m==='errors'){errors();persist();return;}buildSource();rebuildCategories();const saved=DATA.find(x=>x.id===state.current);show(saved&&filtered().includes(saved)?saved:filtered()[0]||null);}

function appendDifferenceRuns(node,runs,className){
 for(const run of runs){if(run.marked){const mark=document.createElement('mark');mark.className=className;mark.textContent=run.text;node.append(mark);}else node.append(document.createTextNode(run.text));}
}
function renderAnswerDifference(container,input,item){
 const diff=answerDifference(input,item);if(!diff)return;
 const view=document.createElement('div');view.className='answer-difference';
 const legend=document.createElement('p');legend.className='diff-legend';legend.textContent='红色：写错或多写　绿色：正确写法／需要补上的部分';
 const grid=document.createElement('div');grid.className='diff-grid';
 for(const [label,runs,cls] of [[diff.core?'你的答案（核心部分）':'你的答案',diff.inputRuns,'diff-wrong'],[diff.core?'正确核心表达':'正确表达',diff.targetRuns,'diff-required']]){
  const section=document.createElement('div'),head=document.createElement('strong'),line=document.createElement('div');head.textContent=label;line.className='diff-line';appendDifferenceRuns(line,runs,cls);if(!runs.length){const empty=document.createElement('span');empty.className='note';empty.textContent='（未写出核心表达）';line.append(empty);}section.append(head,line);grid.append(section);
 }
 const note=document.createElement('p');note.className='note';note.textContent='按原审核规则忽略大小写、标点和允许的占位词写法，保留重音。'+(diff.truncated?'此处显示前 500 个字符。':'');
 view.append(legend,grid,note);container.append(view);
}

function check(){if(!current)return;const input=$('answer').value.trim();if(!input){$('toast').textContent='请先写出法语再检查。';return;}saveDraft();const result=grade(input,current),r=rec();r.attempts++;r.last=result.ok;r[result.ok?'correct':'wrong']++;if(!result.ok)r.error={...(r.error||{}),answer:input,count:(r.error?.count||0)+1,resolved:false,date:new Date().toISOString()};else if(r.error)r.error.resolved=true;$('feedback').className='feedback '+(result.ok?'ok':'bad');$('feedback').textContent=result.ok?'✓ 正确'+(current.module===0?'，完整搭配已核对。':'，核心表达已核对。'):'还差一点。\n你的答案：'+input+'\n正确表达：'+current.fr+'\n需要保留的核心：'+result.cores.join(' 或 ')+'\n已加入错题本。';if(!result.ok)renderAnswerDifference($('feedback'),input,current);window.TCF_CONJUGATIONS?.render($('feedback'),current.fr);window.TCF_NOUNS?.render($('feedback'),current.fr);persist();list();}
function errors(){const items=errorItems();$('errorList').replaceChildren();if(!items.length){const p=document.createElement('p');p.className='muted';p.textContent='当前没有符合条件的错题。';$('errorList').append(p);}for(const x of items){const e=state.records[x.id].error,b=document.createElement('div');b.className='errorItem';const head=document.createElement('small');head.textContent=names[x.module]+' · '+x.origins.map(p=>SOURCE_NAMES[p]).join(' / ')+' · 错 '+e.count+' 次'+(e.resolved?' · 已订正':' · 待复习');const title=document.createElement('p');title.textContent=x.zh;const detail=document.createElement('details'),summary=document.createElement('summary');summary.textContent='查看错误与正确表达';const text=document.createElement('p');text.textContent='错误：'+e.answer+'\n正确：'+x.fr;detail.append(summary,text);window.TCF_NOUNS?.render(detail,x.fr);renderAnswerDifference(detail,e.answer,x);const btn=document.createElement('button');btn.textContent='重新练习';btn.onclick=()=>{state.patternSource=String(x.origins[0]);state.source='';$('status').value='';$('search').value='';$('category').value='';setModule(x.module);show(x);$('answer').value='';rec().draft='';persist();$('answer').focus();};b.append(head,title,detail,btn);$('errorList').append(b);}stats();}
document.querySelectorAll('[data-module]').forEach(b=>b.addEventListener('click',()=>setModule(['errors','vocab'].includes(b.dataset.module)?b.dataset.module:Number(b.dataset.module))));
$('sourceFilter').onchange=()=>{saveDraft();if(mode===1)state.patternSource=selectedSource();else state.source=selectedSource();order=null;$('category').value='';rebuildCategories();show(filtered()[0]||null);};
for(const id of ['category','status','search'])$(id).addEventListener(id==='search'?'input':'change',()=>{order=null;show(filtered()[0]||null);});
$('answer').oninput=saveDraft;$('answer').onkeydown=e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();check();}};$('check').onclick=check;
window.TCF_GRAMMAR_TARGET=()=>current?({fr:current.fr,zh:current.zh,usage:current.usage||''}):null;$('reveal').onclick=()=>{if(!current)return;const hidden=$('reference').classList.contains('hidden');$('reference').textContent='法语表达：'+current.fr+'\n核心核对：'+variants(current).join(' 或 ')+'\n\n'+current.members.map(m=>SOURCE_NAMES[m.sourceIndex]+' · '+m.category+' · 来源表第 '+m.row+' 行\n中文：'+m.zh+(m.usage?'\n用法提示：'+m.usage:'')+'\n原文例句：'+(m.example||'')+'\n出处：'+(m.source||'')).join('\n\n────────\n\n');window.TCF_NOUNS?.render($('reference'),current.fr);$('reference').classList.toggle('hidden',!hidden);$('reveal').textContent=hidden?'隐藏答案':'显示答案';};
$('clear').onclick=()=>{$('answer').value='';saveDraft();$('feedback').classList.add('hidden');};
function move(d){const rs=filtered(),n=rs.findIndex(x=>x.id===current?.id)+d;if(n>=0&&n<rs.length)show(rs[n]);else $('toast').textContent='已到当前列表边界。';}
$('prev').onclick=()=>move(-1);$('next').onclick=()=>move(1);$('random').onclick=()=>{const rs=filtered();if(rs.length)show(rs[Math.floor(Math.random()*rs.length)]);};$('shuffle').onclick=()=>{order=filtered().map(x=>x.id);for(let i=order.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[order[i],order[j]]=[order[j],order[i]];}show(filtered()[0]||null);};
SOURCE_NAMES.forEach((n,p)=>$('errSource').add(new Option(n,String(p))));for(const id of ['errModule','errSource','showResolved'])$(id).onchange=errors;
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('export').onclick=()=>{saveDraft();download(new Blob([JSON.stringify({...state,vocabulary:window.COMBINED_VOCAB?.getWords()||[]},null,2)],{type:'application/json'}),'TCF-综合表达-进度与单词本.json');};
$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const x=JSON.parse(await f.text());if(x.app!=='tcf-combined'||x.version!==1||!x.records||typeof x.records!=='object'||Array.isArray(x.records))throw Error('请选择本综合网页导出的进度文件。');for(const [id,r] of Object.entries(x.records)){if(!DATA.some(t=>t.id===id)||!r||typeof r.draft!=='string'||!['attempts','correct','wrong'].every(k=>Number.isInteger(r[k])&&r[k]>=0)||(r.error&&(typeof r.error.answer!=='string'||typeof r.error.resolved!=='boolean'||!Number.isInteger(r.error.count))))throw Error('进度文件内容不正确。');}if(x.vocabulary&&!window.COMBINED_VOCAB?.validateWords(x.vocabulary))throw Error('单词本内容不正确。');if(x.vocabulary&&!window.COMBINED_VOCAB.importWords(x.vocabulary))throw Error('单词本未能保存，请导出当前记录备份。');state.records={...state.records,...x.records};persist();mode==='errors'?errors():Number.isInteger(mode)?show(current):window.COMBINED_VOCAB.render();$('toast').textContent='进度与单词本已导入。';}catch(err){$('toast').textContent=err.message;}e.target.value='';};
window.COMBINED_UI={openVocabulary:()=>setModule('vocab'),closeVocabulary:()=>setModule(0),source:()=>current?current.origins.map(p=>SOURCE_NAMES[p]).join(' / '):'TCF 综合表达'};
window.TRAINER_TEST={DATA,grade,variants,answerDifference,getState:()=>state,setModule,filtered,show};
const restoreId=state.current;const restoreMode=[0,1,2,'errors','vocab'].includes(state.module)?state.module:0;setModule(restoreMode);if(Number.isInteger(restoreMode)){const item=filtered().find(x=>x.id===restoreId);if(item)show(item);}


