'use strict';
(()=>{
 const M=10,D=ORAL_ERRORS_DATA,all=[...D.entries,...D.teaching],map=new Map(all.map(e=>[e.id,e]));
 names[M]='我的口语错题本';
 // Register canonical IDs in the existing progress/export/import ecosystem.
 all.forEach(e=>DATA.push({id:e.id,module:M,fr:e.correct,zh:e.explanation||e.pattern,origins:[4],category:e.category,members:[{fr:e.correct,zh:e.explanation||e.pattern,sourceIndex:4,category:e.category,source:e.source.join('\n'),example:e.correct}]}));
 const el=(tag,text='',cls='')=>{const e=document.createElement(tag);e.textContent=text;e.className=cls;return e;};
 const btn=(text,fn,cls='')=>{const b=el('button',text,cls);b.type='button';b.onclick=fn;return b;};
 state.oralErrors={view:'home',category:'',frequency:'',status:'',boundary:'real',search:'',original:'',tag:'',phase:'learn',training:'correct',offset:0,...state.oralErrors};const u=()=>state.oralErrors;
 const record=id=>{const r=rec(id);return r.oral||(r.oral={status:'new',favorite:false,notes:'',editedContent:null,correctCount:0,wrongCount:0,lastReviewed:null,nextReview:null,lastWrong:null});};
 const effective=e=>({...e,...record(e.id).editedContent,id:e.id});
 const save=()=>persist();let revealed=new Set(),openedOriginals=new Set(),editing=null,entering=false;
 const controls=el('section','','hidden');controls.id='oralControls';controls.innerHTML='<h2>我的口语错题本</h2><label>搜索法语 / 中文 / 原稿编号<input id="oralSearch" type="search" placeholder="permettre、介词、072"></label><label>八大专项<select id="oralCategory"><option value="">全部专项</option></select></label><label>历史频率<select id="oralFrequency"><option value="">全部</option><option value="high">高频 · 5 次起</option><option value="medium">中频 · 2–4 次</option><option value="low">低频 · 1 次</option></select></label><label>学习状态<select id="oralStatus"><option value="">全部</option><option value="new">未学习</option><option value="mastered">已掌握</option><option value="unmastered">未掌握</option><option value="favorite">收藏</option><option value="recent">最近错过 · 7 天</option><option value="due">到期复习</option></select></label><label>记录边界<select id="oralBoundary"><option value="real">明确语言错误</option><option value="self">已自我修正</option><option value="occasional">偶发问题 · 1 次</option><option value="all">真实错题 + 教学资料</option><option value="teaching">教学资料</option><option value="audio">待核音（不计错误）</option><option value="optimization">表达优化（不计错误）</option></select></label><label>原稿编号<input id="oralOriginal" inputmode="numeric" placeholder="001–171"></label><label>词条标签<input id="oralTag" placeholder="固定搭配、已自我修正"></label><p id="oralCount" class="note"></p><button id="oralReset">清除筛选</button>';
 $('practiceFilters').before(controls);D.categories.forEach((s,i)=>$('oralCategory').add(new Option(s,String(i))));
 const view=el('section','','hidden');view.id='oralView';$('practice').before(view);
 const dialog=el('dialog');dialog.id='oralEditDialog';dialog.innerHTML='<form id="oralEditForm"><h2>✏️ 编辑词条</h2><label>错误表达<textarea id="oralEditWrong"></textarea></label><label>正确表达<textarea id="oralEditCorrect" required lang="fr"></textarea></label><label>中文解释<textarea id="oralEditExplanation"></textarea></label><label>TCF 推荐表达<textarea id="oralEditRecommended" lang="fr"></textarea></label><div class="oral-actions"><button type="submit" class="primary">保存</button><button type="button" id="oralEditCancel">取消</button></div></form>';document.body.append(dialog);
 function sync(){for(const [id,key] of [['oralSearch','search'],['oralCategory','category'],['oralFrequency','frequency'],['oralStatus','status'],['oralBoundary','boundary'],['oralOriginal','original'],['oralTag','tag']])$(id).value=u()[key];}
 function matches(e){const v=effective(e),r=record(e.id),f=u(),now=Date.now();return (!f.category||e.specialties.includes(+f.category))&&(!f.frequency||e.frequencyBand===f.frequency)&&(!f.original||e.originalIds.includes(+f.original))&&(!f.tag||JSON.stringify(e.tags).includes(f.tag))&&(!f.search||JSON.stringify([v.wrong,v.correct,v.explanation,v.pattern,v.category,e.originalIds.map(i=>String(i).padStart(3,'0')),e.tags,v.source,e.occurrences]).toLowerCase().includes(f.search.toLowerCase()))&&(!f.status||(f.status==='favorite'?r.favorite:f.status==='unmastered'?r.status!=='mastered':f.status==='recent'?r.lastWrong&&now-r.lastWrong<=7*86400000:f.status==='due'?r.nextReview&&r.nextReview<=now:r.status===f.status));}
 function pool(){let rows=u().boundary==='teaching'?D.teaching:u().boundary==='all'?all:D.entries;
 if(u().boundary==='self')rows=rows.filter(e=>e.occurrences.some(o=>o.status==='已自我修正'));
 if(u().boundary==='occasional')rows=rows.filter(e=>e.frequency===1);
 if(u().view==='specialty'&&u().sub==='practice')rows=all;
 return rows.filter(matches).sort((a,b)=>b.frequency-a.frequency||({'高':0,'中':1,'低':2}[a.priority]??3)-({'高':0,'中':1,'低':2}[b.priority]??3)||a.rank-b.rank);}
 function reviewRows(rows){const now=Date.now();return rows.filter(e=>{const r=record(e.id);return r.status==='review'||r.favorite||r.lastWrong&&now-r.lastWrong<7*86400000||r.nextReview&&r.nextReview<=now||e.frequency>=5&&r.status!=='mastered';}).sort((a,b)=>{const rank=e=>{const r=record(e.id);return r.status==='review'?0:r.lastWrong?1:r.nextReview&&r.nextReview<=now?2:r.favorite?3:4;};return rank(a)-rank(b)||b.frequency-a.frequency;});}
 function mark(e,ok){const r=record(e.id),base=rec(e.id),now=Date.now();r.status=ok?'mastered':'review';r.lastReviewed=now;r.nextReview=now+(ok?Math.min(30,2**Math.min(r.correctCount,5)):1)*86400000;r[ok?'correctCount':'wrongCount']++;base.attempts++;base[ok?'correct':'wrong']++;base.last=ok;if(!ok){r.lastWrong=now;base.error={answer:base.draft||'自评：仍不会',count:(base.error?.count||0)+1,resolved:false,date:new Date(now).toISOString()};}else if(base.error)base.error.resolved=true;save();render();}
 function audio(text){const box=el('span','','oral-audio'),status=el('span','','note');status.setAttribute('role','status');box.append(btn('🔊 法语',()=>{const synth=window.speechSynthesis;if(!synth){status.textContent='浏览器不支持朗读';return;}const voices=synth.getVoices().filter(v=>/^fr[-_]/i.test(v.lang));if(!voices.length){status.textContent='请在浏览器或系统中启用法语语音，再重试';return;}window.TCF_AUDIO?.stop();synth.cancel();const speech=new SpeechSynthesisUtterance(String(text).replace(/[\u4e00-\u9fff]+/g,'').replace(/→|\+/g,', '));speech.voice=voices.find(v=>/^fr-FR$/i.test(v.lang))||voices.find(v=>/^fr-CA$/i.test(v.lang))||voices[0];speech.lang=speech.voice.lang;speech.onend=()=>status.textContent='朗读完成';speech.onerror=()=>status.textContent='朗读失败，请重试';synth.speak(speech);status.textContent='正在朗读';}),status);return box;}
 function edit(e){editing=e;const v=effective(e);for(const field of ['Wrong','Correct','Explanation','Recommended'])$('oralEdit'+field).value=v[field.toLowerCase()]||'';dialog.showModal();}
 $('oralEditCancel').onclick=()=>{editing=null;dialog.close();};dialog.oncancel=()=>editing=null;
 $('oralEditForm').onsubmit=ev=>{ev.preventDefault();if(!editing)return;const r=record(editing.id);r.editedContent={};for(const field of ['Wrong','Correct','Explanation','Recommended'])r.editedContent[field.toLowerCase()]=$('oralEdit'+field).value;const adapter=DATA.find(e=>e.id===editing.id);adapter.fr=r.editedContent.correct;adapter.zh=r.editedContent.explanation;editing=null;dialog.close();save();render();};
 function tools(e){const r=record(e.id),bar=el('div','','oral-actions');bar.append(btn(r.favorite?'★ 已收藏':'☆ 收藏',()=>{r.favorite=!r.favorite;save();render();}),btn('✏️ 编辑',()=>edit(e)),btn('✅ 已掌握',()=>mark(e,true)),btn('❌ 仍不会',()=>mark(e,false)));if(r.editedContent)bar.append(btn('恢复原始内容',()=>{r.editedContent=null;const adapter=DATA.find(x=>x.id===e.id);adapter.fr=e.correct;adapter.zh=e.explanation||e.pattern;save();render();}));const notes=el('details'),summary=el('summary',r.notes?'📝 笔记 · 已保存':'📝 笔记'),area=el('textarea');area.value=r.notes;area.setAttribute('aria-label','词条笔记');area.oninput=()=>{r.notes=area.value;summary.textContent='📝 笔记 · 已保存';save();};notes.append(summary,area);bar.append(notes);return bar;}
 function cloze(fr){let answers=[];const stem=fr.replace(/(?<![\p{L}])(aux|au|des|du|de|à|en|pour|avec|dans|que|qui|dont)(?![\p{L}])|(?<![\p{L}])d[’']/giu,m=>{answers.push(m);return '___';});return answers.length?{stem,answers:answers.join(' / ')}:null;}
 const meaningHints={4:'知道做某事：动词后直接接原形，不加介词。',5:'在劳动力市场上。',6:'使某人处于某种状态：动词后接人，再接形容词。',7:'泛指很多人或事物：数量表达后使用介词，注意元音前省音。',8:'结识某人。',9:'帮助某人做某事。',10:'允许某人做某事；让某人能够做某事。',11:'在我看来。',12:'倾向于做某事。',14:'名人：使用法语名词形式。',15:'赌博、博彩类游戏。',16:'参加某项活动。',17:'教某人做某事。',18:'鼓励某人做某事。',19:'在线：使用正确的固定表达。',23:'很多钱：数量表达后正确使用介词。',28:'允许做某事；使做某事成为可能。',29:'意识到某事。',30:'谈论的是……：反身动词在提问时的倒装形式。',31:'在电视上。',32:'从长远来看。',33:'在国外。',35:'正如我们所知道的。',36:'在我们的地球上。',37:'在线、在互联网上：按具体语境选择。',38:'二手的。',39:'面对某个问题或情况。',40:'赌博、博彩类游戏。',41:'家庭成员。',42:'午睡。',43:'保持健康。',44:'在电视上。',45:'在我看来。',46:'面临某种困难。',49:'重视某事；认为某事很重要。',50:'监控摄像头（单数）。',51:'监控摄像头（复数）。',54:'社区：使用法语名词形式。',55:'把时间投入某事。',62:'经常与某人来往：动词直接接人。',68:'剧院：检查冠词的阴阳性。',71:'我们可能……：检查第一人称复数的条件式。',75:'新的某样东西：不定代词后的形容词接法。',77:'对某事感兴趣。',78:'致力于某事。',81:'考虑到某事；使用相应的关系代词时不要重复介词。',86:'在一个国家生活。',90:'有能力做某事。'};
 function chinesePrompt(v){if(!record(v.id).editedContent&&meaningHints[v.rank])return meaningHints[v.rank];const text=String(v.explanation||v.pattern||'').replace(/[^\u3400-\u9fff，。；：？！、（）“”\s]/g,'').replace(/\s+/g,' ').trim();return text||'调用本专项中对应的法语结构，先口头说完整。';}
 function card(e,occurrences=null){const v=effective(e),r=record(e.id),a=el('article','','oral-card');if(occurrences?.length&&!r.editedContent){v.wrong=occurrences[0].wrong;v.correct=occurrences[0].correct;v.explanation=occurrences[0].explanation;v.recommended=occurrences[0].recommended;}a.dataset.oralId=e.id;
 const real=e.sourceType==='real_error';a.append(el('p',(real?'我的真实错误':'专项练习题 · '+(e.sourceType==='training_example'?'延伸训练':'规则例句'))+' · '+(real?({high:'高频',medium:'中频',low:'低频'}[e.frequencyBand])+' · 出现 '+e.frequency+' 次':'教学补充')+' · '+e.category,'note'),el('h3',real?'错误模式 '+e.rank+' · '+D.categories[e.specialties[0]]:D.categories[e.specialties[0]]+' · '+(e.sourceType==='rule_example'?'规则例句':'延伸练习')));
 const training=u().training,blank=training==='cloze'?cloze(v.correct):null;
 let prompt=training==='zh-fr'?chinesePrompt(v):blank?blank.stem:v.wrong||v.explanation||v.pattern;
 a.append(el('p',prompt,'oral-prompt'));
 if(real){const context=el('details'),s=el('summary','查看原稿语境（判错以原意为准）');context.append(s);for(const o of occurrences||e.occurrences){context.append(el('p','原稿 '+String(o.originalId).padStart(3,'0')+' · '+o.status+'\n'+o.sentence));}if(!e.occurrences.length)context.append(el('p','原稿 '+e.originalIds.map(i=>String(i).padStart(3,'0')).join(' / ')+'；完整语境见原题回炉。'));a.append(context);}
 const input=el('textarea');input.lang='fr';input.placeholder='先口头回答，也可以输入法语……';input.value=rec(e.id).draft;input.oninput=()=>{rec(e.id).draft=input.value;record(e.id).status=record(e.id).status==='new'?'learning':record(e.id).status;save();};a.append(input);
 a.append(btn(revealed.has(e.id)?'隐藏答案':'显示答案',()=>{revealed.has(e.id)?revealed.delete(e.id):revealed.add(e.id);render();}));
 if(revealed.has(e.id)){const answer=el('div','','oral-answer');answer.append(el('p','原资料错误模式 / 规则：'+v.pattern,'note'),el('strong','正确表达'),el('p',v.correct),audio(v.correct),el('p','中文解释：'+v.explanation));if(blank)answer.append(el('p','填空参考：'+blank.answers));if(v.recommended)answer.append(el('p','TCF 推荐：'+v.recommended),audio(v.recommended));if(occurrences)for(const o of occurrences)answer.append(el('p','当题真实错误：'+o.wrong+' → '+o.correct+'\n'+o.explanation),audio(o.correct));a.append(answer);}
 a.append(el('p','状态：'+({new:'未学习',learning:'学习中',mastered:'已掌握',review:'待复习'}[r.status])+' · 答对 '+r.correctCount+' / 待巩固 '+r.wrongCount,'note'),tools(e));const source=el('details');source.append(el('summary','来源 · 原稿 '+e.originalIds.map(i=>String(i).padStart(3,'0')).join(' / ')),el('p',e.source.join('\n')));a.append(source);return a;}
 function batch(rows){if(u().phase==='review')rows=reviewRows(rows);const bar=el('div','','oral-actions');for(const [key,label]of [['learn','学习模式'],['review','复习模式']])bar.append(btn(label,()=>{u().phase=key;u().offset=0;save();render();},u().phase===key?'primary':''));const type=el('select');type.setAttribute('aria-label','训练方式');for(const [k,n]of [['correct','改错模式'],['cloze','填空模式'],['zh-fr','中 → 法模式']])type.add(new Option(n,k));type.value=u().training;type.onchange=()=>{u().training=type.value;revealed.clear();save();render();};bar.append(type);view.append(bar);if(u().offset>=rows.length)u().offset=0;const slice=rows.slice(u().offset,u().offset+10);slice.forEach(e=>view.append(card(e)));if(!rows.length)view.append(el('p','当前筛选没有待练词条。'));const nav=el('div','','oral-actions');nav.append(btn('上一批',()=>{u().offset=Math.max(0,u().offset-10);render();}),btn('下一批',()=>{u().offset=u().offset+10>=rows.length?0:u().offset+10;render();}),el('span',rows.length?`${u().offset+1}–${u().offset+slice.length} / ${rows.length}`:'0 条'));view.append(nav);}
 function go(key){Object.assign(u(),{view:key,category:'',offset:0,boundary:key==='search'?'all':'real'});sync();save();render();}
 function overview(){const i=+u().category,d=D.documents[i];const table=el('table','','oral-table');const head=el('tr');head.append(el('th','中文 / 规则 / 意义'),el('th','法语结构 / 示例'));table.append(head);for(const e of [...D.teaching.filter(e=>e.specialties.includes(i)),...D.entries.filter(e=>(d.linkedTeachingIds||[]).includes(e.id))]){const r=el('tr'),fr=el('td');fr.append(el('span',e.correct),audio(e.correct));r.append(el('td',e.explanation),fr);table.append(r);}view.append(table);
 // All Word prose remains accessible with paragraph-level audio; latest true-error tables use canonical IDs.
 const rules=el('details');rules.append(el('summary','专项规则与原文说明（完整保留）'));let section=el('div');for(const p of d.paragraphs){if(!p)continue;if(/^(\d+ |[一二三四五六七八九十]+、|最新完整版更新|合法表达)/.test(p)){section=el('details');section.append(el('summary',p));rules.append(section);}else{const row=el('p',p);if(/[A-Za-zÀ-ÿ]/.test(p))row.append(audio(p));section.append(row);if(section.parentNode!==rules)rules.append(section);}}view.append(rules);
 }
 function originals(){let rows=D.originals.filter(o=>(!u().original||o.id===+u().original)&&(!u().search||JSON.stringify([o.id,String(o.id).padStart(3,'0'),o.title,o.zh,o.group]).toLowerCase().includes(u().search.toLowerCase())));for(const o of rows){const a=el('article','','oral-card');a.dataset.original=o.id;a.append(el('h3','原稿 '+String(o.id).padStart(3,'0')+' · '+o.zh),el('p',o.title),audio(o.title));const raw=el('details');raw.append(el('summary','原始回答 / 完整原稿'),el('p',o.transcript));a.append(raw);const errors=el('details');errors.append(el('summary','查看我当时犯过的错误 · '+o.errorIds.length+' 个模式'));errors.ontoggle=()=>{if(errors.open)openedOriginals.add(o.id);else openedOriginals.delete(o.id);if(!errors.open||errors.dataset.loaded)return;errors.dataset.loaded='1';for(const id of o.errorIds){const e=map.get(id),occ=e.occurrences.filter(d=>d.originalId===o.id);errors.append(card(e,occ));}for(const d of o.unmappedDetails){const p=el('p','原稿真实错误明细（保留原始审核）：'+d.wrong+' → '+d.correct+'\n'+d.explanation);p.append(audio(d.correct));errors.append(p);}if(!o.errorIds.length)errors.append(el('p','这条原稿没有明确语言错误记录。'));};errors.open=openedOriginals.has(o.id);a.append(errors,el('p','重新口头回答，重点避开上述历史错误。'));const notes=el('textarea');notes.placeholder='本次回炉复盘（不要求背原稿）';state.oralOriginalNotes=state.oralOriginalNotes||{};notes.value=state.oralOriginalNotes[o.id]||'';notes.oninput=()=>{state.oralOriginalNotes[o.id]=notes.value;save();};a.append(notes);view.append(a);}if(!rows.length)view.append(el('p','没有匹配原稿。'));}
 function render(){if(mode!==M)return;view.replaceChildren();const nav=el('nav','','oral-actions');nav.append(btn('错题本首页',()=>go('home')));for(const [k,n]of [['frequent','🔥 高频错题'],['specialties','🎯 八大专项'],['originals','🎙 171 原题回炉'],['search','🔎 错题速查']])nav.append(btn(n,()=>go(k),u().view===k?'primary':''));view.append(nav);$('oralCount').textContent=pool().length+' 个匹配词条';
 if(u().view==='home'){view.append(el('h2','我的口语错题本'),el('p','1,127 个真实错误模式 · 171 条原稿 · 8 个专项'));const grid=el('div','','oral-home');for(const [k,n,d] of [['frequent','🔥 高频错题','按历史频率集中纠错'],['specialties','🎯 八大专项','规则速览 / 专项练习 / 真实错题'],['originals','🎙 171 原题回炉','重新回答旧题，避免重犯'],['search','🔎 错题速查','搜索表达、规则和原稿来源']]){const b=btn(n+'\n'+d,()=>go(k));grid.append(b);}view.append(grid,el('p','待核音 430 条、表达优化 25 条单独保留，不计入真实错误。','note'));return;}
 if(u().view==='specialties'){D.categories.forEach((n,i)=>view.append(btn((i+1)+'. '+n+' · '+D.audit.specialties[i]+' 条',()=>{u().view='specialty';u().category=String(i);u().sub='overview';u().phase='learn';sync();render();save();})));return;}
 if(u().view==='originals'){originals();return;}
 if(['audio','optimization'].includes(u().boundary)){const kind=u().boundary==='audio'?'待核音':'表达优化（不计错误）';D.excluded.filter(d=>d.status===kind&&(!u().original||d.originalId===+u().original)&&(!u().search||JSON.stringify(d).toLowerCase().includes(u().search.toLowerCase()))).forEach(d=>{const p=el('article','','oral-card');p.append(el('h3',kind+' · 原稿 '+String(d.originalId).padStart(3,'0')),el('p',d.wrong+'\n原语境：'+d.sentence),el('p','审核建议（不是错误判定）：'+d.correct+'\n'+d.explanation),audio(d.correct));view.append(p);});return;}
 if(u().view==='specialty'){view.append(el('h2',D.categories[+u().category]));const bar=el('div','','oral-actions');for(const [k,n]of [['overview','快速学习 / 规则速览'],['practice','专项练习'],['real','我的真实错题']])bar.append(btn(n,()=>{u().sub=k;u().offset=0;u().phase='learn';u().boundary='real';sync();render();save();},u().sub===k?'primary':''));view.append(bar);if(u().sub==='overview'){overview();return;}}
 batch(pool());if(u().view==='search'&&u().search.trim()){for(const doc of D.documents.filter(d=>!u().category||d.category===+u().category)){const paragraphs=doc.paragraphs.filter(p=>p.toLowerCase().includes(u().search.toLowerCase()));if(!paragraphs.length)continue;const rules=el('details');rules.append(el('summary','规则原文 / 教学说明 · '+D.categories[doc.category]+' · '+paragraphs.length+' 处'));for(const p of paragraphs){const row=el('p',p);if(/[A-Za-zÀ-ÿ]/.test(p))row.append(audio(p));rules.append(row);}rules.append(el('p',doc.file,'note'));view.append(rules);}}save();}
 for(const [id,key]of [['oralSearch','search'],['oralCategory','category'],['oralFrequency','frequency'],['oralStatus','status'],['oralBoundary','boundary'],['oralOriginal','original'],['oralTag','tag']])$(id).addEventListener(['oralSearch','oralOriginal','oralTag'].includes(id)?'input':'change',()=>{u()[key]=$(id).value;u().offset=0;if(u().view==='specialty'&&!u().category)u().view='specialties';render();save();});
 $('oralReset').onclick=()=>{Object.assign(u(),{category:'',frequency:'',status:'',boundary:'real',search:'',original:'',tag:'',offset:0});sync();render();save();};
 function activate(){const active=mode===M;controls.classList.toggle('hidden',!active);view.classList.toggle('hidden',!active);if(active){for(const id of ['practiceFilters','practiceStats','practice','errorsView','vocabularyView','batchControls','batchView','studyView','studyReviewView','t2InversionControls','t2InversionView','speechFlowControls','speechFlowView','c1Controls','c1View'])$(id)?.classList.add('hidden');sync();render();}}
 const oldSet=setModule;setModule=function(m,fresh=false){window.speechSynthesis?.cancel();if(m===M){if(mode!==M){entering=true;try{oldSet(M,fresh);}finally{entering=false;}current=null;order=null;}document.querySelectorAll('[data-module]').forEach(b=>{b.classList.toggle('active',b.dataset.module===String(m));b.setAttribute('aria-pressed',String(b.dataset.module===String(m)));});activate();save();}else{oldSet(m,fresh);activate();}};
 const oldShow=show;show=function(x){if(x?.module===M&&!entering){setModule(M);u().view='search';u().search=x.id;u().category='';u().boundary='all';u().search=effective(map.get(x.id)).correct;sync();render();return;}oldShow(x);};
 const oldDraft=saveDraft;saveDraft=function(){if(mode!==M)oldDraft();};
 const oldImport=$('file').onchange;$('file').onchange=async event=>{const file=event.target.files[0];let extra=null;try{extra=file?JSON.parse(await file.text()):null;}catch{}await oldImport(event);if(extra?.app==='tcf-combined'&&extra?.version===1&&extra.oralErrors&&$('toast').textContent.includes('已导入')){state.oralErrors={...u(),...extra.oralErrors};state.oralOriginalNotes={...state.oralOriginalNotes,...extra.oralOriginalNotes};save();sync();render();}};
 window.COMBINED_UI.closeVocabulary=()=>setModule([0,1,2,3,4,5,6,7,8,9,10,'errors'].includes(state.vocabularyReturnView)?state.vocabularyReturnView:0);
 all.forEach(e=>{const adapter=DATA.find(x=>x.id===e.id),v=effective(e);adapter.fr=v.correct;adapter.zh=v.explanation||v.pattern;});
 window.ORAL_ERRORS={record,effective,pool,reviewRows,go,render,mark,data:D};if(ORAL_ERRORS_RESTORE)setModule(M);else activate();
})();
