'use strict';
(()=>{
 const MODULE=8,TITLE='TCF 高频语流发音训练',norm=s=>String(s||'').normalize('NFC').toLocaleLowerCase('fr').replace(/[’‘]/g,"'").replace(/\s+/g,' ').trim();
 const initial=state.speechFlow||{};state.speechFlow={view:['learn','review','single'].includes(initial.view)?initial.view:'learn',size:[5,10,20].includes(initial.size)?initial.size:10,category:initial.category==='介词冠词及小词组合'?SPEECH_FLOW_CATEGORIES[4]:initial.category||'',grammarGroup:initial.grammarGroup||'',source:initial.source||'',difficulty:initial.difficulty||'',status:initial.status||'',search:initial.search||'',ids:Array.isArray(initial.ids)?initial.ids.filter(id=>SPEECH_FLOW_ITEMS.some(x=>x.id===id)):[],used:Array.isArray(initial.used)?initial.used:[],single:initial.single||null,signature:initial.signature||''};
 const saved=()=>state.speechFlow;
 const field=(x,name)=>rec(x.id).flowEdit?.[name]??x[name];
 const itemStatus=x=>rec(x.id).flowStatus||(rec(x.id).error&&!rec(x.id).error.resolved?'review':rec(x.id).last===true?'mastered':'new');
 function origins(x){return x.sourceSentenceIds.map(id=>SPEECH_FLOW_SOURCES[id]).filter(Boolean);}
 function sourceFor(x){return origins(x).find(s=>!saved().source||s.source===saved().source)||SPEECH_FLOW_SOURCES[x.sourceSentenceId];}
 function pool(){const s=saved(),q=norm(s.search);let rs=SPEECH_FLOW_ITEMS.filter(x=>(!s.category||x.category===s.category)&&(!s.grammarGroup||x.categoryIndex!==4||x.grammarGroup===s.grammarGroup)&&(!s.source||origins(x).some(r=>r.source===s.source))&&(!s.difficulty||x.difficulty===s.difficulty)&&(!s.status||(s.status==='favorite'?rec(x.id).flowFavorite:itemStatus(x)===s.status))&&(!q||norm([field(x,'fr'),field(x,'zh'),field(x,'focus'),field(x,'note'),x.topic,x.question,...origins(x).map(r=>r.theme+' '+r.question+' '+r.fr)].join(' ')).includes(q)));if(q){const rank=x=>norm(field(x,'fr'))===q?0:norm(field(x,'focus')).includes(q)?1:norm(field(x,'zh')).includes(q)?2:3;rs.sort((a,b)=>rank(a)-rank(b));}if(order){const ranks=new Map(order.map((id,i)=>[id,i]));rs.sort((a,b)=>(ranks.get(a.id)??99999)-(ranks.get(b.id)??99999));}return rs;}
 const controls=document.createElement('section');controls.id='speechFlowControls';controls.className='flow-controls hidden';controls.setAttribute('aria-label','语流训练筛选');
 controls.innerHTML='<strong>'+TITLE+'</strong><label for="flowCategory">分类筛选</label><select id="flowCategory"><option value="">全部分类</option></select><label for="flowGrammarGroup">第 5 类结构筛选</label><select id="flowGrammarGroup"><option value="">全部小词结构</option></select><label for="flowSource">来源</label><select id="flowSource"><option value="">Tâche 2 + Tâche 3</option><option>Tâche 2</option><option>Tâche 3</option></select><label for="flowDifficulty">训练难度</label><select id="flowDifficulty"><option value="">全部难度</option><option>基础</option><option>高频</option><option>强化</option></select><label for="flowStatusFilter">练习范围</label><select id="flowStatusFilter"><option value="">全部词条</option><option value="new">尚未练习</option><option value="mastered">已掌握</option><option value="review">待复习</option><option value="favorite">已收藏</option></select><label for="flowSearch">搜索法语／中文／主题／原句</label><input id="flowSearch" type="search" placeholder="例如 qu’on、du voyage、环境"><label for="flowSize">每批词条</label><select id="flowSize"><option value="5">5 个</option><option value="10">10 个</option><option value="20">20 个</option></select><div class="flow-actions"><button id="flowRandom" type="button">随机练习</button><button id="flowShuffle" type="button">打乱顺序</button></div><p id="flowListCount" class="flow-summary"></p><div id="flowList" class="list flow-search-list"></div>';
 $('practiceFilters').before(controls);SPEECH_FLOW_CATEGORIES.forEach(c=>$('flowCategory').add(new Option(c,c)));
 for(const group of 'ABCDEFGH'){const x=SPEECH_FLOW_ITEMS.find(x=>x.grammarGroup===group);if(x)$('flowGrammarGroup').add(new Option(x.grammarType,group));}
 const view=document.createElement('section');view.id='speechFlowView';view.className='hidden';view.setAttribute('aria-label',TITLE);view.innerHTML='<h2>'+TITLE+'</h2><p class="flow-help">第 5 类：把我已经懂的语法小词结构练成口语条件反射。看到结构 → 整块输出 → 放回真实原句。其他分类：听词块 → 慢速跟读 → 正常语速。复习采用口语自评；也可默写词块核对文字。</p><div class="flow-modes"><button type="button" id="flowLearn">学习模式</button><button type="button" id="flowReview">复习模式</button><button type="button" id="flowSingle">单词条练习</button></div><div id="flowStats" class="flow-stats"></div><p id="flowSummary" class="flow-summary" role="status"></p><div id="flowCards" class="flow-cards"></div><audio id="flowAudio" controls preload="none" hidden></audio><p id="flowAudioStatus" class="note" role="status" aria-live="polite"></p><div class="flow-actions"><button id="flowPrev" type="button">上一条</button><button id="flowNext" type="button">下一批</button><button id="flowRestart" type="button">重新开始</button><button id="flowStop" type="button">停止发音</button></div><details class="flow-help"><summary>内容来源与联诵规则</summary><p>训练词块只从口语 T2 与 T3 两个主语料页面抽取，完整原句与全部出处保留。相同词块在同一分类中合并；同句的不同训练重点保留独立词条。</p><p><a href="speech-flow-audit.json" target="_blank" rel="noopener">查看来源与去重核对</a> · <a href="https://vitrinelinguistique.oqlf.gouv.qc.ca/23549/la-prononciation/liaisons/contextes-de-liaisons-obligatoires" target="_blank" rel="noopener">必须 liaison</a> · <a href="https://vitrinelinguistique.oqlf.gouv.qc.ca/23550/la-prononciation/liaisons/contextes-de-liaisons-facultatives" target="_blank" rel="noopener">可选 liaison</a> · <a href="https://vitrinelinguistique.oqlf.gouv.qc.ca/23552/la-prononciation/liaisons/contextes-de-liaisons-interdites" target="_blank" rel="noopener">禁止 liaison</a></p></details>';
 $('practice').before(view);
 const dialog=document.createElement('dialog');dialog.id='flowEditDialog';dialog.className='flow-edit-dialog';dialog.setAttribute('aria-labelledby','flowEditHeading');dialog.innerHTML='<form id="flowEditForm"><h2 id="flowEditHeading">✏️ 编辑训练词条</h2><label for="flowEditFr">法语训练内容</label><textarea id="flowEditFr" lang="fr" required></textarea><label for="flowEditZh">中文意思</label><textarea id="flowEditZh" required></textarea><label for="flowEditFocus">重点发音部分</label><input id="flowEditFocus" lang="fr" required><label for="flowEditNote">发音说明</label><textarea id="flowEditNote" required></textarea><p id="flowEditError" class="note" role="status"></p><div class="flow-actions"><button type="submit" class="primary">保存</button><button type="button" id="flowEditCancel">取消</button></div></form>';document.body.append(dialog);let editing=null;
 function edit(x){editing=x;for(const [name,id]of [['fr','flowEditFr'],['zh','flowEditZh'],['focus','flowEditFocus'],['note','flowEditNote']])$(id).value=field(x,name);document.querySelector('label[for=flowEditFocus]').textContent=x.categoryIndex===4?'重点小词（多个用 | 分隔）':'重点发音部分';document.querySelector('label[for=flowEditNote]').textContent=x.categoryIndex===4?'结构提示':'发音说明';$('flowEditError').textContent='';dialog.showModal();$('flowEditFr').focus();}
 $('flowEditCancel').onclick=()=>{editing=null;dialog.close();};dialog.addEventListener('cancel',()=>{editing=null;});
 $('flowEditForm').onsubmit=e=>{e.preventDefault();if(!editing)return;const data={fr:$('flowEditFr').value.trim(),zh:$('flowEditZh').value.trim(),focus:$('flowEditFocus').value.trim(),note:$('flowEditNote').value.trim()};if(Object.values(data).some(v=>!v)){$('flowEditError').textContent='请填写全部字段。';return;}if(!data.focus.split('|').map(v=>v.trim()).filter(Boolean).every(f=>norm(data.fr).includes(norm(f))||origins(editing).some(s=>norm(s.fr).includes(norm(f))))){$('flowEditError').textContent='重点发音部分需要出现在词块或原句中。';return;}rec(editing.id).flowEdit=data;delete rec(editing.id).flowTextResult;persist();dialog.close();editing=null;render();renderList();};
 const audio=$('flowAudio'),packs=new Map();let manifestPromise=null,request=0,blobUrl=null;
 function stop(){request++;audio.pause();audio.removeAttribute('src');audio.load();audio.hidden=true;if(blobUrl)URL.revokeObjectURL(blobUrl);blobUrl=null;window.speechSynthesis?.cancel();}
 async function loadAudio(text){if(!manifestPromise)manifestPromise=fetch('speech-flow-audio/manifest.json?v=smallwords-2').then(r=>{if(!r.ok)throw Error('发音清单加载失败');return r.json();}).catch(e=>{manifestPromise=null;throw e;});const manifest=await manifestPromise,link=manifest.entries[text];if(!link)return null;const url=new URL(link.pack,new URL('speech-flow-audio/',document.baseURI)).href;if(!packs.has(url))packs.set(url,fetch(url).then(r=>{if(!r.ok)throw Error('发音文件加载失败');return r.json();}).catch(e=>{packs.delete(url);throw e;}));const pack=await packs.get(url),record=pack[link.id];if(!record?.audio)throw Error('发音条目加载失败');return record;}
 async function speak(x,whole,rate){stop();window.TCF_AUDIO?.stop();const token=request;const s=sourceFor(x),text=whole?s.fr:field(x,'fr');$('flowAudioStatus').textContent='正在加载法语'+(rate<1?'慢速':'正常语速')+'朗读……';try{const data=await loadAudio(text);if(token!==request||mode!==MODULE)return;if(!data){const voices=window.speechSynthesis?.getVoices().filter(v=>/^fr[-_]/i.test(v.lang))||[];if(!voices.length)throw Error('自定义内容尚无发音；可以先听原句');const utterance=new SpeechSynthesisUtterance(text);utterance.lang=voices[0].lang;utterance.voice=voices[0];utterance.rate=rate;window.speechSynthesis.speak(utterance);$('flowAudioStatus').textContent='自定义内容 · 浏览器法语朗读';return;}
 blobUrl=URL.createObjectURL(new Blob([Uint8Array.from(atob(data.audio),c=>c.charCodeAt(0))],{type:'audio/mpeg'}));audio.src=blobUrl;audio.hidden=false;audio.playbackRate=rate;audio.preservesPitch=true;$('flowAudioStatus').textContent='Piper · 法语 siwis · '+(rate<1?'慢速 0.75×':'正常 1×')+(whole?' · 原句':' · 词块');try{await audio.play();}catch{$('flowAudioStatus').textContent+=' · 请点击播放器播放';}}catch(e){if(token===request)$('flowAudioStatus').textContent=e.message+'，请重试。';}}
 audio.onended=()=>{$('flowAudioStatus').textContent='朗读完成，可以再跟读一次。';};audio.onerror=()=>{$('flowAudioStatus').textContent='发音播放失败，请重试。';};
 function highlight(node,text,focus,small=false){const normalized=norm(text),parts=String(focus||'').split('|').map(norm).filter(Boolean),ranges=[];for(const f of parts){let at=normalized.indexOf(f);while(at>=0){const before=normalized[at-1]||'',after=normalized[at+f.length]||'';if(!small||(!/[\p{L}]/u.test(before)&&(!/[\p{L}]/u.test(after)||f.endsWith("'"))))ranges.push([at,at+f.length]);at=normalized.indexOf(f,at+f.length);}}ranges.sort((a,b)=>a[0]-b[0]||b[1]-a[1]);let end=0;for(const [a,b]of ranges){if(a<end)continue;node.append(document.createTextNode(text.slice(end,a)));const mark=document.createElement('mark');mark.textContent=text.slice(a,b);node.append(mark);end=b;}node.append(document.createTextNode(text.slice(end)));}
 function button(text,fn,className=''){const b=document.createElement('button');b.type='button';b.textContent=text;b.className=className;b.onclick=fn;return b;}
 function setStatus(x,value){const r=rec(x.id);r.flowStatus=value;r.attempts++;r.last=value==='mastered';r[value==='mastered'?'correct':'wrong']++;if(value==='mastered'){if(r.error)r.error.resolved=true;}else r.error={answer:'口语自评：需要再练',count:(r.error?.count||0)+1,resolved:false,date:new Date().toISOString()};persist();render();renderList();}
 function card(x){const r=rec(x.id),s=sourceFor(x),wrap=document.createElement('article');wrap.className='flow-card'+(current?.id===x.id?' current':'');wrap.dataset.flowId=x.id;const h=document.createElement('h3');h.textContent=field(x,'zh');const tags=document.createElement('div');tags.className='flow-tags';for(const text of [x.category,...(x.grammarType?[x.grammarType]:[]),x.difficulty,s.source,...(x.liaison?[x.liaison]:[])]){const tag=document.createElement('span');tag.className='flow-tag'+(text.includes('liaison')?' liaison':'');tag.textContent=text;tags.append(tag);}wrap.append(h,tags);
 const body=document.createElement('div');let content=body;if(saved().view!=='learn'){const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='显示词块与完整原句';details.append(summary);content=document.createElement('div');details.append(content);body.append(details);}
 const target=document.createElement('div');target.className='flow-target';target.lang='fr';highlight(target,field(x,'fr'),field(x,'focus'),x.categoryIndex===4);const note=document.createElement('p');note.className='flow-help';note.textContent=field(x,'note');const sentence=document.createElement('div');sentence.className='flow-sentence';sentence.lang='fr';highlight(sentence,s.fr,r.flowEdit?.focus||x.focusBySentence?.[s.id]||x.focus,x.categoryIndex===4);const label=document.createElement('strong');label.textContent='原始完整例句';content.append(target,note,label,sentence);if(x.errorHint){const error=document.createElement("p");error.className="flow-help";error.textContent="易错提醒："+x.errorHint;content.append(error);}
 if(x.forms?.length>1){const forms=document.createElement('p');forms.className='flow-help';forms.textContent='原稿词形（合并练习）：'+x.forms.join(' / ');content.append(forms);}wrap.append(body);
 const plays=document.createElement('div');plays.className='flow-actions';for(const [text,whole,rate]of [['🔊 词块 · 正常',false,1],['🔊 词块 · 慢速',false,.75],['🔊 原句 · 正常',true,1],['🔊 原句 · 慢速',true,.75]])plays.append(button(text,()=>speak(x,whole,rate)));wrap.append(plays);
 if(saved().view!=='learn'){const box=document.createElement('details'),sum=document.createElement('summary');sum.textContent='可选：默写词块核对文字';const input=document.createElement('input');input.lang='fr';input.autocomplete='off';input.spellcheck=false;input.value=r.flowDraft||'';input.setAttribute('aria-label','默写：'+field(x,'zh'));input.oninput=()=>{r.flowDraft=input.value;delete r.flowTextResult;persist();};const feedback=document.createElement('p');feedback.className='note';const result=r.flowTextResult;if(result&&result.answer===input.value&&result.target===field(x,'fr'))feedback.textContent=result.ok?'文字正确':'正确词块：'+field(x,'fr');const check=button('核对文字',()=>{if(!input.value.trim()){feedback.textContent='请先填写词块。';return;}const ok=norm(input.value).replace(/[.!?;,]/g,'')===norm(field(x,'fr')).replace(/[.!?;,]/g,'');r.flowTextResult={answer:input.value,target:field(x,'fr'),ok};feedback.textContent=ok?'文字正确':'正确词块：'+field(x,'fr');persist();});box.className='flow-review-answer';box.append(sum,input,check,feedback);wrap.append(box);}
 const actions=document.createElement('div');actions.className='flow-actions';const favorite=button(r.flowFavorite?'★ 已收藏':'☆ 收藏',()=>{r.flowFavorite=!r.flowFavorite;persist();render();renderList();});favorite.setAttribute('aria-pressed',String(!!r.flowFavorite));actions.append(favorite,button('✏️ 编辑词条',()=>edit(x)));for(const [text,val]of [['已掌握 · 能顺口说出','mastered'],['待复习 · 需要再练','review']]){const b=button(text,()=>setStatus(x,val),'flow-status');b.setAttribute('aria-pressed',String(itemStatus(x)===val));actions.append(b);}wrap.append(actions);
 const notes=document.createElement('details'),title=document.createElement('summary'),area=document.createElement('textarea');notes.className='flow-user-note';title.textContent=r.flowNote?'笔记 · 已保存':'笔记';area.value=r.flowNote||'';area.placeholder='记录你容易卡顿的地方或练习提示……';area.setAttribute('aria-label','笔记：'+field(x,'zh'));area.dataset.flowNote=x.id;area.oninput=()=>{r.flowNote=area.value;title.textContent=area.value?'笔记 · 已保存':'笔记';persist();};notes.append(title,area);wrap.append(notes);
 const source=document.createElement('details'),summary=document.createElement('summary');source.className='flow-source';const refs=origins(x).filter(ref=>!saved().source||ref.source===saved().source);summary.textContent='来源：'+s.theme+(s.question?' · '+s.question:'')+'（'+refs.length+' 处）';source.append(summary);let shown=0;const container=document.createElement('div');const more=button('显示更多出处',()=>appendMore());function appendMore(){for(const ref of refs.slice(shown,shown+5)){const p=document.createElement('div');p.className='flow-origin-item';const line=document.createElement('p');line.textContent=ref.source+' · '+ref.theme+'\n'+ref.question+'\n'+ref.fr+'\n'+(ref.source==='Tâche 3'?'原段中文参考：':'原句中文：')+ref.zh;const meta=document.createElement('small');meta.textContent='词条 ID：'+x.id+'\nSource sentence ID：'+ref.id;const a=document.createElement('a');a.href=ref.url;a.target='_blank';a.rel='noopener';a.textContent='打开原稿页面';p.append(line,meta,document.createElement('br'),a);container.append(p);}shown+=5;more.hidden=shown>=refs.length;}source.append(container,more);appendMore();wrap.append(source);return wrap;}
 const signature=()=>JSON.stringify([saved().category,saved().grammarGroup,saved().source,saved().difficulty,saved().status,saved().search]);
 function batch(reset=false){const rs=pool();if(reset||saved().signature!==signature()){saved().used=[];saved().signature=signature();}const used=new Set(saved().used),next=rs.filter(x=>!used.has(x.id)).slice(0,saved().size);if(!next.length&&rs.length&&!reset){$('flowSummary').textContent='当前筛选已经练完，可点击“重新开始”。';return;}saved().ids=next.map(x=>x.id);saved().used=[...new Set([...saved().used,...saved().ids])];saved().single=next[0]?.id||null;current=next[0]||null;persist();render();renderList();}
 function visibleItems(){if(saved().view==='single'){const rs=pool();const x=rs.find(x=>x.id===saved().single)||rs[0];if(x){saved().single=x.id;current=x;}else current=null;return x?[x]:[];}const allowed=new Set(pool().map(x=>x.id));return saved().ids.map(id=>SPEECH_FLOW_ITEMS.find(x=>x.id===id)).filter(x=>x&&allowed.has(x.id));}
 function render(){if(mode!==MODULE)return;const rows=visibleItems(),rs=pool();$('flowCards').replaceChildren();if(!rows.length){const p=document.createElement('p');p.className='flow-empty';p.textContent='当前筛选暂无词条，请调整筛选条件。';$('flowCards').append(p);}else for(const x of rows)$('flowCards').append(card(x));$('flowSummary').textContent='当前筛选 '+rs.length+' 项；'+(saved().view==='single'?'逐条练习':'本批 '+rows.length+' 项')+'。笔记、编辑、收藏与状态在各模式同步。';$('flowStats').replaceChildren();for(const text of ['全部 '+SPEECH_FLOW_ITEMS.length+' 项','已掌握 '+SPEECH_FLOW_ITEMS.filter(x=>itemStatus(x)==='mastered').length,'待复习 '+SPEECH_FLOW_ITEMS.filter(x=>itemStatus(x)==='review').length,'收藏 '+SPEECH_FLOW_ITEMS.filter(x=>rec(x.id).flowFavorite).length]){const span=document.createElement('span');span.textContent=text;span.style.whiteSpace='nowrap';$('flowStats').append(span);}for(const [id,v]of [['flowLearn','learn'],['flowReview','review'],['flowSingle','single']]){$(id).classList.toggle('primary',saved().view===v);$(id).setAttribute('aria-pressed',String(saved().view===v));}$('flowPrev').hidden=saved().view!=='single';$('flowPrev').disabled=!rs.length;$('flowNext').disabled=!rs.length;$('flowNext').textContent=saved().view==='single'?'下一条':'下一批';persist();}
 function renderList(){if(mode!==MODULE)return;const rs=pool(),frag=document.createDocumentFragment();$('flowListCount').textContent=rs.length+' 项训练';$('flowList').replaceChildren();for(const x of rs){const b=button(field(x,'zh'),()=>{saved().single=x.id;saved().view='single';current=x;stop();render();renderList();persist();},'item');const small=document.createElement('small');small.textContent=x.category+' · '+x.difficulty+(itemStatus(x)==='mastered'?' · 已掌握':itemStatus(x)==='review'?' · 待复习':'')+(rec(x.id).flowFavorite?' · ★':'');b.append(small);b.classList.toggle('active',x.id===current?.id);frag.append(b);}$('flowList').append(frag);}
 function activate(){const active=mode===MODULE;controls.classList.toggle('hidden',!active);view.classList.toggle('hidden',!active);if(!active)return;for(const id of ['practiceFilters','practiceStats','practice','batchControls','studyView','studyReviewView','batchView','t2InversionControls','t2InversionView'])$(id)?.classList.add('hidden');for(const [id,k]of [['flowCategory','category'],['flowGrammarGroup','grammarGroup'],['flowSource','source'],['flowDifficulty','difficulty'],['flowStatusFilter','status'],['flowSearch','search'],['flowSize','size']])$(id).value=String(saved()[k]);if(saved().signature!==signature()||!saved().ids.length)batch(true);else{render();renderList();}}
 for(const [id,k]of [['flowCategory','category'],['flowGrammarGroup','grammarGroup'],['flowSource','source'],['flowDifficulty','difficulty'],['flowStatusFilter','status'],['flowSearch','search']]){$(id).addEventListener(id==='flowSearch'?'input':'change',()=>{saved()[k]=$(id).value;if(k==='grammarGroup'&&saved().grammarGroup){saved().category=SPEECH_FLOW_CATEGORIES[4];$('flowCategory').value=saved().category;}if(k==='category'&&saved().category!==SPEECH_FLOW_CATEGORIES[4]){saved().grammarGroup='';$('flowGrammarGroup').value='';}order=null;stop();batch(true);});}
 $('flowSize').onchange=()=>{saved().size=Number($('flowSize').value);batch(true);};
 for(const[id,v]of [['flowLearn','learn'],['flowReview','review'],['flowSingle','single']])$(id).onclick=()=>{stop();saved().view=v;render();renderList();};
 function nextSingle(delta){const rs=pool();if(!rs.length)return;const at=rs.findIndex(x=>x.id===saved().single),x=rs[(Math.max(at,0)+delta+rs.length)%rs.length];saved().single=x.id;current=x;stop();render();renderList();}
 $('flowPrev').onclick=()=>nextSingle(-1);$('flowNext').onclick=()=>{stop();saved().view==='single'?nextSingle(1):batch(false);};$('flowRestart').onclick=()=>{stop();batch(true);};$('flowStop').onclick=()=>{stop();$('flowAudioStatus').textContent='已停止朗读。';};$('flowRandom').onclick=()=>{const rs=pool();if(!rs.length)return;const x=rs[Math.floor(Math.random()*rs.length)];saved().view='single';saved().single=x.id;current=x;stop();render();renderList();};$('flowShuffle').onclick=()=>{order=pool().map(x=>x.id);for(let i=order.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[order[i],order[j]]=[order[j],order[i]];}batch(true);};
 const previousSave=saveDraft;saveDraft=function(){if(mode!==MODULE)previousSave();};
 const previousFiltered=filtered;filtered=function(){return mode===MODULE?pool():previousFiltered();};
 const previousList=list;list=function(){if(mode===MODULE)renderList();else previousList();};
 const previousShow=show;show=function(x){if(mode!==MODULE)return previousShow(x);if(x){saved().single=x.id;current=x;}activate();};
 const previousSet=setModule;setModule=function(m,fresh=false){stop();previousSet(m,fresh);activate();};
 window.COMBINED_UI.closeVocabulary=()=>setModule([0,1,2,3,4,5,6,7,8,'errors'].includes(state.vocabularyReturnView)?state.vocabularyReturnView:0);
 window.SPEECH_FLOW={pool,sourceFor,field,loadAudio,speak,record:id=>rec(id),items:SPEECH_FLOW_ITEMS,sources:SPEECH_FLOW_SOURCES,render,edit,setStatus};window.addEventListener('pagehide',stop);activate();
})();
