'use strict';
(()=>{
 const M=12,D=T2_ERRORS_DATA,recordMap=new Map(D.records.map(r=>[r.id,r]));
 const E=id=>document.getElementById(id),el=(tag,text='',cls='')=>{const x=document.createElement(tag);x.textContent=text;x.className=cls;return x;};
 const btn=(text,fn,cls='')=>{const b=el('button',text,cls);b.type='button';b.onclick=fn;return b;};
 const norm=s=>String(s||'').trim().toLowerCase().replace(/\s+/g,' ');
 const sig=e=>e.type+'|'+norm(e.fragment||e.original);
 const freqMap=new Map();D.errors.filter(e=>!e.asr).forEach(e=>freqMap.set(sig(e),(freqMap.get(sig(e))||0)+1));
 state.t2Errors={view:'home',type:'',severity:'',boundary:'real',status:'',search:'',recordId:'',mode:'correct',offset:0,...state.t2Errors};
 state.t2ErrorProgress=state.t2ErrorProgress||{};
 const u=()=>state.t2Errors,prog=e=>state.t2ErrorProgress[e.id]||(state.t2ErrorProgress[e.id]={status:'new',favorite:false,notes:'',draft:'',correct:0,wrong:0,lastWrong:null});
 const save=()=>persist(),revealed=new Set();
 const controls=el('section','','hidden');controls.id='t2eControls';
 controls.innerHTML='<h2>口语 Tâche 2 错题本</h2><label>搜索法语 / 中文 / 记录编号<input id="t2eSearch" type="search" placeholder="que、介词、B5-05"></label><label>错误类型<select id="t2eType"><option value="">全部类型</option></select></label><label>影响程度<select id="t2eSeverity"><option value="">全部</option><option value="高">高</option><option value="中">中</option><option value="低">低</option></select></label><label>记录边界<select id="t2eBoundary"><option value="real">真实学习问题</option><option value="all">全部（含疑似ASR）</option><option value="asr">只看疑似ASR</option></select></label><label>学习状态<select id="t2eStatus"><option value="">全部</option><option value="new">未学习</option><option value="mastered">已掌握</option><option value="review">待复习</option><option value="favorite">收藏</option></select></label><label>练习记录编号<input id="t2eRecord" placeholder="B1-01 / B6-17"></label><p id="t2eCount" class="t2e-note"></p><button id="t2eReset" type="button">清除筛选</button>';
 E('practiceFilters').before(controls);D.types.forEach(t=>E('t2eType').add(new Option(t,t)));
 const view=el('section','','hidden');view.id='t2eView';E('practice').before(view);
 function audio(text){const wrap=el('span','','t2e-audio'),status=el('span','','t2e-note');wrap.append(btn('🔊 法语',()=>{const s=window.speechSynthesis;if(!s){status.textContent='浏览器不支持朗读';return;}const vs=s.getVoices().filter(v=>/^fr[-_]/i.test(v.lang));if(!vs.length){status.textContent='请先启用法语语音';return;}s.cancel();const q=new SpeechSynthesisUtterance(text);q.voice=vs.find(v=>/^fr-CA$/i.test(v.lang))||vs.find(v=>/^fr-FR$/i.test(v.lang))||vs[0];q.lang=q.voice.lang;q.onend=()=>status.textContent='朗读完成';s.speak(q);status.textContent='正在朗读';}),status);return wrap;}
 function sync(){[['t2eSearch','search'],['t2eType','type'],['t2eSeverity','severity'],['t2eBoundary','boundary'],['t2eStatus','status'],['t2eRecord','recordId']].forEach(p=>E(p[0]).value=u()[p[1]]||'');}
 function matches(e){const f=u(),p=prog(e),r=recordMap.get(e.recordId);if(f.boundary==='real'&&e.asr)return false;if(f.boundary==='asr'&&!e.asr)return false;if(f.type&&e.type!==f.type)return false;if(f.severity&&e.severity!==f.severity)return false;if(f.recordId&&!e.recordId.toLowerCase().includes(f.recordId.toLowerCase()))return false;if(f.status){if(f.status==='favorite'&&!p.favorite)return false;if(f.status!=='favorite'&&p.status!==f.status)return false;}if(f.search){const hay=JSON.stringify([e.recordId,e.original,e.fragment,e.type,e.correct,e.natural,e.explanation,r&&r.topic,r&&r.scene]).toLowerCase();if(!hay.includes(f.search.toLowerCase()))return false;}return true;}
 function pool(){return D.errors.filter(matches).sort((a,b)=>{const sf=x=>x.severity==='高'?0:x.severity==='中'?1:2;return (u().view==='frequent'?((freqMap.get(sig(b))||1)-(freqMap.get(sig(a))||1)):0)||sf(a)-sf(b)||a.recordId.localeCompare(b.recordId)||a.id.localeCompare(b.id);});}
 function mark(e,ok){const p=prog(e);p.status=ok?'mastered':'review';p[ok?'correct':'wrong']++;if(!ok)p.lastWrong=Date.now();save();render();}
 function card(e){const r=recordMap.get(e.recordId),p=prog(e),f=freqMap.get(sig(e))||1,a=el('article','', 't2e-card '+(e.asr?'asr':e.severity==='高'?'high':e.severity==='中'?'medium':'low'));
  a.append(el('p',e.recordId+' · '+(r?r.topic:'')+' · '+e.type+' · '+e.severity+'影响'+(e.asr?' · 疑似ASR':(!e.asr&&f>1?' · 同类出现 '+f+' 次':'')),'t2e-note'));
  a.append(el('h3',u().mode==='zh-fr'?'根据中文解释说出正确法语':'找出错误并口头改正'));
  a.append(el('p',u().mode==='zh-fr'?e.explanation:e.original,'t2e-prompt'));
  const ta=el('textarea');ta.placeholder='先口头回答，也可以在这里输入……';ta.value=p.draft||'';ta.oninput=()=>{p.draft=ta.value;if(p.status==='new')p.status='learning';save();};a.append(ta);
  a.append(btn(revealed.has(e.id)?'隐藏答案':'显示答案',()=>{revealed.has(e.id)?revealed.delete(e.id):revealed.add(e.id);render();}));
  if(revealed.has(e.id)){const ans=el('div','','t2e-answer');if(!e.asr){ans.append(el('strong','正确表达'),el('p',e.correct),audio(e.correct));if(e.natural&&e.natural!==e.correct)ans.append(el('strong','更自然口语'),el('p',e.natural),audio(e.natural));}else ans.append(el('strong','疑似转写错误：不作为真实语法错误背诵'),el('p',e.correct||e.natural||'建议回听确认'));ans.append(el('p','中文解释：'+e.explanation));const d=el('details'),s=el('summary','查看来源记录');d.append(s,el('p',e.recordId+' · '+(r?r.topic:'')+'\n'+(r?r.scene:'')+'\n原句：'+e.original+'\n错误片段：'+e.fragment));ans.append(d);a.append(ans);}
  const bar=el('div','','t2e-actions');bar.append(btn(p.favorite?'★ 已收藏':'☆ 收藏',()=>{p.favorite=!p.favorite;save();render();}),btn('✅ 已掌握',()=>mark(e,true)),btn('❌ 仍不会',()=>mark(e,false)));a.append(bar);
  const notes=el('details'),sum=el('summary',p.notes?'📝 笔记 · 已保存':'📝 笔记'),tx=el('textarea');tx.value=p.notes||'';tx.oninput=()=>{p.notes=tx.value;sum.textContent='📝 笔记 · 已保存';save();};notes.append(sum,tx);a.append(notes);
  a.append(el('p','状态：'+({new:'未学习',learning:'学习中',mastered:'已掌握',review:'待复习'}[p.status]||p.status)+' · 答对 '+p.correct+' / 待巩固 '+p.wrong,'t2e-note'));return a;}
 function batch(rows){const bar=el('div','','t2e-actions');[['correct','改错模式'],['zh-fr','中 → 法模式']].forEach(k=>bar.append(btn(k[1],()=>{u().mode=k[0];u().offset=0;revealed.clear();save();render();},u().mode===k[0]?'primary':'')));view.append(bar);if(u().offset>=rows.length)u().offset=0;const slice=rows.slice(u().offset,u().offset+10);slice.forEach(e=>view.append(card(e)));if(!rows.length)view.append(el('p','当前筛选没有匹配错题。'));const nav=el('div','','t2e-actions');nav.append(btn('上一批',()=>{u().offset=Math.max(0,u().offset-10);render();}),btn('下一批',()=>{u().offset=u().offset+10>=rows.length?0:u().offset+10;render();}),el('span',rows.length?(u().offset+1)+'–'+(u().offset+slice.length)+' / '+rows.length:'0 条'));view.append(nav);}
 function home(){const real=D.errors.filter(e=>!e.asr),high=real.filter(e=>e.severity==='高').length,mastered=D.errors.filter(e=>prog(e).status==='mastered').length;view.append(el('h2','口语 Tâche 2 · 我的总错题本'),el('p','基于你目前全部真实 Tâche 2 练习整理。疑似 ASR 与真实语言错误分开处理。','t2e-note'));const m=el('div','','t2e-metric');[[D.meta.recordCount,'真实练习'],[D.meta.errorCount,'问题点'],[D.meta.realCount,'真实学习问题'],[D.meta.asrCount,'疑似ASR'],[high,'高影响'],[mastered,'已掌握']].forEach(x=>{const d=el('div');d.append(el('strong',String(x[0])),el('span',x[1]));m.append(d);});view.append(m);const g=el('div','','t2e-home');[['frequent','🔥 高频 / 高影响错题','先处理重复和高影响错误'],['types','🎯 按错误类型练','疑问句、介词、固定搭配、时态……'],['records','🎙 119 条真题回炉','按真实练习记录查看当时错误'],['search','🔎 错题速查','搜索法语、中文、记录编号']].forEach(x=>g.append(btn(x[1]+'\n'+x[2],()=>{u().view=x[0];u().offset=0;save();render();})));view.append(g);}
 function typesView(){const counts=new Map();D.errors.filter(e=>u().boundary==='all'||(u().boundary==='asr'?e.asr:!e.asr)).forEach(e=>counts.set(e.type,(counts.get(e.type)||0)+1));const table=el('table','','t2e-table'),h=el('tr');h.append(el('th','错误类型'),el('th','条数'),el('th','进入专项'));table.append(h);[...counts].sort((a,b)=>b[1]-a[1]).forEach(x=>{const tr=el('tr');tr.append(el('td',x[0]),el('td',String(x[1])));const td=el('td');td.append(btn('练这一类',()=>{u().type=x[0];u().view='search';u().offset=0;sync();save();render();}));tr.append(td);table.append(tr);});view.append(table);}
 function recordsView(){const q=u().search.toLowerCase(),idq=u().recordId.toLowerCase();D.records.filter(r=>(!q||JSON.stringify([r.id,r.topic,r.scene,r.status]).toLowerCase().includes(q))&&(!idq||r.id.toLowerCase().includes(idq))).forEach(r=>{const es=D.errors.filter(e=>e.recordId===r.id&&(u().boundary==='all'||(u().boundary==='asr'?e.asr:!e.asr)));const a=el('article','','t2e-card');a.append(el('h3',r.id+' · '+r.topic),el('p',r.scene||'','t2e-note'),el('p','信息 '+(r.info??'—')+' · 互动 '+(r.interaction??'—')+' · 词汇语法 '+(r.grammar??'—')+' · 发音 '+(r.pronunciation??'—')+' · 流畅 '+(r.fluency??'—')+' · '+(r.status||''),'t2e-note'));const d=el('details'),s=el('summary','查看这条练习的错题 · '+es.length+' 条');d.append(s);es.forEach(e=>d.append(card(e)));a.append(d);view.append(a);});}
 function render(){if(mode!==M)return;view.replaceChildren();sync();const nav=el('nav','','t2e-actions');[['home','错题本首页'],['frequent','🔥 高频错题'],['types','🎯 错误类型'],['records','🎙 119 真题回炉'],['search','🔎 错题速查']].forEach(x=>nav.append(btn(x[1],()=>{u().view=x[0];u().offset=0;save();render();},u().view===x[0]?'primary':'')));view.append(nav);E('t2eCount').textContent=pool().length+' 个匹配条目';if(u().view==='home'){home();return;}if(u().view==='types'){typesView();return;}if(u().view==='records'){recordsView();return;}batch(pool());}
 [['t2eSearch','search','input'],['t2eType','type','change'],['t2eSeverity','severity','change'],['t2eBoundary','boundary','change'],['t2eStatus','status','change'],['t2eRecord','recordId','input']].forEach(x=>E(x[0]).addEventListener(x[2],()=>{u()[x[1]]=E(x[0]).value;u().offset=0;render();save();}));
 E('t2eReset').onclick=()=>{Object.assign(u(),{type:'',severity:'',boundary:'real',status:'',search:'',recordId:'',offset:0});sync();render();save();};
 function activate(){const active=mode===M;controls.classList.toggle('hidden',!active);view.classList.toggle('hidden',!active);if(active){['practiceFilters','practiceStats','practice','errorsView','vocabularyView','batchControls','batchView','studyView','studyReviewView','t2InversionControls','t2InversionView','speechFlowControls','speechFlowView','c1Controls','c1View','oralControls','oralView'].forEach(id=>E(id)?.classList.add('hidden'));render();}}
 const oldSet=setModule;setModule=function(m,fresh=false){window.speechSynthesis?.cancel();if(m===M){if(mode!==M){oldSet(M,fresh);current=null;order=null;}document.querySelectorAll('[data-module]').forEach(b=>{const a=b.dataset.module===String(M);b.classList.toggle('active',a);b.setAttribute('aria-pressed',String(a));});activate();save();}else{oldSet(m,fresh);activate();}};
 const oldDraft=saveDraft;saveDraft=function(){if(mode!==M)oldDraft();};
 window.T2_ERROR_NOTEBOOK={data:D,pool,render,recordMap,progress:prog};activate();
})();