'use strict';
(()=>{
 const M=11,D=window.TRANSFER_DATA,all=[...D.entries,...D.structures],byId=new Map(all.map(e=>[e.id,e]));names[M]='真题语料迁移训练';
 const el=(tag,text='',cls='')=>{const x=document.createElement(tag);x.textContent=text;x.className=cls;return x;};
 const button=(text,fn,cls='')=>{const b=el('button',text,cls);b.type='button';b.onclick=fn;return b;};
 const record=id=>{const r=rec(id);return r.transfer||(r.transfer={status:'new',favorite:false,notes:'',editedContent:null,nextReview:null});};
 const effective=e=>({...e,...record(e.id).editedContent,id:e.id});
 const save=()=>persist();
 state.transferUI={theme:'',page:'overview',level:'',type:'',source:'',review:'due',search:'',index:0,structureGroup:'',...state.transferUI};const ui=()=>state.transferUI;
 let entering=false,revealed=false,editing=null,outputTask=null,activeSpeech=null;
 all.forEach(e=>DATA.push({id:e.id,module:M,fr:effective(e).fr,zh:effective(e).zh,origins:[4],category:e.theme||e.group,members:[{fr:e.fr,zh:e.zh,sourceIndex:4,category:e.theme||e.group,source:e.questions,example:e.t3||e.example,usage:e.t3Source||e.source}]}));
 const controls=el('section','','hidden');controls.id='transferControls';$('practiceFilters').before(controls);
 const view=el('section','','hidden');view.id='transferView';$('practice').before(view);
 const dialog=el('dialog');dialog.id='transferEdit';dialog.innerHTML='<form><h2>✏️ 编辑语料</h2><label>中文<textarea name="zh" required></textarea></label><label>法语词条 / 结构<textarea name="fr" lang="fr" required></textarea></label><label>T3 迁移句 / 结构例句<textarea name="t3" lang="fr"></textarea></label><label>迁移句中文<textarea name="t3zh"></textarea></label><label>备注<textarea name="remarks"></textarea></label><div class="row"><button class="primary" type="submit">保存</button><button type="button" id="transferCancel">取消</button></div></form>';document.body.append(dialog);
 $('transferCancel').onclick=()=>{editing=null;dialog.close();};
 dialog.querySelector('form').onsubmit=event=>{event.preventDefault();const e=byId.get(editing),f=event.currentTarget.elements;record(editing).editedContent={zh:f.zh.value.trim(),fr:f.fr.value.trim(),t3:f.t3.value.trim(),t3zh:f.t3zh.value.trim(),remarks:f.remarks.value.trim()};if(e.group)record(editing).editedContent.example=f.t3.value.trim();updateAdapter(e);dialog.close();editing=null;save();render();};
 function updateAdapter(e){const a=DATA.find(x=>x.id===e.id),v=effective(e);a.fr=v.fr;a.zh=v.zh;}
 function edit(e){editing=e.id;const v=effective(e),f=dialog.querySelector('form').elements;for(const k of ['zh','fr','t3','t3zh','remarks'])f[k].value=k==='t3'&&e.group?v.example||'':v[k]||'';dialog.showModal();}
 function audio(text){const box=el('span','','transfer-audio'),status=el('span','','note');status.setAttribute('role','status');box.append(button('🔊 法语',()=>{const synth=window.speechSynthesis;if(!synth){status.textContent='此浏览器不支持法语朗读';return;}window.TCF_AUDIO?.stop();synth.cancel();const utter=new SpeechSynthesisUtterance(text);const voices=synth.getVoices().filter(v=>/^fr\b/i.test(v.lang));utter.voice=voices.find(v=>v.lang==='fr-FR')||voices.find(v=>v.lang==='fr-CA')||voices[0]||null;utter.lang=utter.voice?.lang||'fr-FR';utter.rate=Number(ui().rate||.9);utter.onend=()=>{status.textContent='朗读完成';activeSpeech=null;};utter.onerror=()=>{status.textContent='朗读失败，请确认系统已启用法语语音后重试';activeSpeech=null;};activeSpeech=utter;synth.speak(utter);status.textContent='正在朗读';}),status);return box;}
 function mark(e,ok){const r=record(e.id),base=rec(e.id);r.status=ok?'mastered':'review';base.attempts++;base[ok?'correct':'wrong']++;base.last=ok;r.nextReview=Date.now()+(ok?3:1)*86400000;if(!ok)base.error={answer:base.draft||'自评：不熟悉',count:(base.error?.count||0)+1,resolved:false,date:new Date().toISOString()};else if(base.error)base.error.resolved=true;save();render();}
 function learned(e){const r=record(e.id);if(r.status==='new')r.status='learning';save();}
 function tools(e){const r=record(e.id),box=el('div','','row');box.append(button(r.favorite?'★ 已收藏':'☆ 收藏',()=>{r.favorite=!r.favorite;save();render();}),button('✏️ 编辑',()=>edit(e)),button('✅ 已掌握',()=>mark(e,true)),button('❌ 不熟悉 / 待复习',()=>mark(e,false)));if(r.editedContent)box.append(button('恢复原始内容',()=>{r.editedContent=null;updateAdapter(e);save();render();}));const notes=el('details');const summary=el('summary',r.notes?'📝 笔记 · 已保存':'📝 笔记'),area=el('textarea');area.value=r.notes;area.setAttribute('aria-label','语料笔记');area.oninput=()=>{r.notes=area.value;summary.textContent='📝 笔记 · 已保存';save();};notes.append(summary,area);box.append(notes);return box;}
 const levels=['A1','A2','B1','B2','C1','C2'];
 function matches(e){const f=ui(),v=effective(e),n=levels.indexOf(e.level);let level=!f.level||e.level===f.level||(f.level==='B1+'&&n>=2)||(f.level==='B2+'&&n>=3)||(f.level==='C1–C2'&&n>=4);let typ=!f.type||e.type===f.type||f.type==='完整迁移句'&&!!e.t3;let source=!f.source||e.source===f.source||f.source===e.t3Source;return (!f.theme||e.theme===f.theme)&&level&&typ&&source&&(!f.search||JSON.stringify(v).toLowerCase().includes(f.search.toLowerCase()));}
 function pool(){return D.entries.filter(matches).sort((a,b)=>b.priority-a.priority||a.table-b.table||a.row-b.row);}
 function reviewRows(rows){const now=Date.now();return rows.filter(e=>{const r=record(e.id);return ui().review==='favorite'?r.favorite:ui().review==='notes'?!!r.notes.trim():ui().review==='unfamiliar'?r.status==='review':ui().review==='due'?r.status==='review'||r.nextReview&&r.nextReview<=now:true;});}
 function select(label,choices,value,onchange){const wrap=el('label',label),s=el('select');s.setAttribute('aria-label',label);choices.forEach(([v,n])=>s.add(new Option(n,v)));s.value=value;s.onchange=()=>onchange(s.value);wrap.append(s);return wrap;}
 function filters(){controls.replaceChildren(el('h2','真题语料迁移训练'));controls.append(select('主题',[['','全部主题'],...D.themes.map(t=>[t,t])],ui().theme,v=>{ui().theme=v;ui().index=0;outputTask=null;save();render();}));
 for(const [key,label,choices] of [['level','等级',[['','全部'],...levels.map(v=>[v,v]),...['B1+','B2+','C1–C2'].map(v=>[v,v])]],['type','内容类型',[['','全部'],...['主题词汇','动词搭配','固定搭配','完整迁移句','连接结构'].map(v=>[v,v])]],['source','来源类型',[['','全部'],['听力原文语料','听力原文语料'],['T3 迁移句 / 整理版','T3 迁移句 / 整理版']]]])controls.append(select(label,choices,ui()[key],v=>{ui()[key]=v;ui().index=0;revealed=false;save();render();}));
 const label=el('label','搜索中文 / 法语'),search=el('input');search.type='search';search.value=ui().search;search.onchange=()=>{ui().search=search.value;ui().index=0;save();render();};label.append(search);controls.append(label,select('法语语速',[['0.75','慢速 0.75×'],['0.9','稍慢 0.9×'],['1','正常 1×']],String(ui().rate||.9),v=>{ui().rate=v;save();}),button('停止朗读',()=>window.speechSynthesis?.cancel()),button('清除筛选',()=>{Object.assign(ui(),{level:'',type:'',source:'',search:'',index:0});save();render();}));controls.append(el('p','听力语料可能来自原文、题干或选项；题号须连同等级回查。右栏迁移句和规范化结构均为整理版。','note'));}
 function go(page){ui().page=page;ui().index=0;revealed=false;outputTask=null;save();render();}
 function metadata(e){return el('p',e.level+' · '+(e.theme||e.group)+' · '+e.type+' · 来源题号 / 素材：'+e.questions,'note');}
 function card(e,sentence=false,cloze=false){const v=effective(e),r=record(e.id),a=el('article','','transfer-card');a.dataset.entryId=e.id;a.append(metadata(e));const prompt=cloze?blank(v.example):null;const zh=sentence?v.t3zh:v.zh;a.append(el('p',prompt?prompt.text:zh,'prompt'));
 const hide=ui().page==='learn'||ui().page==='sentences'||ui().page==='review'||ui().page==='muscle';const visible=!hide||revealed;
 a.append(button(visible?'隐藏法语':'显示答案',()=>{revealed=!visible;learned(e);render();}));
 if(visible){a.append(el('p',sentence?v.t3:v.fr,'transfer-fr'),el('p',sentence?e.t3Source:e.source,'sourceTag'),audio(sentence?v.t3:v.fr));if(prompt)a.append(el('p','填空答案：'+prompt.answers.join(' / ')));if(v.example){a.append(el('p','结构例句 · 整理版'),el('p',v.example,'transfer-fr'),audio(v.example));}if(v.t3&&!sentence){a.append(el('h3','T3 可迁移用法 · 整理版'),el('p',v.t3,'transfer-fr'),audio(v.t3),el('p',v.t3zh));}if(sentence&&!/^[A-ZÀ-Ý]/.test(v.t3))a.append(el('p','原文件此项为迁移短语，原样保留。','note'));if(r.editedContent)a.append(el('p','当前显示你的本地修改版；来源标签说明原始资料。','note'));if(v.remarks)a.append(el('p','备注：'+v.remarks));}
 const draft=el('textarea');draft.lang='fr';draft.placeholder=cloze?'输入空缺的小词，再显示答案核对':'先口头回忆，也可以写下自己的法语；完整迁移句按意思练，不要求逐字一致。';draft.value=rec(e.id).draft;draft.oninput=()=>{rec(e.id).draft=draft.value;learned(e);};a.append(draft,el('p','状态：'+({new:'未学习',learning:'学习中',mastered:'已掌握',review:'待复习'}[r.status]),'note'),tools(e));return a;}
 function blank(text){const answers=[];const stem=text.replace(/(?<![\p{L}])(?:à|de|aux|au|du|des|que|en|pour|avec|dans)(?![\p{L}])|(?<![\p{L}])d[’']/giu,m=>{answers.push(m);return '___';});return answers.length?{text:stem,answers}:null;}
 function browse(rows,sentence=false,muscle=false){if(!rows.length){view.append(el('p','当前范围没有语料。可以调整筛选，或先学习并收藏语料。'));return;}ui().index=Math.min(ui().index,rows.length-1);const e=rows[ui().index];learned(e);const bar=el('div','','row');const move=n=>{ui().index=n;revealed=false;save();render();};bar.append(button('上一条',()=>move(Math.max(0,ui().index-1))),el('span',`${ui().index+1} / ${rows.length}`),button('下一条',()=>move(Math.min(rows.length-1,ui().index+1))),button('随机一条',()=>move(Math.floor(Math.random()*rows.length))));view.append(bar,card(e,sentence,muscle));}
 function table(rows){const wrap=el('div','','transfer-table-wrap'),t=el('table','','transfer-table'),h=el('tr');['中文','法语表达','类型 / 等级','来源 / 练习'].forEach(v=>h.append(el('th',v)));t.append(h);for(const e of rows){const v=effective(e),r=el('tr'),zh=el('td',ui().type==='完整迁移句'?v.t3zh:v.zh),fr=el('td'),actions=el('td');const sentence=ui().type==='完整迁移句';fr.append(el('span',sentence?v.t3:v.fr),audio(sentence?v.t3:v.fr));actions.append(el('p',sentence?e.t3Source:e.source,'sourceTag'),el('p',e.questions,'note'),button('单条练习',()=>{const rows=pool();ui().page=sentence?'sentences':'learn';ui().index=rows.findIndex(x=>x.id===e.id);revealed=false;save();render();}),tools(e));r.append(zh,fr,el('td',(sentence?'完整迁移句':e.type)+' · '+e.level),actions);t.append(r);}wrap.append(t);view.append(wrap);}
 const sample=(rows,n)=>{const a=[...rows];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a.slice(0,n);};
 function output(){if(!ui().theme){view.append(el('p','请先选择一个主题，再从本主题已学习的语料中生成任务。'));return;}const learnedRows=D.entries.filter(e=>e.theme===ui().theme&&record(e.id).status!=='new');if(learnedRows.length<2){view.append(el('p','先学习当前主题至少 2 条语料，再开始主动输出。'));return;}
 if(!outputTask)outputTask={theme:ui().theme,chunks:sample(learnedRows,2+Math.floor(Math.random()*3)),verb:sample(D.structures.filter(s=>s.group==='动词结构'),1)[0],connector:sample(D.structures.filter(s=>s.group==='连接结构'),1)[0]};
 view.append(el('h2','主动输出 · '+ui().theme),el('p','请使用至少 3 个下面的表达，围绕本主题中你熟悉的一个问题说 40–60 秒。先表达观点，再解释原因或举例；不必逐字复述。'));for(const e of [...outputTask.chunks,outputTask.verb,outputTask.connector]){const v=effective(e);const p=el('article','','transfer-card');p.append(el('p',v.zh),el('p',v.fr,'transfer-fr'),audio(v.fr),el('p',e.source,'sourceTag'));view.append(p);}const answer=el('textarea');answer.lang='fr';answer.placeholder='也可以写下你的组合表达（自动保存）';state.transferOutputDrafts=state.transferOutputDrafts||{};answer.value=state.transferOutputDrafts[ui().theme]||'';answer.oninput=()=>{state.transferOutputDrafts[ui().theme]=answer.value;save();};view.append(answer,button('重新抽取',()=>{outputTask=null;render();}),el('p','自检：用了至少 3 个表达？介词完整？连接结构后面的语式正确？观点和例子相互支持？','note'));}
 function library(muscle=false){view.append(el('h2',muscle?'固定结构肌肉记忆':'结构辅助库'),el('p','91 个动词结构 · 41 个连接结构 · 6 组易错提醒。规范化结构与例句属于整理版；素材题号不证明结构逐字出现于原文。','note'));view.append(select('结构类别',[['','全部'],...['动词结构','连接结构','易错结构'].map(v=>[v,v])],ui().structureGroup,v=>{ui().structureGroup=v;ui().index=0;render();save();}));let rows=D.structures.filter(e=>(!ui().structureGroup||e.group===ui().structureGroup)&&(!ui().search||JSON.stringify(effective(e)).toLowerCase().includes(ui().search.toLowerCase()))&&(!ui().type||ui().type===e.type)&&(!ui().source||ui().source===e.source));if(muscle){view.append(select('快速练习',[['structure','中文 → 结构'],['cloze','例句填空']],ui().muscle||'structure',v=>{ui().muscle=v;revealed=false;render();save();}));if(ui().muscle==='cloze')rows=rows.filter(e=>blank(effective(e).example));browse(rows,false,ui().muscle==='cloze');}else{for(const e of rows){const v=effective(e),a=el('article','','transfer-card');a.append(metadata(e),el('p',v.zh),el('p',v.fr,'transfer-fr'),audio(v.fr),el('p',v.example),audio(v.example),tools(e));view.append(a);}const details=el('details');details.append(el('summary','完整原文件说明与原始 Markdown'),el('pre',D.markdownOriginal));view.append(details);}}
 function home(){view.append(el('h2','真题语料迁移训练'),el('p','真题输入 → 语块记忆 → 迁移用法 → 主动输出。按主题学习，等级用于筛选。'));const grid=el('div','','transfer-grid');for(const theme of D.themes){const rows=D.entries.filter(e=>e.theme===theme),learnedCount=rows.filter(e=>record(e.id).status!=='new').length,mastered=rows.filter(e=>record(e.id).status==='mastered').length,due=reviewRowsForCount(rows),fav=rows.filter(e=>record(e.id).favorite).length;const b=button(`${theme}\n${rows.length} 条语料\n${learnedCount} / ${rows.length} 已学习 · ${mastered} 已掌握\n${due} 待复习 · ${fav} 收藏`,()=>{ui().theme=theme;go('overview');});grid.append(b);}view.append(grid);}
 function reviewRowsForCount(rows){return rows.filter(e=>{const r=record(e.id);return r.status==='review'||r.nextReview&&r.nextReview<=Date.now();}).length;}
 function render(){if(mode!==M)return;filters();view.replaceChildren();const nav=el('nav','','row');for(const [key,label]of [['home','九个主题'],['overview','核心语料速览'],['learn','核心语块 · 学习'],['sentences','迁移句 · 学习'],['output','主动输出'],['review','复习模式'],['all','全部语料'],['library','结构辅助库'],['muscle','结构肌肉记忆']])nav.append(button(label,()=>go(key),ui().page===key?'primary':''));view.append(nav);if(ui().page==='home'){home();return;}if(['library','muscle'].includes(ui().page)){library(ui().page==='muscle');return;}if(ui().page==='output'){output();return;}
 view.append(el('h2',ui().theme||'全部主题'));if(ui().page==='overview'){if(!ui().theme){home();return;}view.append(el('h3','主题核心语料速览'),el('p','优先展示具有主动表达和复用价值的语块；完整内容见“全部语料”。','note'));const core=pool().filter(e=>e.priority>=5).slice(0,24);table(core);const details=el('details');details.append(el('summary','主题与各等级适用说明'),el('p',D.themeNotes[ui().theme].join('\n')));view.append(details);return;}
 let rows=pool();if(ui().page==='all'){const pageSize=20,start=ui().index*pageSize;if(start>=rows.length)ui().index=0;view.append(el('p',`${rows.length} 条原始语料；每条同时保留 T3 用法、题号及等级。`));table(rows.slice(ui().index*pageSize,(ui().index+1)*pageSize));view.append(button('上一页',()=>{ui().index=Math.max(0,ui().index-1);render();save();}),button('下一页',()=>{ui().index=(ui().index+1)*pageSize<rows.length?ui().index+1:0;render();save();}));return;}
 if(ui().page==='review'){view.append(select('复习范围',[['due','待复习 / 到期'],['all','按主题全部复习'],['favorite','只复习收藏'],['notes','只复习有笔记'],['random','随机复习'],['unfamiliar','错题 / 不熟悉']],ui().review,v=>{ui().review=v;ui().index=0;revealed=false;render();save();}));rows=reviewRows(rows);if(ui().review==='random')rows=sample(rows,rows.length);}
 browse(rows,ui().page==='sentences'||ui().source==='T3 迁移句 / 整理版'||ui().type==='完整迁移句');save();}
 const hiddenIds=['practiceFilters','practiceStats','practice','errorsView','vocabularyView','batchControls','batchView','studyView','studyReviewView','t2InversionControls','t2InversionView','speechFlowControls','speechFlowView','c1Controls','c1View','oralControls','oralView'];
 const oldSet=setModule;setModule=function(m,fresh=false){window.speechSynthesis?.cancel();window.TCF_AUDIO?.stop();if(m===M){entering=true;try{oldSet(m,fresh);}finally{entering=false;}mode=M;current=null;for(const id of hiddenIds)$(id)?.classList.add('hidden');controls.classList.remove('hidden');view.classList.remove('hidden');render();save();}else{controls.classList.add('hidden');view.classList.add('hidden');oldSet(m,fresh);}};
 const oldShow=show;show=function(x){if(x?.module===M&&!entering){ui().theme=byId.get(x.id).theme||'';ui().page=byId.get(x.id).group?'muscle':'learn';ui().level='';ui().type='';ui().source='';ui().search='';setModule(M);if(byId.get(x.id).group)ui().structureGroup=byId.get(x.id).group;const rows=byId.get(x.id).group?D.structures.filter(e=>e.group===ui().structureGroup):pool();ui().index=Math.max(0,rows.findIndex(e=>e.id===x.id));render();current=x;}else oldShow(x);};
 const oldDraft=saveDraft;saveDraft=function(){if(mode!==M)oldDraft();};
 const oldImport=$('file').onchange;$('file').onchange=async event=>{const file=event.target.files[0];let extra;try{extra=file?JSON.parse(await file.text()):null;}catch{}await oldImport(event);if(extra?.app==='tcf-combined'&&$('toast').textContent.includes('已导入')){state.transferUI={...ui(),...extra.transferUI};state.transferOutputDrafts={...state.transferOutputDrafts,...extra.transferOutputDrafts};all.forEach(updateAdapter);save();render();}};
 window.TRANSFER_TRAINING={data:D,record,effective,pool,reviewRows,blank,render,go,mark};if(window.TRANSFER_RESTORE)setModule(M);if(ui().page==='overview'&&!ui().theme)ui().page='home';
})();
