(()=>{const themes=window.TCF_T2_THEMES||[],subs=window.TCF_T2_SUBS||[],raw=window.TCF_T2_RAW||[],craw=window.TCF_T2_C||[],$=id=>document.getElementById(id);
const generic=raw.map((r,i)=>({id:"g"+(i+1),kind:"generic",theme:themes[r[0]]||"",subcategory:(subs[r[0]]||[])[r[1]]||"",scenario:"",fr:r[2],zh:r[3]}));
const cqs=craw.map((r,i)=>({id:"c"+(i+1),kind:"c",theme:r.theme,subcategory:r.sub,scenario:r.scenario,fr:r.fr,zh:r.zh}));
const all=[...generic,...cqs];
const el={themeFilter:$("themeFilter"),subFilter:$("subFilter"),scenarioFilter:$("scenarioFilter"),searchInput:$("searchInput"),questionList:$("questionList"),randomBtn:$("randomBtn"),reviewOnlyBtn:$("reviewOnlyBtn"),questionCounter:$("questionCounter"),themeName:$("themeName"),subName:$("subName"),promptZh:$("promptZh"),answerBox:$("answerBox"),wordCount:$("wordCount"),checkBtn:$("checkBtn"),revealBtn:$("revealBtn"),clearBtn:$("clearBtn"),resultPanel:$("resultPanel"),scoreValue:$("scoreValue"),scoreMessage:$("scoreMessage"),userDiff:$("userDiff"),answerDiff:$("answerDiff"),prevBtn:$("prevBtn"),nextBtn:$("nextBtn"),statMastered:$("statMastered"),statReview:$("statReview"),statAttempts:$("statAttempts")};
const KEY="tcf-tache2-trainer-v2",saved=(()=>{try{return JSON.parse(localStorage.getItem(KEY)||"{}")}catch{return{}}})(),state={questionId:saved.questionId||all[0]?.id,statuses:saved.statuses||{},attempts:Number(saved.attempts)||0,reviewOnly:false};
function persist(){localStorage.setItem(KEY,JSON.stringify({questionId:state.questionId,statuses:state.statuses,attempts:state.attempts}))}
function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function normalize(s){return String(s||"").normalize("NFC").replace(/[’‘`]/g,"'").replace(/\s+/g," ").trim()}
function tokens(s){return normalize(s).match(/[\p{L}\p{M}]+(?:['’-][\p{L}\p{M}]+)*/gu)||[]}const cmp=t=>t.toLocaleLowerCase("fr");
function lcs(a,b){const A=tokens(a),B=tokens(b),n=A.length,m=B.length,dp=Array.from({length:n+1},()=>new Uint16Array(m+1));for(let i=n-1;i>=0;i--)for(let j=m-1;j>=0;j--)dp[i][j]=cmp(A[i])===cmp(B[j])?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);let i=0,j=0,k=0;const u=[],v=[];while(i<n&&j<m){if(cmp(A[i])===cmp(B[j])){u.push({t:A[i],c:"ok"});v.push({t:B[j],c:"ok"});k++;i++;j++}else if(dp[i+1][j]>=dp[i][j+1])u.push({t:A[i++],c:"extra"});else v.push({t:B[j++],c:"miss"})}while(i<n)u.push({t:A[i++],c:"extra"});while(j<m)v.push({t:B[j++],c:"miss"});return{user:u,answer:v,score:Math.round(2*k/Math.max(1,n+m)*100)}}
function renderTokens(a){return a.map(x=>'<span'+(x.c==="ok"?'':' class="'+x.c+'"')+'>'+esc(x.t)+'</span>').join(" ")}
function current(){return all.find(q=>q.id===state.questionId)||filtered()[0]||all[0]}
function populateThemes(){const ts=[...new Set(all.map(q=>q.theme).filter(Boolean))];el.themeFilter.innerHTML='<option value="">全部大主题（'+all.length+'）</option>'+ts.map(t=>'<option>'+esc(t)+'</option>').join("");populateSubs()}
function populateSubs(){const t=el.themeFilter.value,arr=all.filter(q=>!t||q.theme===t),ss=[...new Set(arr.map(q=>q.subcategory).filter(Boolean))];el.subFilter.innerHTML='<option value="">全部子分类（'+arr.length+'）</option>'+ss.map(s=>'<option>'+esc(s)+'</option>').join("");populateScenarios()}
function populateScenarios(){const t=el.themeFilter.value,s=el.subFilter.value,arr=cqs.filter(q=>(!t||q.theme===t)&&(!s||q.subcategory===s)),sc=[...new Set(arr.map(q=>q.scenario).filter(Boolean))];el.scenarioFilter.innerHTML='<option value="">通用问题 + 全部C层题目</option>'+sc.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join("")}
function filtered(){const t=el.themeFilter.value,s=el.subFilter.value,sc=el.scenarioFilter.value,q=el.searchInput.value.trim().toLowerCase();return all.filter(x=>(!t||x.theme===t)&&(!s||x.subcategory===s)&&(!sc||(x.kind==="c"&&x.scenario===sc))&&(!state.reviewOnly||state.statuses[x.id]==="review")&&(!q||(`${x.zh} ${x.fr} ${x.theme} ${x.subcategory} ${x.scenario}`.toLowerCase().includes(q))))}
function ensure(){const list=filtered();if(list.length&&!list.some(q=>q.id===state.questionId)){state.questionId=list[0].id;persist();reset()}}
function renderList(){ensure();const list=filtered();el.questionList.innerHTML=list.length?list.map((q,i)=>'<button type="button" class="question-item '+(q.id===state.questionId?'active':'')+'" data-id="'+q.id+'"><span class="dot '+(state.statuses[q.id]||"new")+'"></span><span class="num">'+String(i+1).padStart(2,"0")+'</span><span class="zh">'+esc(q.zh)+'</span><span class="fr">'+esc(q.fr)+'</span></button>').join(""):'<div style="padding:20px;color:var(--muted)">没有匹配的题目。</div>';el.questionList.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>{state.questionId=b.dataset.id;persist();reset();render()})}
function renderStats(){const v=Object.values(state.statuses);el.statMastered.textContent=v.filter(x=>x==="mastered").length;el.statReview.textContent=v.filter(x=>x==="review").length;el.statAttempts.textContent=state.attempts}
function renderPractice(){const q=current(),list=filtered();if(!q)return;const idx=Math.max(0,list.findIndex(x=>x.id===q.id));el.questionCounter.textContent=(q.kind==="c"?"C层级 · ":"通用问题 · ")+"当前筛选第 "+(idx+1)+" / "+list.length+" 题";el.themeName.textContent=q.theme;el.subName.textContent=q.subcategory+(q.scenario?" · "+q.scenario:"");el.promptZh.textContent=q.zh;document.querySelectorAll(".status-btn").forEach(b=>b.classList.toggle("active",b.dataset.status===(state.statuses[q.id]||"new")))}
function render(){renderList();renderStats();renderPractice()}function updateCount(){el.wordCount.textContent=tokens(el.answerBox.value).length+" mots"}function reset(){el.answerBox.value="";el.resultPanel.classList.add("hidden");updateCount()}
function check(){const q=current(),u=el.answerBox.value.trim();if(!u){el.answerBox.focus();return}const d=lcs(u,q.fr);el.scoreValue.textContent=d.score+"%";el.scoreMessage.textContent=d.score===100?"完全正确。":d.score>=92?"非常接近，看看标出的细节。":d.score>=80?"大体正确，重点检查变位、介词、冠词或 tu/vous。":"建议先看原句，再清空重写一遍。";el.userDiff.innerHTML=renderTokens(d.user);el.answerDiff.innerHTML=renderTokens(d.answer);el.resultPanel.classList.remove("hidden");state.attempts++;if(d.score===100&&state.statuses[q.id]!=="review")state.statuses[q.id]="mastered";persist();renderStats();renderList()}
function reveal(){const q=current();el.scoreValue.textContent="原句";el.scoreMessage.textContent="对照以后建议清空，再自己写一遍。";el.userDiff.textContent=el.answerBox.value.trim()||"（尚未作答）";el.answerDiff.textContent=q.fr;el.resultPanel.classList.remove("hidden")}
function move(d){const l=filtered();if(!l.length)return;let i=l.findIndex(q=>q.id===state.questionId);if(i<0)i=0;i=(i+d+l.length)%l.length;state.questionId=l[i].id;persist();reset();render()}
populateThemes();el.themeFilter.onchange=()=>{populateSubs();state.questionId=filtered()[0]?.id||all[0]?.id;persist();reset();render()};el.subFilter.onchange=()=>{populateScenarios();state.questionId=filtered()[0]?.id||all[0]?.id;persist();reset();render()};el.scenarioFilter.onchange=()=>{state.questionId=filtered()[0]?.id||all[0]?.id;persist();reset();render()};el.searchInput.oninput=render;el.randomBtn.onclick=()=>{const l=filtered();if(!l.length)return;state.questionId=l[Math.floor(Math.random()*l.length)].id;persist();reset();render()};el.reviewOnlyBtn.onclick=()=>{state.reviewOnly=!state.reviewOnly;el.reviewOnlyBtn.setAttribute("aria-pressed",String(state.reviewOnly));el.reviewOnlyBtn.classList.toggle("secondary",state.reviewOnly);render()};document.querySelectorAll(".status-btn").forEach(b=>b.onclick=()=>{state.statuses[state.questionId]=b.dataset.status;persist();render()});el.answerBox.oninput=updateCount;el.answerBox.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter")check()};el.checkBtn.onclick=check;el.revealBtn.onclick=reveal;el.clearBtn.onclick=reset;el.prevBtn.onclick=()=>move(-1);el.nextBtn.onclick=()=>move(1);render()})();