(()=>{'use strict';
 const api=window.TCF_T2_TRAINER;if(!api)return;
 const css=document.createElement('style');css.textContent='.t2-editor{margin-top:8px}.t2-edit-pencil{background:transparent;border:1px solid #cbd5d0;border-radius:7px;cursor:pointer;padding:5px 9px;font-size:1rem;color:#355b4f}.t2-edit-pencil:hover{background:#eef5f2}.t2-edit-form{padding:12px;margin-top:8px;border:1px solid #cbd5d0;border-radius:10px;background:#f8fbfa}.t2-edit-form label{display:block;font-size:.85rem;font-weight:600;margin:6px 0}.t2-edit-form textarea{width:100%;min-height:65px;box-sizing:border-box;padding:9px;border:1px solid #b8cbc2;border-radius:7px;font:inherit;line-height:1.6;resize:vertical}.t2-edit-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.t2-edit-message{font-size:.85rem;color:#216946;margin:6px 0}.t2-edit-form [role=status]{color:#a53439}';document.head.append(css);
 let serial=0,lastSaved=null;
 function create(q){const box=document.createElement('div'),pencil=document.createElement('button'),message=document.createElement('p');box.className='t2-editor';box.dataset.editQuestion=q.id;pencil.type='button';pencil.className='t2-edit-pencil';pencil.textContent='✎';pencil.title='编辑法语和中文';pencil.setAttribute('aria-label','编辑词条 '+q.zh);message.className='t2-edit-message';message.setAttribute('role','status');if(lastSaved===q.id)message.textContent='已保存';box.append(pencil,message);
 pencil.onclick=()=>{lastSaved=null;message.textContent='';pencil.hidden=true;const form=document.createElement('form');form.className='t2-edit-form';const fr=document.createElement('textarea'),zh=document.createElement('textarea'),error=document.createElement('p'),actions=document.createElement('div');
 for(const [input,name,value,lang] of [[fr,'法语词条',q.fr,'fr'],[zh,'中文意思',q.zh,'zh-CN']]){const label=document.createElement('label');input.id='t2-edit-'+(++serial);label.htmlFor=input.id;label.textContent=name;input.value=value;input.lang=lang;input.required=true;form.append(label,input);}
 const save=document.createElement('button'),cancel=document.createElement('button');save.type='submit';save.className='btn primary';save.textContent='保存';cancel.type='button';cancel.className='btn ghost';cancel.textContent='取消';actions.className='t2-edit-actions';actions.append(save,cancel);error.setAttribute('role','status');form.append(actions,error);box.append(form);cancel.onclick=()=>{form.remove();pencil.hidden=false;pencil.focus();};form.onsubmit=e=>{e.preventDefault();try{lastSaved=q.id;api.saveQuestion(q.id,fr.value,zh.value);}catch(err){lastSaved=null;error.textContent='保存失败：'+err.message+' 请重试。';}};fr.focus();};return box;}
 const single=document.createElement('div');single.id='t2SingleEditor';document.querySelector('.prompt-card').append(single);
 function renderSingle(q){if(q)single.replaceChildren(create(q));}
 window.TCF_T2_EDITOR={create,renderSingle};renderSingle(api.current());
})();
