(()=>{'use strict';
 const api=window.TCF_T2_TRAINER;if(!api)return;const {all,state,filtered,persist}=api,$=id=>document.getElementById(id),s=state.study;
 s.mode=['learn','review'].includes(s.mode)?s.mode:'single';s.size=Number.isInteger(s.size)&&s.size>0?Math.min(s.size,all.length):10;s.ids=Array.isArray(s.ids)?[...new Set(s.ids)].filter(id=>all.some(q=>q.id===id)):[];s.used=Array.isArray(s.used)?s.used:[];s.review=s.review||{ids:[],drafts:{},results:{}};const r=s.review;r.ids=(r.ids||[]).filter(id=>all.some(q=>q.id===id));r.drafts=r.drafts||{};r.results=r.results||{};
 const controls=document.createElement('section');controls.className='t2-study-controls';controls.innerHTML='<strong>练习方式</strong><div class="t2-study-actions"><button id="t2Single" type="button" class="btn ghost">逐题练习</button><button id="t2Learn" type="button" class="btn ghost">学习模式</button><button id="t2Review" type="button" class="btn ghost">复习模式</button></div><label for="t2Size">每批问题数量</label><input id="t2Size" type="number" min="1" step="1" value="10"><div class="t2-study-actions"><button type="button" class="btn ghost" data-t2-size="10">10 个</button><button type="button" class="btn ghost" data-t2-size="20">20 个</button><button type="button" class="btn ghost" data-t2-size="50">50 个</button></div><button id="t2Start" type="button" class="btn secondary">开始这一批</button><p>按当前主题、子分类和 C 层题目筛选。复习只练刚学的同一批问题。</p>';
 document.querySelector('.sidebar').prepend(controls);
 const view=document.createElement('section');view.className='practice hidden';view.id='t2StudyView';view.innerHTML='<h2 id="t2StudyTitle"></h2><p id="t2StudyCaption"></p><p id="t2StudySummary" role="status" aria-live="polite"></p><div class="t2-study-table-wrap"><table class="t2-study-table"><thead><tr><th scope="col">中文问题</th><th id="t2FrenchHeading" scope="col">法语问题</th></tr></thead><tbody id="t2StudyRows"></tbody></table></div><audio id="t2StudyAudio" controls preload="none" hidden style="width:100%;margin-top:16px"></audio><p id="t2AudioStatus" role="status"></p><div class="t2-study-actions"><button id="t2Submit" type="button" class="btn primary">提交本批复习</button><button id="t2ReviewThis" type="button" class="btn primary">复习这一批</button><button id="t2BackLearn" type="button" class="btn secondary">返回学习这一批</button><button id="t2Next" type="button" class="btn secondary">学习下一批</button><button id="t2Stop" type="button" class="btn ghost">停止发音</button></div><p id="t2StudyNote"></p>';
 const original=document.querySelector('.practice');original.after(view);
 const css=document.createElement('style');css.textContent='.t2-study-controls{padding:14px;border:1px solid #dce5e2;border-radius:12px;margin-bottom:16px}.t2-study-controls label{display:block;margin-top:12px}.t2-study-controls input{width:100%;padding:10px;border:1px solid #cbd5d0;border-radius:8px;box-sizing:border-box}.t2-study-actions{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.t2-study-controls p,#t2StudyNote,#t2StudyCaption,#t2AudioStatus{font-size:.9rem;color:#60706b;line-height:1.7}.t2-study-table{width:100%;border-collapse:collapse;table-layout:fixed}.t2-study-table th,.t2-study-table td{padding:14px 10px;text-align:left;vertical-align:top;border-bottom:1px solid #dce5e2;overflow-wrap:anywhere}.t2-study-table th:first-child{width:40%}.t2-study-table textarea{width:100%;min-height:75px;box-sizing:border-box}.t2-study-table small{display:block;margin-top:7px;color:#60706b}.t2-study-feedback{white-space:pre-wrap;line-height:1.7}.t2-study-feedback.bad{color:#a53439}.t2-study-feedback.ok{color:#216946}.t2-study-table [aria-invalid=true]{border-color:#a53439}#t2StudySummary{background:#eef5f2;padding:12px;border-radius:8px}@media(max-width:600px){.t2-study-table th,.t2-study-table td{padding:10px 5px}}';document.head.append(css);
 const filters=()=>({theme:$('themeFilter').value,sub:$('subFilter').value,scenario:$('scenarioFilter').value,search:$('searchInput').value,reviewOnly:state.reviewOnly});
 if(s.filters){$('themeFilter').value=s.filters.theme||'';api.populateSubs();$('subFilter').value=s.filters.sub||'';api.populateScenarios();$('scenarioFilter').value=s.filters.scenario||'';$('searchInput').value=s.filters.search||'';state.reviewOnly=s.filters.reviewOnly===true;$('reviewOnlyBtn').setAttribute('aria-pressed',String(state.reviewOnly));}
 const signature=()=>JSON.stringify(filters()),items=()=> (s.mode==='review'?r.ids:s.ids).map(id=>all.find(q=>q.id===id)).filter(Boolean);
 const audio=$('t2StudyAudio');let request=0,url=null,segments=[],segment=0;
 function stop(){request++;audio.pause();audio.removeAttribute('src');audio.load();audio.hidden=true;if(url)URL.revokeObjectURL(url);url=null;segments=[];segment=0;}
 async function playSegment(token){if(token!==request)return;const data=segments[segment]?.data;if(!data)return;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(new Blob([Uint8Array.from(atob(data.audio),c=>c.charCodeAt(0))],{type:'audio/mpeg'}));audio.src=url;audio.hidden=false;audio.playbackRate=Number($('frenchRate')?.value||1);try{await audio.play();}catch{if(token===request)$('t2AudioStatus').textContent='音频已就绪，请点击播放器播放。';}}
 async function speak(q){stop();window.TCF_PIPER_AUDIO?.stop();const token=request;$('t2AudioStatus').textContent='正在加载法语发音……';try{const loaded=await window.TCF_PIPER_AUDIO.load(q.fr);if(token!==request||s.mode!=='learn')return;segments=loaded;segment=0;$('t2AudioStatus').textContent='正在朗读：'+q.fr;await playSegment(token);}catch(e){if(token===request)$('t2AudioStatus').textContent=e.message+'，请点击发音按钮重试。';}}
 audio.onended=()=>{if(segment+1<segments.length){segment++;playSegment(request);}else $('t2AudioStatus').textContent='朗读完成，可以重听。';};audio.onerror=()=>{$('t2AudioStatus').textContent='音频播放失败，请重试。';};
 function results(){let correct=0,wrong=0,blank=0,pending=0;for(const id of r.ids){const draft=r.drafts[id]||'',result=r.results[id],valid=result&&result.answer===draft,node=$('t2Result-'+id),input=$('t2Answer-'+id);if(!draft.trim())blank++;else if(!valid)pending++;else if(result.score===100)correct++;else wrong++;if(node){node.className='t2-study-feedback '+(valid?(result.score===100?'ok':'bad'):'');node.textContent=valid?(result.score===100?'✓ 正确':'✗ 匹配度 '+result.score+'%\n原句：'+all.find(q=>q.id===id).fr):'';}input?.setAttribute('aria-invalid',String(!!(valid&&result.score!==100)));}$('t2StudySummary').textContent=r.submitted?'本批 '+r.ids.length+' 个：正确 '+correct+'，错误 '+wrong+'，未填写 '+blank+(pending?'，待核对 '+pending:''):'本批 '+r.ids.length+' 个问题，来自刚才学习的同一批。';}
 function render(){stop();const review=s.mode==='review',rows=items();$('t2StudyTitle').textContent='口语 Tâche 2 · '+(review?'复习模式':'学习模式');$('t2StudyCaption').textContent=review?'当前学习批次 · '+rows.length+' 个问题':'当前筛选 '+filtered().length+' 个问题；本批 '+rows.length+' 个。';$('t2FrenchHeading').textContent=review?'你的法语问题':'法语问题';$('t2StudyRows').replaceChildren();for(const [i,q] of rows.entries()){const tr=document.createElement('tr'),zh=document.createElement('td'),fr=document.createElement('td'),meta=document.createElement('small');zh.textContent=(i+1)+'. '+q.zh;meta.textContent=[q.theme,q.subcategory,q.scenario].filter(Boolean).join(' · ');zh.append(meta);if(review){const input=document.createElement('textarea'),feedback=document.createElement('p');input.id='t2Answer-'+q.id;input.lang='fr';input.spellcheck=false;input.autocomplete='off';input.value=r.drafts[q.id]||'';input.setAttribute('aria-label',q.zh+'：复习法语问题');input.oninput=()=>{r.drafts[q.id]=input.value;results();persist();};feedback.id='t2Result-'+q.id;fr.append(input,feedback);}else{const text=document.createElement('p'),button=document.createElement('button');text.textContent=q.fr;text.lang='fr';button.type='button';button.className='btn ghost';button.textContent='🔊 发音';button.setAttribute('aria-label','朗读 '+q.fr);button.onclick=()=>speak(q);fr.append(text,button);}tr.append(zh,fr);$('t2StudyRows').append(tr);}
  for(const id of ['t2Submit','t2BackLearn'])$(id).classList.toggle('hidden',!review);for(const id of ['t2ReviewThis','t2Next','t2Stop'])$(id).classList.toggle('hidden',review);$('t2Submit').disabled=!rows.length;$('t2Next').disabled=!rows.length;$('t2ReviewThis').disabled=!rows.length;$('t2AudioStatus').textContent='';$('t2StudyNote').textContent=review?'按现有原句核对规则，忽略大小写和标点，保留重音、变位、介词、冠词和 tu/vous。未填写项不计错。':'复用已有法语录音。学习不会增加练习次数或改变熟练度。';if(review)results();else $('t2StudySummary').textContent='直接学习中法对照，点击发音按钮听原句。';
 }
 function start(reset){const n=Number($('t2Size').value);if(!Number.isInteger(n)||n<1||n>all.length){$('t2Size').setCustomValidity('请输入 1 到 '+all.length+' 之间的整数。');$('t2Size').reportValidity();return;}$('t2Size').setCustomValidity('');s.size=n;const sig=signature();if(reset||s.scope!==sig){s.used=[];s.scope=sig;}const pool=filtered(),used=new Set(s.used),rows=pool.filter(q=>!used.has(q.id)).slice(0,n);if(!rows.length&&pool.length&&!reset){$('t2StudySummary').textContent='当前筛选已全部学完，点击“开始这一批”可重新开始。';return;}s.ids=rows.map(q=>q.id);s.used=[...new Set([...s.used,...s.ids])];s.mode='learn';sync(false);render();if(!pool.length)$('t2StudySummary').textContent='当前筛选没有问题，请调整筛选条件。';persist();}
 function sync(refresh=true){const review=s.mode==='review',active=s.mode!=='single';original.classList.toggle('hidden',active);view.classList.toggle('hidden',!active);$('t2Size').max=all.length;$('t2Size').value=s.size;for(const [id,mode] of [['t2Single','single'],['t2Learn','learn'],['t2Review','review']]){$(id).classList.toggle('primary',s.mode===mode);$(id).setAttribute('aria-pressed',String(s.mode===mode));}$('t2Review').disabled=!s.ids.length;for(const el of [$('t2Size'),$('t2Start'),...controls.querySelectorAll('[data-t2-size]')])el.disabled=review;s.filters=filters();if(refresh&&active){if(!review&&(s.scope!==signature()||!s.ids.length))start(true);else render();}persist();}
 function learn(){s.mode='learn';sync();}function review(){if(!s.ids.length)return;if(JSON.stringify(r.ids)!==JSON.stringify(s.ids)){r.ids=s.ids.slice();r.drafts={};r.results={};r.submitted=false;}s.mode='review';window.TCF_PIPER_AUDIO?.stop();sync();}
 $('t2Single').onclick=()=>{s.mode='single';stop();sync(false);api.render();};$('t2Learn').onclick=learn;$('t2Review').onclick=review;$('t2ReviewThis').onclick=review;$('t2BackLearn').onclick=learn;$('t2Start').onclick=()=>start(true);$('t2Next').onclick=()=>start(false);$('t2Stop').onclick=()=>{stop();$('t2AudioStatus').textContent='已停止朗读。';};$('t2Size').oninput=()=>{$('t2Size').setCustomValidity('');};controls.querySelectorAll('[data-t2-size]').forEach(b=>b.onclick=()=>{$('t2Size').value=b.dataset.t2Size;start(true);});
 $('t2Submit').onclick=()=>{if(s.mode!=='review')return;for(const id of r.ids){const draft=r.drafts[id]||'';if(!draft.trim()||r.results[id]?.answer===draft)continue;const score=api.lcs(draft,all.find(q=>q.id===id).fr).score;r.results[id]={answer:draft,score};state.attempts++;state.statuses[id]=score===100?'mastered':'review';}r.submitted=true;persist();api.renderStats();results();};
 window.TCF_T2_STUDY={sync};window.addEventListener('pagehide',stop);api.render();
})();
