const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),crypto=require('crypto'),path=require('path');const root=path.resolve(__dirname,'../..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');const source=JSON.parse(read('tache3-exams/work-checkpoint.json')),payload=JSON.parse(read('tache3-exams/exams-2026-07-10.json'));const c={window:{}};vm.runInNewContext(read('data.js'),c);vm.runInNewContext(read('translations.js'),c);assert.equal(c.window.TCF_TOPICS.length,62);assert.equal(payload.migrations.length,32);assert.equal(Object.keys(payload.metadata).length,36);assert.equal(source.records.length,45);assert.equal(new Set(source.records.map(r=>r.recordId)).size,45);
const mapped=Object.values(payload.metadata).flatMap(m=>m.records);assert.equal(mapped.length,45);for(const r of source.records){assert.deepEqual(mapped.find(x=>x.recordId===r.recordId),r);assert.equal(crypto.createHash('sha256').update(JSON.stringify([r.prompt,r.document1,r.document2])).digest('hex'),r.contentSha256);}
for(const [month,n] of Object.entries(source.monthlyCounts))assert.equal(mapped.filter(r=>r.month===month).length,n);
for(const t of payload.migrations){const words=t.paragraphs.map(p=>p.answer).join(' ').split(/\s+/).length;assert.ok(words>=120&&words<=180,t.id);assert.equal(t.translations.length,4);assert.ok(t.translations.every(Boolean));assert.ok(t.reusedPhrases.length>0);assert.ok(t.sourceIds.every(id=>c.window.TCF_TOPICS.some(t=>t.id===id)));assert.match(t.paragraphs[3].answer,/il me semble/);assert.match(t.paragraphs.slice(1).map(p=>p.answer).join(' '),/par exemple/i);}
let JSDOM;try{({JSDOM}=require('jsdom'));}catch{({JSDOM}=require('/tmp/ee3-test-dom/node_modules/jsdom'));}
const KEY='tcf-writing-trainer-v1';let storage={[KEY]:JSON.stringify({lastTopicId:20,lastSegment:2,mode:'full',hint:'zh',statuses:{1:'mastered',20:'review'},attempts:19,cardOrder:{20:[0,1]}}),'tcf-vocabulary-v1:/TCF-writing-trainer':JSON.stringify([{id:'oldword',french:'un logement',chinese:'住房',note:'已有笔记'}])};
function launch(){const dom=new JSDOM(read('index.html'),{url:'https://limengz1129-creator.github.io/TCF-writing-trainer/',runScripts:'outside-only'});const w=dom.window;for(const[k,v]of Object.entries(storage))w.localStorage.setItem(k,v);w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};for(const p of ['data.js','translations.js','tache3-exams/exam-data.js','tache3-exams/study-ui.js','app.js','vocabulary.js'])w.eval(read(p));return {dom,w,d:w.document};}
let {dom,w,d}=launch();const $=id=>d.getElementById(id),click=id=>$(id).click(),items=()=>[...$('topicList').querySelectorAll('[data-id]')];assert.equal(items().length,62);assert.equal($('topicZh').textContent,'职场友谊与职业边界');assert.equal($('statDone').textContent,'1');assert.equal($('statAttempts').textContent,'19');click('revealBtn');assert.equal($('reference').querySelectorAll('.ref-pair').length,4);const pair=$('reference').querySelector('.ref-pair');assert.deepEqual([...pair.children].map(x=>x.className),['ref-fr','ref-note-wrap','ref-zh']);assert.equal(d.querySelector('.vb-launch').textContent,'单词本 (1)');
click('examScopeBtn');assert.equal(items().length,36);for(const[m,n]of Object.entries(source.monthlyCounts)){$('examMonth').value=m;$('examMonth').dispatchEvent(new w.Event('change'));assert.equal(items().length,n);for(let i=0;i<n+1;i++){click('nextBtn');assert.ok(items().some(t=>t.classList.contains('active')));}}
$('examMonth').value='';$('examMonth').dispatchEvent(new w.Event('change'));$('searchInput').value='此搜索无任何结果';$('searchInput').dispatchEvent(new w.Event('input'));assert.ok($('practicePanel').classList.contains('hidden'));$('searchInput').value='';$('searchInput').dispatchEvent(new w.Event('input'));assert.equal(items().length,36);
$('topicList').querySelector('[data-id="1004"]').click();click('revealBtn');const note=$('reference').querySelector('.ref-note');note.value='测试：CV两份材料基本一致';note.dispatchEvent(new w.Event('input'));const p=$('reference').querySelector('.ref-fr');const range=d.createRange();range.setStart(p.firstChild,0);range.setEnd(p.firstChild,3);w.getSelection().addRange(range);p.dispatchEvent(new w.MouseEvent('mouseup',{bubbles:true,clientX:100,clientY:100}));assert.equal(d.querySelector('.vb-select-menu').hidden,false);assert.equal(d.querySelector('.vb-select-highlight').hidden,false);assert.equal(d.querySelector('.vb-select-clear').hidden,false);d.querySelector('.vb-select-highlight').click();assert.equal(p.querySelector('.hl').textContent,'Les');
const exact=w.TCF_EE3_EXAMS.migrations.find(t=>t.id===1004).paragraphs.map(p=>p.answer).join('\n\n');$('answerBox').value=exact;click('checkBtn');assert.equal($('scoreValue').textContent,'100%');assert.equal(JSON.parse(w.localStorage.getItem(KEY)).statuses[1],'mastered');assert.equal(JSON.parse(w.localStorage.getItem(KEY)).attempts,20);
storage=Object.fromEntries(Array.from({length:w.localStorage.length},(_,i)=>w.localStorage.key(i)).map(k=>[k,w.localStorage.getItem(k)]));dom.window.close();({dom,w,d}=launch());assert.equal(items().length,36);click('revealBtn');assert.equal($('reference').querySelector('.ref-note').value,'测试：CV两份材料基本一致');assert.equal($('reference').querySelector('.hl').textContent,'Les');const paragraph=$('reference').querySelector('.ref-fr');d.dispatchEvent(new w.CustomEvent('tcf-clear-paragraph-highlight',{detail:{paragraph}}));assert.equal(paragraph.querySelectorAll('.hl').length,0);assert.equal($('reference').querySelector('.ref-note').value,'测试：CV两份材料基本一致');$('topicList').querySelector('[data-id="1002"]').click();click('revealBtn');assert.equal($('reference').querySelector('.ref-note').value,'');click('baseScopeBtn');assert.equal(items().length,62);assert.ok(items().every(n=>Number(n.dataset.id)<1000));assert.ok($('themeVocabulary').textContent.includes('l’autonomie'));d.querySelector('[data-mode="cards"]').click();click('shuffleCardsBtn');assert.ok($('cardCounter').textContent.includes('主题卡'));click('reviewOnlyBtn');assert.equal(items().length,1);assert.equal(items()[0].dataset.id,'20');d.querySelector('[data-status="mastered"]').click();assert.equal(items().length,0);assert.ok($('practicePanel').classList.contains('hidden'));dom.window.close();console.log('PASS: 45 sources and 90 documents intact; 36 tasks / 4 direct / 32 migrations; word range; old progress/vocabulary; monthly navigation; empty filters; bilingual paragraph ordering; notes/highlights reload and isolation; checking/cards/status.');
