'use strict';
const $=id=>document.getElementById(id),KEY='tcf-eo-t3-corpus-v1';
const topicNames=[...new Set(CORPUS.map(x=>x.topic))];
const questions=[...new Set(CORPUS.map(x=>x.questionId))].map(id=>{const parts=CORPUS.filter(x=>x.questionId===id).sort((a,b)=>a.part-b.part);return{id:'q:'+id,kind:'question',topic:parts[0].topic,categories:[...new Set(parts.map(x=>x.category))],question:parts[0].question,questionNumber:parts[0].questionNumber,summary:parts.map(x=>'主体段 '+x.part+'：'+x.summary).join('\n'),zh:parts.map(x=>x.zh).join('\n\n'),fr:parts.map(x=>x.fr).join('\n\n'),parts};});
const paragraphs=CORPUS.map(x=>({...x,id:'p:'+x.id,kind:'paragraph',categories:[x.category],parts:[x]}));const UNITS=[...paragraphs,...questions],unitById=new Map(UNITS.map(x=>[x.id,x]));
let saved;try{saved=JSON.parse(localStorage.getItem(KEY)||'{}');}catch{saved={};}
let state={version:1,app:'eo-t3-corpus',view:['paragraph','question','errors','argumentMap','frameworks'].includes(saved?.view)?saved.view:'paragraph',current:unitById.has(saved?.current)?saved.current:null,records:saved?.records&&typeof saved.records==='object'&&!Array.isArray(saved.records)?saved.records:{},topic:saved?.topic===''||topicNames.includes(saved?.topic)?saved.topic:topicNames[0],category:typeof saved?.category==='string'?saved.category:'',hint:['zh','summary','first','none'].includes(saved?.hint)?saved.hint:'zh'};let current=null,order=null;
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{$('toast').textContent='保存失败，请导出备份。';}}
function record(id=current?.id){return state.records[id]||(state.records[id]={draft:'',attempts:0,correct:0,wrong:0,last:null,error:null});}
function saveDraft(){if(current){record().draft=$('answer').value;persist();}}
function normalize(s){return s.normalize('NFC').toLocaleLowerCase('fr').replace(/[’‘`]/g,"'");}
function tokenize(s){return [...s.matchAll(/[\p{L}\p{M}]+(?:['’‘`-][\p{L}\p{M}]+)*|\d+(?:[.,]\d+)*/gu)].map(m=>({text:m[0],key:normalize(m[0]),start:m.index,end:m.index+m[0].length}));}
function compare(input,target){const a=tokenize(input),b=tokenize(target);if(a.length>2200||b.length>2200)throw Error('答案过长，请按当前论段或同题三个主体段练习。');const dp=Array.from({length:a.length+1},()=>new Uint16Array(b.length+1));for(let i=a.length-1;i>=0;i--)for(let j=b.length-1;j>=0;j--)dp[i][j]=a[i].key===b[j].key?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);let i=0,j=0,matches=0;const wrong=new Set(),missing=new Set();while(i<a.length&&j<b.length){if(a[i].key===b[j].key){matches++;i++;j++;}else if(dp[i+1][j]>=dp[i][j+1])wrong.add(i++);else missing.add(j++);}while(i<a.length)wrong.add(i++);while(j<b.length)missing.add(j++);return{ok:wrong.size===0&&missing.size===0,score:Math.round(200*matches/Math.max(1,a.length+b.length)),input,target,a,b,wrong,missing};}
function markedLine(node,text,tokens,set,cls){let cursor=0;tokens.forEach((t,i)=>{node.append(document.createTextNode(text.slice(cursor,t.start)));if(set.has(i)){const mark=document.createElement('mark');mark.className=cls;mark.textContent=t.text;node.append(mark);}else node.append(document.createTextNode(t.text));cursor=t.end;});node.append(document.createTextNode(text.slice(cursor)));}
function renderDifference(container,input,target){const diff=compare(input,target),box=document.createElement('div');box.className='answer-difference';const legend=document.createElement('p');legend.className='diff-legend';legend.textContent='红色：写错／多写　绿色：原文中需要补上／替换的词';const grid=document.createElement('div');grid.className='diff-grid';for(const [label,text,tokens,marks,cls]of[['你的答案',input,diff.a,diff.wrong,'diff-wrong'],['原文答案',target,diff.b,diff.missing,'diff-required']]){const section=document.createElement('div'),h=document.createElement('strong'),line=document.createElement('div');h.textContent=label;line.className='diff-line';markedLine(line,text,tokens,marks,cls);section.append(h,line);grid.append(section);}box.append(legend,grid);container.append(box);return diff;}
function selected(unit){return(!$('topic').value||unit.topic===$('topic').value)&&(!$('category').value||unit.categories.includes($('category').value))&&[unit.question,unit.summary,unit.zh].join(' ').toLocaleLowerCase().includes($('search').value.trim().toLocaleLowerCase());}
function filtered(){let items=(state.view==='question'?questions:paragraphs).filter(selected);const range=$('range').value;if(range)items=items.filter(x=>{const r=state.records[x.id];return range==='new'?!r?.attempts:range==='wrong'?r?.error&&!r.error.resolved:r?.last===true;});if(order)items.sort((a,b)=>order.indexOf(a.id)-order.indexOf(b.id));return items;}
function errorItems(){return UNITS.filter(x=>selected(x)&&state.records[x.id]?.error&&($('resolved').checked||!state.records[x.id].error.resolved));}
function stats(){const items=state.view==='errors'?errorItems():filtered();$('total').textContent=items.length;$('done').textContent=items.filter(x=>state.records[x.id]?.attempts).length;$('pending').textContent=items.filter(x=>state.records[x.id]?.error&&!state.records[x.id].error.resolved).length;$('errorCount').textContent=Object.values(state.records).filter(r=>r.error&&!r.error.resolved).length;}
function renderList(){const items=state.view==='errors'?errorItems():filtered();$('list').replaceChildren();$('listCount').textContent=items.length+(state.view==='question'?' 道原题':' 条练习');for(const x of items){const b=document.createElement('button');b.className='item'+(current?.id===x.id?' active':'');b.textContent=x.kind==='paragraph'?x.summary:x.question;const meta=document.createElement('small');meta.textContent=x.topic+' · 第 '+x.questionNumber+' 题'+(x.kind==='paragraph'?' · 主体段 '+x.part:' · 3 个主体段')+(state.records[x.id]?.last===true?' · 已答对':state.records[x.id]?.error&&!state.records[x.id].error.resolved?' · 待复习':'');b.append(meta);b.onclick=()=>{if(state.view==='errors')retry(x);else show(x);};$('list').append(b);}stats();}
function updatePrompt(){if(!current)return;const hint=$('hint').value;$('prompt').textContent=hint==='zh'?current.zh:hint==='summary'?current.summary:hint==='first'?current.parts.map(x=>x.fr.split(/\s+/).slice(0,8).join(' ')+' …').join('\n\n'):'不显示提示，先自行回忆论据与表达。';state.hint=hint;persist();}
function words(){ $('wordCount').textContent=tokenize($('answer').value).length+' mots';}
function show(x){saveDraft();current=x;const fromMap=sessionStorage.getItem('tcf-eo-t3-return-argument-map')==='1';const fromFramework=sessionStorage.getItem('tcf-eo-t3-return-frameworks')==='1';$('argumentReturn')?.classList.toggle('hidden',!fromMap);$('frameworkReturn')?.classList.toggle('hidden',!fromFramework);state.current=x?.id||null;$('practice').classList.toggle('hidden',!x);$('feedback').classList.add('hidden');$('reference').classList.add('hidden');$('reveal').textContent='显示原文';if(!x){$('toast').textContent='这个筛选下暂无练习。';renderList();persist();return;}$('toast').textContent='';$('position').textContent=x.topic+' · '+x.categories.join(' / ')+' · '+(filtered().findIndex(t=>t.id===x.id)+1)+' / '+filtered().length;$('questionTitle').textContent='第 '+x.questionNumber+' 题 · '+x.question+(x.kind==='paragraph'?' · 主体段 '+x.part:'');$('summary').textContent=x.kind==='question'?'同一原题的三个主体段合练；各段可能属于不同论据子话题。':x.summary;$('summary').classList.toggle('hidden',$('hint').value==='none');$('answer').value=record().draft;$('answer').placeholder=x.kind==='question'?'依次默写主体段 1、2、3……':'根据中文提示，默写这个主体论段……';$('source').textContent=x.parts.map(p=>p.sourceFile+'\n原文第 '+p.sourceParagraph+' 个段落标题 · 原题 '+p.questionNumber+' · 主体段 '+p.part+' · '+p.category).join('\n\n');updatePrompt();words();renderList();persist();}
function categories(){const old=$('category').value||state.category;const items=CORPUS.filter(x=>!$('topic').value||x.topic===$('topic').value);$('category').replaceChildren(new Option('全部论据子话题',''));for(const c of [...new Set(items.map(x=>x.category))])$('category').add(new Option(c+' · '+items.filter(x=>x.category===c).length+' 段',c));$('category').value=[...$('category').options].some(o=>o.value===old)?old:'';$('scopeNote').textContent=state.view==='question'?'按子话题找到含该论据的原题；合练时仍包含该题全部三个主体段。':'子话题分类沿用文档标题，每次练习一个主体论段。';}
function setView(view){saveDraft();state.view=view;current=null;order=null;document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',b.dataset.view===view);});$('errorsView').classList.toggle('hidden',view!=='errors');$('argumentMapView').classList.toggle('hidden',view!=='argumentMap');$('frameworkView').classList.toggle('hidden',view!=='frameworks');$('practice').classList.toggle('hidden',view==='errors'||view==='argumentMap'||view==='frameworks');$('range').disabled=view==='errors'||view==='argumentMap'||view==='frameworks';categories();if(view==='argumentMap'){$('list').replaceChildren();const meta=window.CORPUS_ARGUMENT_MAP?.getMeta?.($('topic').value)||{mothers:0,paragraphs:0,title:$('topic').value||'论点地图'};$('listCount').textContent=meta.title+' · '+meta.mothers+' 个母论点';$('total').textContent=meta.mothers;$('done').textContent=meta.paragraphs;$('pending').textContent='0';window.CORPUS_ARGUMENT_MAP?.render();persist();return;}if(view==='frameworks'){$('list').replaceChildren();const meta=window.CORPUS_OPENING_CLOSING?.getMeta?.()||{openings:169,closings:169,subjunctive:126};$('listCount').textContent='开头 / 结尾框架 · 169 道原题';$('total').textContent=meta.openings;$('done').textContent=meta.closings;$('pending').textContent=meta.subjunctive;window.CORPUS_OPENING_CLOSING?.render();persist();return;}if(view==='errors'){renderErrors();renderList();persist();return;}const saved=unitById.get(state.current),items=filtered();show(items.includes(saved)?saved:items[0]||null);}
function check(){if(!current)return;const input=$('answer').value.trim();if(!input){$('toast').textContent='请先写出法语再检查。';return;}let result;try{result=compare(input,current.fr);}catch(e){$('toast').textContent=e.message;return;}saveDraft();const r=record();r.attempts++;r.last=result.ok;r[result.ok?'correct':'wrong']++;if(!result.ok)r.error={answer:input,count:(r.error?.count||0)+1,resolved:false,date:new Date().toISOString(),score:result.score};else if(r.error)r.error.resolved=true;$('feedback').replaceChildren();$('feedback').className='feedback '+(result.ok?'ok':'bad');const h=document.createElement('p');h.className='result-head';h.textContent=result.ok?'✓ 与原文一致 · 100%':'与原文的词语相似度：'+result.score+'% · 已加入错题本';$('feedback').append(h);if(!result.ok)renderDifference($('feedback'),input,current.fr);window.TCF_CORPUS_CONJUGATIONS?.render($('feedback'),current.fr);window.TCF_NOUNS?.render($('feedback'),current.fr);renderList();persist();}
function retry(x){$('topic').value=x.topic;state.topic=x.topic;state.category='';$('category').value='';$('search').value='';$('range').value='';setView(x.kind);show(x);$('answer').focus();}
function renderErrors(){const items=errorItems();$('errors').replaceChildren();if(!items.length){const p=document.createElement('p');p.className='empty';p.textContent='这个筛选下没有错题。';$('errors').append(p);}for(const x of items){const r=state.records[x.id].error,box=document.createElement('article');box.className='errorItem';const meta=document.createElement('small');meta.textContent=x.topic+' · 第 '+x.questionNumber+' 题 · '+(x.kind==='paragraph'?'主体段 '+x.part:'同题主体合练')+' · 错 '+r.count+' 次 · '+(r.resolved?'已订正':'待复习');const p=document.createElement('p');p.textContent=x.kind==='paragraph'?x.summary:x.question;const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='查看高亮纠错与动词变位';details.append(summary);let rendered=false;details.addEventListener('toggle',()=>{if(details.open&&!rendered){renderDifference(details,r.answer,x.fr);window.TCF_CORPUS_CONJUGATIONS?.render(details,x.fr);window.TCF_NOUNS?.render(details,x.fr);rendered=true;}});const b=document.createElement('button');b.textContent='重新练习';b.onclick=()=>retry(x);box.append(meta,p,details,b);$('errors').append(box);}stats();}
$('topic').replaceChildren(new Option('全部 9 个大话题',''));for(const topic of topicNames)$('topic').add(new Option(topic+' · '+CORPUS.filter(x=>x.topic===topic).length+' 段',topic));$('topic').value=state.topic;$('hint').value=state.hint;categories();
for(const id of ['topic','category','range','search'])$(id).addEventListener(id==='search'?'input':'change',()=>{saveDraft();order=null;if(id==='topic'){state.category='';$('category').value='';categories();}state.topic=$('topic').value;state.category=$('category').value;if(state.view==='argumentMap'){setView('argumentMap');return;}if(state.view==='frameworks'){setView('frameworks');return;}state.view==='errors'?(renderErrors(),renderList()):show(filtered()[0]||null);});
for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>{if(b.dataset.view!=='paragraph')sessionStorage.removeItem('tcf-eo-t3-return-argument-map');setView(b.dataset.view);};$('backToArgumentMap').onclick=()=>{sessionStorage.removeItem('tcf-eo-t3-return-argument-map');setView('argumentMap');};$('backToFrameworks').onclick=()=>{const mode=sessionStorage.getItem('tcf-eo-t3-framework-mode')||'opening';sessionStorage.removeItem('tcf-eo-t3-return-frameworks');window.CORPUS_OPENING_CLOSING?.setMode?.(mode);setView('frameworks');};$('vocabTab').onclick=()=>window.CORPUS_VOCAB?.open();$('answer').oninput=()=>{saveDraft();words();};$('answer').onkeydown=e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();check();}};$('hint').onchange=()=>{updatePrompt();$('summary').classList.toggle('hidden',$('hint').value==='none');};$('check').onclick=check;window.TCF_GRAMMAR_TARGET=()=>current?({fr:current.fr,zh:current.zh,usage:current.usage||''}):null;$('reveal').onclick=()=>{if(!current)return;const opening=$('reference').classList.contains('hidden');$('reference').replaceChildren();const text=document.createElement('p');text.textContent=current.fr;$('reference').append(text);window.TCF_CORPUS_CONJUGATIONS?.render($('reference'),current.fr);window.TCF_NOUNS?.render($('reference'),current.fr);$('reference').classList.toggle('hidden',!opening);$('reveal').textContent=opening?'隐藏原文':'显示原文';};$('clear').onclick=()=>{$('answer').value='';saveDraft();words();$('feedback').classList.add('hidden');};$('resolved').onchange=()=>{renderErrors();renderList();};
function move(delta){const xs=filtered(),index=xs.findIndex(x=>x.id===current?.id)+delta;if(index>=0&&index<xs.length)show(xs[index]);else $('toast').textContent='已到当前列表边界。';}$('prev').onclick=()=>move(-1);$('next').onclick=()=>move(1);$('random').onclick=()=>{const xs=state.view==='errors'?errorItems():filtered();if(xs.length){const x=xs[Math.floor(Math.random()*xs.length)];state.view==='errors'?retry(x):show(x);}};$('shuffle').onclick=()=>{order=filtered().map(x=>x.id);for(let i=order.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[order[i],order[j]]=[order[j],order[i]];}state.view==='errors'?renderList():show(filtered()[0]||null);};
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}$('export').onclick=()=>{saveDraft();download(new Blob([JSON.stringify({...state,vocabulary:window.CORPUS_VOCAB?.getWords()||[]},null,2)],{type:'application/json'}),'EO-T3-语料默写-进度与单词本.json');};$('import').onclick=()=>$('backupFile').click();$('backupFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const x=JSON.parse(await f.text());if(x.app!=='eo-t3-corpus'||x.version!==1||!x.records||Array.isArray(x.records)||typeof x.records!=='object')throw Error('请选择本网页导出的备份文件。');for(const[id,r]of Object.entries(x.records)){if(!unitById.has(id)||!r||typeof r.draft!=='string'||typeof r.last!=='boolean'&&r.last!==null||!['attempts','correct','wrong'].every(k=>Number.isInteger(r[k])&&r[k]>=0)||r.error&&(typeof r.error.answer!=='string'||r.error.answer.length>50000||typeof r.error.resolved!=='boolean'||!Number.isInteger(r.error.count)))throw Error('备份记录格式不正确。');}if(x.vocabulary&&!window.CORPUS_VOCAB?.validate(x.vocabulary))throw Error('单词本格式不正确。');if(x.vocabulary&&!window.CORPUS_VOCAB.importWords(x.vocabulary))throw Error('单词本未能保存。');state.records={...state.records,...x.records};persist();state.view==='errors'?(renderErrors(),renderList()):show(current);$('toast').textContent='进度与单词本已导入。';}catch(err){$('toast').textContent=err.message;}e.target.value='';};
for(const topic of topicNames){const xs=CORPUS.filter(x=>x.topic===topic),p=document.createElement('p');p.className='note';p.textContent=topic+'：'+xs.length+' 段 / '+new Set(xs.map(x=>x.questionId)).size+' 题 / '+new Set(xs.map(x=>x.category)).size+' 个子话题';$('audit').append(p);}
window.CORPUS_OPEN_PARAGRAPH=id=>{const x=paragraphs.find(p=>p.id==='p:'+id);if(!x)return;$('topic').value=x.topic;state.topic=x.topic;state.category=x.category;$('category').value=x.category;setView('paragraph');$('category').value=x.category;state.category=x.category;show(x);};window.CORPUS_OPEN_QUESTION=(topic,n,mode='opening')=>{const x=questions.find(q=>q.topic===topic&&q.questionNumber===n);if(!x)return;sessionStorage.setItem('tcf-eo-t3-return-frameworks','1');sessionStorage.setItem('tcf-eo-t3-framework-mode',mode);$('topic').value=topic;state.topic=topic;state.category='';$('category').value='';setView('question');show(x);};window.CORPUS_OPEN_TOPIC_QUESTIONS=(topic,mode='virtual')=>{const x=questions.find(q=>q.topic===topic);if(!x)return;sessionStorage.setItem('tcf-eo-t3-return-frameworks','1');sessionStorage.setItem('tcf-eo-t3-framework-mode',mode);$('topic').value=topic;state.topic=topic;state.category='';$('category').value='';setView('question');show(x);};window.CORPUS_CONTEXT=()=>current?current.topic+' · '+current.categories.join(' / ')+' · 第 '+current.questionNumber+' 题':'口语 Tâche 3 语料库';window.CORPUS_TEST={CORPUS,paragraphs,questions,compare,tokenize};setView(state.view);
