const fs=require('fs'),vm=require('vm');const c={window:{}};vm.runInNewContext(fs.readFileSync('data.js','utf8'),c);vm.runInNewContext(fs.readFileSync('translations.js','utf8'),c);const base=c.window.TCF_TOPICS,tr=c.window.TCF_TRANSLATIONS;const checkpoint=JSON.parse(fs.readFileSync('tache3-exams/work-checkpoint.json'));const records=checkpoint.records;const specs=require('./draft-specs.json');const aliases={'2026-09-02':'2026-08-08','2026-09-03':'2026-07-11','2026-09-06':'2026-08-15','2026-09-07':'2026-08-04','2026-09-10':'2026-08-14','2026-09-11':'2026-08-05','2026-10-02':'2026-09-13','2026-10-03':'2026-08-02','2026-10-04':'2026-08-14'};const direct={'2026-07-09':{id:20,relation:'补充',question:'职场友谊如何兼顾合作与职业边界？',reason:'原20的友谊收益、群体排他、客观决策和边界立场均与两份材料一致；179词。'},'2026-08-08':{id:58,relation:'不同角度',question:'如何区分娱乐狩猎和不同实际用途？',reason:'原58概括反对娱乐杀戮与多种实际动机，并未把材料2误写为全面支持狩猎；立场限制娱乐并严格监管。177词。'},'2026-08-11':{id:43,relation:'部分一致',question:'城市限行怎样依靠设施和例外许可实现有效过渡？',reason:'原43的环境安全收益、公交停车与必要职业例外，与材料2有条件接受一致；179词。'},'2026-09-04':{id:61,relation:'对立',question:'公共资金是否应举办大型体育赛事？',reason:'原61对照文化经济、就业设施与债务、健康教育支出，个人立场谨慎评估；178词。'}};
const splitFr=s=>s.split(/(?<=[.!?])\s+/).filter(Boolean),splitZh=s=>s.match(/[^。！？]+[。！？]?/g)||[];const wc=s=>s.trim().split(/\s+/).length;const out=[];const mismatch=[];
for(const [i,s] of specs.entries()){
 const b=base.find(t=>t.id===s.base);const select=(pi)=>{const f=splitFr(b.paragraphs[pi].answer),z=splitZh(tr[b.id][pi]);if(f.length!==z.length)mismatch.push({key:s.key,base:b.id,pi,f:f.length,z:z.length});return {f:f.slice(0,2).join(' '),z:f.length===z.length?z.slice(0,2).join(''):tr[b.id][pi],parts:f,zhparts:z};};
 let p2=select(1),p3=select(2);if(s.extraFr){if(['2026-08-02','2026-09-08'].includes(s.key))p2={f:s.extraFr,z:s.extraZh};else p3={f:s.extraFr,z:s.extraZh};}
 if([9,29].includes(b.id)){p2.z=b.id===9?'一方面，如果自动售货机提供合适的饮料，它们可以很有用。课间休息时，一些学生并不总有时间去食堂。':'一方面，肉类是蛋白质、维生素和某些重要矿物质的重要来源。它因此可以成为均衡饮食的一部分。';}
 const thirdExample=['2026-07-03','2026-07-05','2026-07-10','2026-08-05','2026-08-07','2026-08-09','2026-08-10','2026-09-05','2026-09-13'].includes(s.key);
 const alreadyExample=/par exemple/i.test(p2.f);
 let ps=[s.fr,p2.f+(!thirdExample&&!alreadyExample?' '+s.exampleFr:''),p3.f+(thirdExample?' '+s.exampleFr:''),b.paragraphs[3].answer],zs=[s.zh,p2.z+(!thirdExample&&!alreadyExample?s.exampleZh:''),p3.z+(thirdExample?s.exampleZh:''),tr[b.id][3]];
 if(s.key==='2026-10-01'){ps[3]='Pour conclure, il me semble que les nouvelles technologies sont utiles si leur usage reste raisonnable. Parallèlement, il faudrait que les parents et les écoles trouvent un équilibre entre les outils numériques, le jeu libre et les activités physiques.';zs[3]='总而言之，我认为合理使用时，新技术是有用的。与此同时，父母与学校应在数字工具、自由游戏和身体活动之间找到平衡。';}
 // Keep complete reused sentences; shorten only the optional second explanatory sentence.
 if(wc(ps.join(' '))>180&&splitFr(p2.f).length>1){const f=splitFr(p2.f),z=splitZh(p2.z);if(f.length===z.length){ps[1]=f[0]+(!thirdExample&&!alreadyExample?' '+s.exampleFr:'');zs[1]=z[0]+(!thirdExample&&!alreadyExample?s.exampleZh:'');}}
 if(wc(ps.join(' '))>180&&splitFr(p3.f).length>1){const f=splitFr(p3.f),z=splitZh(p3.z);if(f.length===z.length){ps[2]=f[0]+(thirdExample?' '+s.exampleFr:'');zs[2]=z[0]+(thirdExample?s.exampleZh:'');}}
 if(wc(ps.join(' '))>180)throw Error(s.key+' '+wc(ps.join(' ')));
 const sourceIds=s.sources||[s.base];const pool=sourceIds.map(id=>base.find(t=>t.id===id).paragraphs.map(p=>p.answer).join(' ')).join(' ');const token=s=>(s.toLocaleLowerCase('fr').normalize('NFC').match(/[\p{L}\p{M}]+(?:[’'][\p{L}\p{M}]+)*/gu)||[]);const known=new Set(token(pool));const newWords=[...new Set(token(ps.join(' ')).filter(w=>!known.has(w)))];
 const topic={id:1001+i,section:b.section,subsection:b.subsection,zhTitle:records.find(r=>r.recordId===s.key).zhTitle,frTitle:records.find(r=>r.recordId===s.key).prompt,examOnly:true,paragraphs:ps.map((answer,j)=>({role:['Synthèse des documents','Argument personnel','Nuance et limites','Conclusion'][j],hintZh:zs[j],answer})),translations:zs,sourceIds,wordCount:wc(ps.join(' ')),newMemory:{newDistinctFormsComparedWithWholeCorpus:newWords.filter(w=>!new Set(token(base.map(t=>t.paragraphs.map(p=>p.answer).join(' ')).join(' '))).has(w)).length,newDistinctFormsComparedWithSources:newWords.length,newForms:newWords,measurement:'相对列出的来源文章，按法语词形去重；不是词汇难度或百分比估计。',newContent:'准确材料摘要、针对题目的例子'+(s.extraFr?'及任务差异段':'')},reusedExpressions:sourceIds.map(id=>({id,title:base.find(t=>t.id===id).zhTitle})),reuseTypes:['主题名词与动词搭配','优点/风险论点模块','条件或让步','结论与建议'],newExpressions:[s.exampleFr,...(s.extraFr?[s.extraFr]:[])]};out.push(topic);s.topicId=topic.id;s.total=topic.wordCount;
}
const metadata={};for(const r of records){const key=aliases[r.recordId]||r.recordId,d=direct[key],s=specs.find(x=>x.key===key);if(!d&&!s)throw Error(r.recordId);const id=d?d.id:s.topicId;if(!metadata[id])metadata[id]={topicId:id,type:d?'direct':'migration',recordIds:[],months:[],records:[],relation:d?d.relation:s.relation,centralQuestion:d?d.question:s.question,matchReason:d?d.reason:s.reason,sourceIds:d?[d.id]:(s.sources||[s.base]),summaryFr:d?base.find(t=>t.id===id).paragraphs[0].answer:s.fr,summaryZh:d?tr[id][0]:s.zh};metadata[id].recordIds.push(r.recordId);metadata[id].records.push(r);if(!metadata[id].months.includes(r.month))metadata[id].months.push(r.month);}
for(const m of Object.values(metadata)){m.material1Core=m.summaryZh.split(/[。；]/)[0];m.material2Core=m.summaryZh.split(/[。；]/).slice(1).join('。');m.personalPosition=tr[m.topicId]?.[3]||out.find(t=>t.id===m.topicId).translations[3];}
const cores=require('./material-cores.json');for(const m of Object.values(metadata)){[m.material1Core,m.material2Core]=cores[aliases[m.recordIds[0]]||m.recordIds[0]];m.checks={topic:'一致',document1:'按原材料概括',document2:'按原材料概括',relationship:m.relation,centralDispute:m.centralQuestion,personalPosition:m.personalPosition};}
for(const t of out){const pool=t.sourceIds.flatMap(id=>base.find(x=>x.id===id).paragraphs.flatMap(p=>splitFr(p.answer)));t.reusedPhrases=[...new Set(t.paragraphs.slice(1).flatMap(p=>splitFr(p.answer)).filter(s=>pool.includes(s)))].slice(0,5);t.newExpressions=t.newExpressions.filter(x=>t.paragraphs.some(p=>p.answer.includes(x)));}
const payload={schemaVersion:1,monthlyCounts:checkpoint.monthlyCounts,totalMonthlyRecords:45,independentTasks:Object.keys(metadata).length,exactOriginalVariants:checkpoint.exactDistinctOriginals,directArticles:Object.values(metadata).filter(x=>x.type==='direct').length,migrationArticles:out.length,metadata,migrations:out};fs.writeFileSync('tache3-exams/exams-2026-07-10.json',JSON.stringify(payload,null,2)+'\n');fs.writeFileSync('tache3-exams/exam-data.js','window.TCF_EE3_EXAMS = '+JSON.stringify(payload,null,2)+';\n');fs.writeFileSync('tache3-exams/matching-audit.md','# 2026年7–10月 Tâche 3 核对\n\n45条月度记录，36道按材料观点与中心争议去重的独立任务，41份逐字不同的原题版本（含标点、引文署名、末尾换行差异）。不同月份的完整原文均独立保留。原62篇未改动。\n\n'+Object.values(metadata).map(m=>`## ${m.months.join(' / ')} · ${m.records[0].prompt}\n\n- ${m.type==='direct'?'原库直接匹配':'真题迁移改写版'} · 文章 ${m.topicId}\n- 月度记录：${m.recordIds.join(' / ')}\n- 材料关系：${m.relation}\n- 核心问题：${m.centralQuestion}\n- 材料摘要：${m.summaryZh}\n- 匹配理由：${m.matchReason}\n- 语料来源：${m.sourceIds.join(' / ')}\n- 个人立场：${m.personalPosition}\n`).join('\n'));console.log(JSON.stringify({counts:[payload.independentTasks,payload.directArticles,payload.migrationArticles],mismatch,wordCounts:out.map(x=>[x.id,x.zhTitle,x.wordCount])},null,2));
